<a href="https://colab.research.google.com/github/leonardosilva-sepl/Consulta_ITP24-25_PR/blob/main/AUTP_ITP2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Instalações e Imports

In [1]:
import nest_asyncio
nest_asyncio.apply()

In [2]:
#SELENIUM E SUAS DEPENDENCIAS
%pip install selenium==4.41.0
%pip install webdriver-manager==4.0.2
!pip install selenium-stealth==1.0.6
!pip install undetected-chromedriver==3.5.5
!pip install pypdfium2==5.6.0

Collecting selenium==4.41.0
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium==4.41.0) (2026.2.25)
Collecting trio<1.0,>=0.31.0 (from selenium==4.41.0)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium==4.41.0)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium==4.41.0) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium==4.41.0)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium==4.41.0) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium==4.41.0) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium==4.41.0)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium==4.41.0) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium==4.41.0)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium==4.41.0) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium==4.41.0)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium==4.41.0) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium==4.41.0) (0.16.0)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 210.6 kB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 210.8 kB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 163.4 kB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.41.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2
Collecting webdriver-manager==4.0.2
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager==4.0.2) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager==4.0.2) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager==4.0.2) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager==4.0.2) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager==4.0.2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager==4.0.2) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager==4.0.2) (2026.2.25)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2
Collecting selenium-stealth==1.0.6
  Downloading selenium_stealth-1.0.6-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (from selenium-stealth==1.0.6) (4.41.0)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth==1.0.6) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth==1.0.6) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth==1.0.6) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth==1.0.6) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->selenium-stealth==1.0.6) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth==1.0.6) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth==1.0.6) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth==1.0.6) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth==1.0.6) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth==1.0.6) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth==1.0.6) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth==1.0.6) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->selenium-stealth==1.0.6) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth==1.0.6) (0.16.0)
Downloading selenium_stealth-1.0.6-py3-none-any.whl (32 kB)
Installing collected packages: selenium-stealth
Successfully installed selenium-stealth-1.0.6
Collecting undetected-chromedriver==3.5.5
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: selenium>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver==3.5.5) (4.41.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver==3.5.5) (2.32.4)
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver==3.5.5) (15.0.1)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver==3.5.5) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver==3.5.5) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver==3.5.5) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver==3.5.5) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver==3.5.5) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver==3.5.5) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->undetected-chromedriver==3.5.5) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->undetected-chromedriver==3.5.5) (3.11)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver==3.5.5) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver==3.5.5) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver==3.5.5) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver==3.5.5) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver==3.5.5) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver==3.5.5) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver==3.5.5) (0.16.0)
Building wheels for collected packages: undetected-chromedriver
  Building wheel for undetected-chromedriver (setup.py) ... done
  Created wheel for undetected-chromedriver: filename=undetected_chromedriver-3.5.5-py3-none-any.whl size=47047 sha256=a35c3f412a5e69e3d7b0c8c753933a9792369406e1bc9c41439442e8b34e87ff
  Stored in directory: /root/.cache/pip/wheels/c4/f1/aa/9de6cf276210554d91e9c0526864563e850a428c5e76da4914
Successfully built undetected-chromedriver
Installing collected packages: undetected-chromedriver
Successfully installed undetected-chromedriver-3.5.5
Collecting pypdfium2==5.6.0
  Downloading pypdfium2-5.6.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 kB 1.2 MB/s eta 0:00:00
Downloading pypdfium2-5.6.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 221.5 kB/s eta 0:00:00
Installing collected packages: pypdfium2
Successfully installed pypdfium2-5.6.0

In [3]:
#SCRAPLING
!pip install "scrapling[fetchers]==0.4.3"
!scrapling install

Collecting scrapling==0.4.3 (from scrapling[fetchers]==0.4.3)
  Downloading scrapling-0.4.3-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: lxml>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from scrapling==0.4.3->scrapling[fetchers]==0.4.3) (6.0.2)
Collecting cssselect>=1.4.0 (from scrapling==0.4.3->scrapling[fetchers]==0.4.3)
  Downloading cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: orjson>=3.11.7 in /usr/local/lib/python3.12/dist-packages (from scrapling==0.4.3->scrapling[fetchers]==0.4.3) (3.11.8)
Collecting tld>=0.13.2 (from scrapling==0.4.3->scrapling[fetchers]==0.4.3)
  Downloading tld-0.13.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting w3lib>=2.4.1 (from scrapling==0.4.3->scrapling[fetchers]==0.4.3)
  Downloading w3lib-2.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from scrapling==0.4.3->scrapling[fetchers]==0.4.3) (4.15.0)
Requirement already satisfied: click>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]==0.4.3) (8.3.1)
Requirement already satisfied: curl_cffi>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]==0.4.3) (0.14.0)
Collecting playwright==1.58.0 (from scrapling[fetchers]==0.4.3)
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Collecting patchright==1.58.2 (from scrapling[fetchers]==0.4.3)
  Downloading patchright-1.58.2-py3-none-manylinux1_x86_64.whl.metadata (11 kB)
Collecting browserforge>=1.2.4 (from scrapling[fetchers]==0.4.3)
  Downloading browserforge-1.2.4-py3-none-any.whl.metadata (28 kB)
Collecting apify-fingerprint-datapoints>=0.11.0 (from scrapling[fetchers]==0.4.3)
  Downloading apify_fingerprint_datapoints-0.12.0-py3-none-any.whl.metadata (14 kB)
Collecting msgspec>=0.20.0 (from scrapling[fetchers]==0.4.3)
  Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: anyio>=4.12.1 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]==0.4.3) (4.13.0)
Collecting pyee<14,>=13 (from patchright==1.58.2->scrapling[fetchers]==0.4.3)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from patchright==1.58.2->scrapling[fetchers]==0.4.3) (3.3.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.12.1->scrapling[fetchers]==0.4.3) (3.11)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.14.0->scrapling[fetchers]==0.4.3) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.14.0->scrapling[fetchers]==0.4.3) (2026.2.25)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.14.0->scrapling[fetchers]==0.4.3) (3.0)
Downloading scrapling-0.4.3-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.9/119.9 kB 4.6 MB/s eta 0:00:00
Downloading patchright-1.58.2-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 19.7 MB/s eta 0:00:00
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 16.0 MB/s eta 0:00:00
Downloading apify_fingerprint_datapoints-0.12.0-py3-none-any.whl (643 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 643.8/643.8 kB 17.1 MB/s eta 0:00:00
Downloading browserforge-1.2.4-py3-none-any.whl (37 kB)
Downloading cssselect-1.4.0-py3-none-any.whl (18 kB)
Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 8.3 MB/s eta 0:00:00
Downloading tld-0.13.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 12.2 MB/s eta 0:00:00
Downloading w3lib-2.4.1-py3-none-any.whl (21 kB)
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: w3lib, tld, pyee, msgspec, cssselect, apify-fingerprint-datapoints, scrapling, playwright, patchright, browserforge
Successfully installed apify-fingerprint-datapoints-0.12.0 browserforge-1.2.4 cssselect-1.4.0 msgspec-0.20.0 patchright-1.58.2 playwright-1.58.0 pyee-13.0.1 scrapling-0.4.3 tld-0.13.2 w3lib-2.4.1
Installing Playwright browsers...
(node:5542) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:5605) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:5620) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
Installing Playwright dependencies...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [4]:
#INSTALANDO O CHROME NO AMBIENTE
!apt-get update
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update
!apt-get install -y google-chrome-stable

Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Get:1 http://dl.google.com/linux/chrome/deb stable InRelease [1,825 B]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://cli.github.com/packages stable InRelease
Get:4 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,203 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,028 B in 1s (2,052 B/s)
Reading package lists... Done
W: http://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libvulkan1 mesa-vulkan-drivers
The following NEW packages will be installed:
  google-chrome-stable libvulkan1 mesa-vulkan-drivers
0 upgraded, 3 newly installed, 0 to remove and 13 not upgraded.
Need to get 136 MB of archives.
After this operation, 465 MB of additional disk space will be used.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 147.0.7727.55-1 [125 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 23.2.1-1ubuntu3.1~22.04.3 [10.7 MB]
Fetched 136 MB in 3s (44.5 MB/s)
Selecting previously unselected package libvulkan1:amd64.
(Reading database ... 118489 files and directories currently installed.)
Preparing to unpack .../libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package google-chrome-stable.
Preparing to unpack .../google-chrome-stable_147.0.7727.55-1_amd64.deb ...
Unpacking google-chrome-stable (147.0.7727.55-1) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../mesa-vulkan-drivers_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up google-chrome-stable (147.0.7727.55-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

In [5]:
#BASE PARA MANEJAR DADOS ITP
import pandas as pd
import numpy as np
import zipfile
import re

from io import BytesIO
import os
import time
import warnings
import time

In [6]:
#SELENIUM
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.proxy import Proxy, ProxyType
from selenium.webdriver.remote.client_config import ClientConfig
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.remote.remote_connection import RemoteConnection
from selenium.common.exceptions import WebDriverException, TimeoutException, NoSuchElementException, ElementClickInterceptedException, ElementNotInteractableException
from selenium.webdriver.common.print_page_options import PrintOptions


#SELENIUM STEALTH + UC
from selenium_stealth import stealth
import undetected_chromedriver as uc

#SCRAPLING
from scrapling.fetchers import StealthyFetcher

#OUTROS
from webdriver_manager.chrome import ChromeDriverManager
from urllib3.util import Retry, Timeout
import requests
from requests.adapters import HTTPAdapter
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor, as_completed
import pypdfium2 as pdfium

##Extração e visualizações do ITP25/PR

Devido ao tamanho original do arquivo disponibilizado em https://radardatransparencia.atricon.org.br/downloads.html não era extrair de modo direto os dados do portal. Portanto foi realizado uma query filtrando os dados referentes as entidades paranaense avaliadas no ITP e criando um .zip alocado no github https://github.com/leonardosilva-sepl/Consulta_ITP24-25_PR/

In [7]:
url2025 = 'https://github.com/leonardosilva-sepl/Consulta_ITP24-25_PR/raw/refs/heads/main/itp2025_pr.zip'

In [8]:
filebytes2025 = BytesIO(requests.get(url2025).content)
zip2025 = zipfile.ZipFile(filebytes2025)
zip2025.extractall('questionario2025')

In [9]:
itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")
itp_2025_pr.head()

/tmp/ipykernel_4511/3930033236.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")

,id_avaliacao,entidade_id,entidade_nome,ibge,municipio_nome,uf,id_dimensao,dimensao_texto,id_criterio,criterio_texto,...,resposta_revisao,justificativa_avaliacao,justificativa_validacao,justificativa_revisao,link_avaliacao,link_validacao,link_revisao,imagem_avaliacao,imagem_validacao,imagem_revisao
0,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,652,1.1 Possui sítio oficial próprio na internet?,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
1,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,653,1.2 Possui portal da transparência próprio ou ...,...,NaN,NaN,NaN,NaN,https://planaltopr.equiplano.com.br:7030/trans...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
2,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,654,1.3 O acesso ao portal transparência está visí...,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
3,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,655,1.4 O site e o portal tranparência contêm fer...,...,NaN,NaN,NaN,NaN,https://planaltopr.equiplano.com.br:7030/trans...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
4,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,42,Informações Institucionais,656,2.1 Divulga a sua estrutura organizacional?,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/imprensa/institucio...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN

In [10]:
itp_2025_pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276403 entries, 0 to 276402
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_avaliacao             276403 non-null  int64
 1   entidade_id              276403 non-null  int64
 2   entidade_nome            276403 non-null  object
 3   ibge                     276403 non-null  int64
 4   municipio_nome           276403 non-null  object
 5   uf                       276403 non-null  object
 6   id_dimensao              276403 non-null  int64
 7   dimensao_texto           276403 non-null  object
 8   id_criterio              276403 non-null  int64
 9   criterio_texto           276403 non-null  object
 10  exigibilidade            276403 non-null  object
 11  item_avaliacao           276403 non-null  object
 12  resposta_avaliacao       276403 non-null  bool
 13  resposta_validacao       254041 non-null  object
 14  resposta_revisao         16728 non-null   object
 15  justificativa_avaliacao  42291 non-null   object
 16  justificativa_validacao  29766 non-null   object
 17  justificativa_revisao    2401 non-null    object
 18  link_avaliacao           130311 non-null  object
 19  link_validacao           3678 non-null    object
 20  link_revisao             457 non-null     object
 21  imagem_avaliacao         82753 non-null   object
 22  imagem_validacao         10380 non-null   object
 23  imagem_revisao           2064 non-null    object
dtypes: bool(1), int64(5), object(18)
memory usage: 48.8+ MB

In [11]:
display(itp_2025_pr.item_avaliacao.value_counts(dropna = False),itp_2025_pr.resposta_avaliacao.value_counts(dropna = False),itp_2025_pr.resposta_validacao.value_counts(dropna = False),itp_2025_pr.resposta_revisao.value_counts(dropna = False))

item_avaliacao
Disponibilidade           137285
Atualidade                 41931
Filtros de Pesquisa        37566
Série Histórica            34475
Gravação de Relatórios     25146
Name: count, dtype: int64

resposta_avaliacao
True     250151
False     26252
Name: count, dtype: int64

resposta_validacao
True     201136
False     52905
NaN       22362
Name: count, dtype: int64

resposta_revisao
NaN      259675
True      14653
False      2075
Name: count, dtype: int64

Dataframe de links respostas ENTIDADE x QUESTÃO

In [12]:
itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")
itp_2025_pr.head()

#Filtrando questões avaliadas para prefeituras
questoes_prefeituras = itp_2025_pr[itp_2025_pr['entidade_nome']== 'Prefeitura Municipal de Abatiá'][['id_criterio','criterio_texto']].drop_duplicates()
questoes_prefeituras = questoes_prefeituras.reset_index(drop= True)

#Localizando as entidades "PREFEITURA"
itp_2025_pr['entidade_nome'] = itp_2025_pr.entidade_nome.str.lower()
entidades_pr = itp_2025_pr[['entidade_id','entidade_nome']].drop_duplicates().reset_index(drop= True)
prefeituras_pr = entidades_pr[entidades_pr['entidade_nome'].str.find('prefeitura')== 0]

#DF ENTIDADE X QUESTAO
links = itp_2025_pr[['id_criterio','criterio_texto','entidade_id','link_avaliacao']]
links = links[links['link_avaliacao'].notna()]
links = links[links['entidade_id'].isin(prefeituras_pr.entidade_id)].reset_index(drop= True)
links = links.drop_duplicates()
a = prefeituras_pr['entidade_id']
for id in questoes_prefeituras.id_criterio:
  a = pd.DataFrame(a).merge(links[links['id_criterio'] == id].drop_duplicates(subset= 'entidade_id', keep='last')[['entidade_id','link_avaliacao']],
                                                        on = 'entidade_id', how='left')
  a.rename(columns = {'link_avaliacao':id}, inplace = True)
a

/tmp/ipykernel_4511/91520330.py:1: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")

,entidade_id,652,653,654,655,656,657,658,659,660,...,746,747,748,749,750,751,752,753,754,755
0,509,https://barracao.pr.gov.br/,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/\t,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/secretarias,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/,...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-saude,https://consud-portal.ids.inf.br/portalcidadao...,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-educacao,https://barracao.pr.gov.br/secretaria-educacao
1,660,https://www.bocaiuvadosul.pr.gov.br/,https://bocaiuva.eloweb.net/portaltransparenci...,https://www.bocaiuvadosul.pr.gov.br/,https://www.bocaiuvadosul.pr.gov.br/,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretarias/9,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretaria...,...,NaN,https://bocaiuva.eloweb.net/portaltransparenci...,https://bocaiuva.eloweb.net/portaltransparenci...,https://www.bocaiuvadosul.pr.gov.br/legislacao...,https://www.bocaiuvadosul.pr.gov.br/secretarias/4,NaN,NaN,https://www.bocaiuvadosul.pr.gov.br/secretarias/4,https://www.bocaiuvadosul.pr.gov.br/pagina-site/5,https://www.bocaiuvadosul.pr.gov.br/educacao
2,2972,http://www.marmeleiro.pr.gov.br/,https://marmeleiro.atende.net/?pg=transparencia,http://www.marmeleiro.pr.gov.br/,ttps://marmeleiro.atende.net/?pg=transparencia,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/gr...,http://www.marmeleiro.pr.gov.br/,...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://consud-portal.ids.inf.br/portalcidadao...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro-saudetransparente.ids.inf.b...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/it...
3,1270,http://www.cianorte.pr.gov.br/site/,https://cianorte.oxy.elotech.com.br/portaltran...,http://www.cianorte.pr.gov.br/site/,https://www.cianorte.pr.gov.br/servicos/,https://cianorte.oxy.elotech.com.br/portaltran...,https://www.cianorte.pr.gov.br/secretarias/,https://www.cianorte.pr.gov.br/secretarias/,https://www.cianorte.pr.gov.br/secretarias/,http://www.cianorte.pr.gov.br/secretarias/,...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,http://c3189prd.cloudmv.com.br/portal/agendaPr...,http://c3189prd.cloudmv.com.br/portal/listaEsp...,https://cianorte.pr.gov.br/pagina/194_RELACAO-...,https://cianorte.oxy.elotech.com.br/portaltran...,https://www.cianorte.pr.gov.br/secretaria/educ...,https://www.cianorte.pr.gov.br/pagina/83_Centr...
4,2949,https://www.marialva.pr.gov.br/,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://www.marialva.pr.gov.br/index.php?sessa...,https://www.marialva.pr.gov.br//index.php?sess...,https://www.marialva.pr.gov.br/,https://www.marialva.pr.gov.br/,...,https://www.ingadigital.com.br/transparencia/?...,NaN,NaN,https://marialva.oxy.elotech.com.br/portaltran...,https://www.marialva.pr.gov.br//index.php?sess...,NaN,https://www.ingadigital.com.br/transparencia/?...,https://www.ingadigital.com.br/transparencia/?...,NaN,https://www.ingadigital.com.br/transparencia/i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,4405,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,NaN,NaN,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/cidade/noticia/cen...
393,1554,https://www.diamantedonorte.pr.gov.br/,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://www.diamantedonorte.pr.gov.br/conteudo...,https://www.diamantedonorte.pr.gov.br/expediente,...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,NaN,NaN,https://diamantedonorte.eloweb.net/portaltrans...,NaN,NaN,NaN,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...
394,5196,https://telemacoborba.pr.gov.br/,https://telemacoborba.atende.net/transparencia/,https://telemacoborba.pr.gov.br/,https://telemacoborba.pr.gov.br/,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,...,https://telemacoborba.atende.net/transparencia...,https://telemacoborba.atende.net/transparencia...,NaN,NaN,NaN,NaN,https://telemacoborba.atende.net/transparencia...,https://telemacoborba.pr.gov.br/index.php/info...,https://telemacoborba.atende.net/transparencia...,NaN
395,3341,https://www.novalondrina.pr.gov.br/,https://novalondrina.eloweb.net/portaltranspar...,https://www.novalondrina.pr.gov.br/,https://www.novalondrina.pr.gov.br/,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,...,NaN,https://dd-publico.serpro.gov.br/extensions/pa...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,NaN,NaN,NaN,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.vagou.ngf.net.br/lista-de...
396,3380,https://www.novatebas.pr.gov.br/,https://novatebas.oxy.elotech.com.br/portaltra...,https://www.novatebas.pr.gov.br/,https://www.novatebas.pr.gov.br/,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...

In [13]:
#Detalhamento das questões
links_detalhes = itp_2025_pr[['entidade_id','id_criterio','criterio_texto','item_avaliacao','link_avaliacao','resposta_avaliacao','resposta_validacao','resposta_revisao']]
links_detalhes = links_detalhes[links_detalhes['entidade_id'].isin(prefeituras_pr.entidade_id)].reset_index(drop= True)
links_detalhes = links_detalhes.drop_duplicates()
links_detalhes

,entidade_id,id_criterio,criterio_texto,item_avaliacao,link_avaliacao,resposta_avaliacao,resposta_validacao,resposta_revisao
0,509,652,1.1 Possui sítio oficial próprio na internet?,Disponibilidade,https://barracao.pr.gov.br/,True,True,True
1,509,653,1.2 Possui portal da transparência próprio ou ...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True
2,509,654,1.3 O acesso ao portal transparência está visí...,Disponibilidade,https://barracao.pr.gov.br/\t,True,True,True
3,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://barracao.pr.gov.br/,True,True,True
4,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True
...,...,...,...,...,...,...,...,...
136943,3380,754,19.1 Divulga o plano de educação e o respectiv...,Série Histórica,NaN,True,True,NaN
136944,3380,754,19.1 Divulga o plano de educação e o respectiv...,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,True,NaN
136945,3380,754,19.1 Divulga o plano de educação e o respectiv...,Atualidade,NaN,True,True,NaN
136946,3380,755,19.2 Divulga a lista de espera em creches públ...,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,False,NaN
136947,3380,755,19.2 Divulga a lista de espera em creches públ...,Atualidade,NaN,True,False,NaN

Criando uma coluna de Resultado final, para localizar a resposta que foi utilizada para a visualização contida no site do ITP2025

In [14]:
links_detalhes['resultado_final'] = False
links_detalhes.loc[links_detalhes['resposta_validacao'] == True, 'resultado_final'] = True
links_detalhes.loc[links_detalhes['resposta_revisao'] == True, 'resultado_final'] = True
links_detalhes.loc[links_detalhes['resposta_revisao'] == False, 'resultado_final'] = False
links_detalhes.head()

,entidade_id,id_criterio,criterio_texto,item_avaliacao,link_avaliacao,resposta_avaliacao,resposta_validacao,resposta_revisao,resultado_final
0,509,652,1.1 Possui sítio oficial próprio na internet?,Disponibilidade,https://barracao.pr.gov.br/,True,True,True,True
1,509,653,1.2 Possui portal da transparência próprio ou ...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True,True
2,509,654,1.3 O acesso ao portal transparência está visí...,Disponibilidade,https://barracao.pr.gov.br/\t,True,True,True,True
3,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://barracao.pr.gov.br/,True,True,True,True
4,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True,True

In [15]:
links_detalhes.query("resposta_revisao.notna() and  resposta_revisao != resposta_validacao").value_counts("resultado_final")

resultado_final
False    544
True      42
Name: count, dtype: int64

In [16]:
links_detalhes.query('resultado_final == False and resposta_revisao == True ')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [17]:
links_detalhes.query('resultado_final == True and resposta_revisao == False')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [18]:
links_detalhes.query('resultado_final == False and resposta_validacao == True and resposta_revisao == True')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [19]:
links_detalhes.query('resultado_final == False and resposta_validacao == True and resposta_revisao.isna()')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [20]:
#visuallização das questões respondidas por prefeituras
links_detalhes[['id_criterio','criterio_texto']].drop_duplicates()

     id_criterio                                     criterio_texto
0            652      1.1 Possui sítio oficial próprio na internet?
1            653  1.2 Possui portal da transparência próprio ou ...
2            654  1.3 O acesso ao portal transparência está visí...
3            655  1.4 O site e o  portal tranparência contêm fer...
7            656        2.1 Divulga a sua estrutura organizacional?
..           ...                                                ...
298          751  18.3 Divulga a lista de espera de regulação pa...
299          752  18.4 Divulga lista dos medicamentos a serem fo...
303          753  18.5 Divulga os estoques de medicamentos das f...
306          754  19.1 Divulga o plano de educação e o respectiv...
310          755  19.2 Divulga a lista de espera em creches públ...

[91 rows x 2 columns]

Verificando possiveis erros de digitação nos links informados em uma questão de exemplo

In [21]:
teste = links_detalhes[['entidade_id',
                        'id_criterio',
                        'item_avaliacao',
                        'link_avaliacao',
                        'resultado_final']].query('item_avaliacao == "Disponibilidade"')

In [22]:
teste[teste.link_avaliacao.str.contains(",") == True]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
7927,4014,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/i...,True
8533,910,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
8534,910,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
8819,910,730,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
9806,1092,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/i...,True
...,...,...,...,...,...
126138,4445,663,Disponibilidade,http://santamariana.pr.gov.br/index.php?sessao...,True
126285,4445,698,Disponibilidade,http://177.220.171.162:7474/transparencia/cont...,True
126357,4445,731,Disponibilidade,"O portal apresenta, no topo das páginas intern...",True
135273,1784,661,Disponibilidade,"www,figueira.pr.gov.br",False
135475,1784,734,Disponibilidade,"www,figueira.pr.gov.br",False

In [23]:
teste[teste.link_avaliacao.str.contains(" ") == True]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
8,509,657,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
1005,1270,659,Disponibilidade,https://www.cianorte.pr.gov.br/secretarias/,True
1007,1270,660,Disponibilidade,http://www.cianorte.pr.gov.br/secretarias/,True
1011,1270,661,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True
1035,1270,667,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True
...,...,...,...,...,...
134335,5318,699,Disponibilidade,: https://docmunicipal.com.br/executivolicitac...,True
134371,5318,724,Disponibilidade,https://www.tuneirasdooeste.pr.gov.br/fisco,True
136010,1554,726,Disponibilidade,https://diamantedonorte.1doc.com.br/b.php?pg=...,True
136259,5196,699,Disponibilidade,https://pit.tce.pr.gov.br/Obra,True
136268,5196,700,Disponibilidade,https://pit.tce.pr.gov.br/Obra,True

In [24]:
teste[teste.link_avaliacao.str.count("https") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
1658,266,676,Disponibilidade,https://antonioolinto.eloweb.net/portahttps://...,True
5210,1754,676,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",True
5231,1754,680,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
5380,1754,743,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
...,...,...,...,...,...
123661,2737,661,Disponibilidade,https://sapl.lapa.pr.leg.br/norma/pesquisar ...,True
123678,2737,666,Disponibilidade,https://lapa.atende.net/transparencia/grupo/re...,True
123735,2737,678,Disponibilidade,https://lapa.atende.net/transparencia/item/rel...,True
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
135722,4405,707,Disponibilidade,https://santaines.eloweb.net/portaltransparenc...,False

In [25]:
teste[teste.link_avaliacao.str.count(".com") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
7,509,656,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
8,509,657,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
2228,2888,665,Disponibilidade,https://e-gov.betha.com.br/transparencia/01037...,True
2230,2888,666,Disponibilidade,https://e-gov.betha.com.br/transparencia/01037...,True
...,...,...,...,...,...
127373,4576,684,Disponibilidade,http://santoinaciopr.equiplano.com.br:7609/tra...,False
128657,3779,665,Disponibilidade,https://portal-prefeitura-pien.equiplano.cloud...,True
128904,3779,741,Disponibilidade,https://leismunicipais.com.br/a/pr/p/pien/decr...,True
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
134330,5318,697,Disponibilidade,https://tuneirasdooeste-pr.portaltp.com.br/con...,True

In [26]:
teste[teste.link_avaliacao.str.count("htt") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
1658,266,676,Disponibilidade,https://antonioolinto.eloweb.net/portahttps://...,True
5210,1754,676,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",True
5231,1754,680,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
5380,1754,743,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
...,...,...,...,...,...
123678,2737,666,Disponibilidade,https://lapa.atende.net/transparencia/grupo/re...,True
123735,2737,678,Disponibilidade,https://lapa.atende.net/transparencia/item/rel...,True
127373,4576,684,Disponibilidade,http://santoinaciopr.equiplano.com.br:7609/tra...,False
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
135722,4405,707,Disponibilidade,https://santaines.eloweb.net/portaltransparenc...,False

In [27]:
teste[teste.link_avaliacao.str.contains("http") == False]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
596,2972,655,Disponibilidade,ttps://marmeleiro.atende.net/?pg=transparencia,True
2792,5470,656,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/ANEXO%...,True
2795,5470,657,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/Lei%20...,False
2863,5470,674,Disponibilidade,file:///C:/Users/Usuário/Downloads/Termo de co...,False
2864,5470,674,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/Termo%...,False
...,...,...,...,...,...
135474,1784,733,Disponibilidade,www.figueira.pr.gov.br,False
135475,1784,734,Disponibilidade,"www,figueira.pr.gov.br",False
135480,1784,739,Disponibilidade,www.figueira.pr.gov.br,False
135503,1784,747,Disponibilidade,www.figueira.pr.gov.br,False
135509,1784,748,Disponibilidade,www.figueira.pr.gov.br,False

## FUNÇÕES DE WEB SCRAPING

###Outras

In [28]:
def scrape_url(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    try:
        if pd.isna(url) or url == '':
            print("Erro: URL vazia ou não localizada para raspagem.")
            return False, "URL_EMPTY", "URL vazia ou não localizada para raspagem."
        else:
            response = requests.get(url, headers=headers, timeout=20)
            time.sleep(10)
            response.raise_for_status()
            time.sleep(10)
            soup = BeautifulSoup(response.content, 'html.parser')
            return soup, False, False

    except requests.exceptions.HTTPError as http_err:
        error_msg = f"HTTP error occurred for {url}: {http_err}"
        print(error_msg)
        error_cod = http_err.response.status_code
        error_msg = http_err.response.reason
        return False, error_cod, error_msg

    except requests.exceptions.ConnectionError as conn_err:
        error_msg = f"Connection error occurred for {url}: {conn_err}"
        print(error_msg)
        error_cod = type(conn_err).__name__
        error_msg = "ConnectionError"
        return False, error_cod, error_msg

    except requests.exceptions.Timeout as timeout_err:
        error_msg = f"Connection error occurred for {url}: {timeout_err}"
        print(error_msg)
        error_cod = type(timeout_err).__name__
        error_msg = "timeout_err"
        return False, error_cod, error_msg

    except requests.exceptions.RequestException as req_err:
        error_msg = f"An unexpected request error occurred for {url}: {req_err}"
        print(error_msg)
        error_cod = type(req_err).__name__
        error_msg = "req_err"
        return False, error_cod, error_msg

    except Exception as e:
        error_msg = f"An unexpected error occurred for {url}: {e}"
        print(error_msg)
        error_cod = e.response.status_code if hasattr(e, 'response') and hasattr(e.response, 'status_code') else type(e).__name__
        error_msg = e.response.reason if hasattr(e, 'response') and hasattr(e.response, 'reason') else str(e)
        return False, error_cod, error_msg

In [29]:
def abrir_driver_stealth():
  options = uc.ChromeOptions()
  options.add_argument("--window-size=1550,1000")
  options.add_argument("--disable-extensions")
  options.add_argument("--disable-application-cache")
  options.add_argument("--disable-gpu")
  options.add_argument("--no-sandbox")
  options.add_argument("--disable-setuid-sandbox")
  options.add_argument("--disable-dev-shm-usage")


  driver = uc.Chrome(options=options, headless=True, version_main=145)

  stealth(
      driver,
      languages=["en-US", "en"],
      vendor="Google Inc.",
      platform="Win32",
      webgl_vendor="Intel Inc.",
      renderer="Intel Iris OpenGL Engine",
      fix_hairline=True,
  )
  return driver

In [30]:
def scrape_info_stealth(driver, url):
    if not url:
        print("Erro: URL vazia ou não localizada para raspagem.")
        return False, "URL_EMPTY", "URL vazia ou não localizada para raspagem."

    try:
        driver.get(url)
        driver.implicitly_wait(20)
        response_text = driver.page_source
        soup = BeautifulSoup(response_text, "html.parser")
        return soup, False, False

    except Exception as e:
        err = f"Erro ao raspar {url}: {e}"
        print(err)
        return False, type(e).__name__, str(e)

In [31]:
def q_scraper(questao):
  q = questao
  qhtml= links_detalhes[['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']].iloc[1005:1011,:].query('id_criterio == @q and item_avaliacao =="Disponibilidade"').drop_duplicates(subset='entidade_id', keep = 'first')
  results = qhtml['link_avaliacao'].apply(scrape_url)
  extracted_data = results.apply(pd.Series)
  qhtml['pagina_scraped'] = extracted_data[0]
  qhtml['error_cod'] = extracted_data[1]
  qhtml['error_msg'] = extracted_data[2]
  return qhtml

In [32]:
def q_stealth(questao):
  q = questao
  qhtml= links_detalhes[['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']].query('id_criterio == @q and item_avaliacao =="Disponibilidade"').drop_duplicates(subset='entidade_id', keep = 'first')
  driver = abrir_driver_stealth()
  results = qhtml['link_avaliacao'].apply(lambda url: scrape_info_stealth(driver, url))
  qhtml['pagina_scraped'] = results.apply(lambda x: x[0])
  qhtml['error_cod'] = results.apply(lambda x: x[1])
  qhtml['error_msg'] = results.apply(lambda x: x[2])
  driver.quit()

  return qhtml

###Auxiliar

In [33]:
def padroniza_parametro(parametro):
    list_paramento = []

    for p in parametro:
        p = p.lower()
        list_paramento.append(p)

        p = p.upper()
        list_paramento.append(p)

        p = p.capitalize()
        list_paramento.append(p)

    return list_paramento

In [34]:
def verifica_lista(lista, parametro):
  lista_verificada = []
  if lista is not None:
    for el in lista:
      for p in parametro:
        if p in el:
          lista_verificada.append([el, True])


  return lista_verificada

In [35]:
### verifica se rede social esta online // tiktok ok, youtube ok, face/x/insta off


def url_online(url: str, timeout: int = 5) -> bool:
    HEADERS = {
              "User-Agent": (
                  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/122.0 Safari/537.36"
              )
          }

    try:
        # HEAD é mais leve; se o servidor não suportar, cai para GET
        resp = requests.head(
            url,
            headers=HEADERS,
            allow_redirects=True,
            timeout=timeout
        )
        if resp.status_code in (301, 302, 303, 307, 308):
            # já fizemos allow_redirects=True, então nesta altura
            # normalmente já estamos no destino final
            pass

        if resp.status_code in (403, 405):  # alguns bloqueiam HEAD
            resp = requests.get(
                url,
                headers=HEADERS,
                allow_redirects=True,
                timeout=timeout
            )

        return resp.status_code == 200
    except requests.exceptions.RequestException as e:
        print(f"Error checking if URL {url} is online: {e}") # Modified this line
        return False

def checker(urls):
    results = []

    for u in urls:
        data_result = {"url": u, "titulo": None, "nickname": None, "error_code": None}

        try:
            # Verificação inicial online
            if not url_online(u):
                data_result["error_code"] = "OFFLINE"
                results.append(data_result)
                continue

            r = requests.get(url=u, timeout=5, headers=HEADERS)
            data_result["error_code"] = r.status_code
            r.raise_for_status()

            soup = BeautifulSoup(r.text, "html.parser")
            data_result["titulo"] = soup.title.string.strip() if soup.title else "Sem título"

            data_result["html"]  = soup

            # Extração de Nickname (específico para TikTok)
            script_tag = soup.find("script", id="__UNIVERSAL_DATA_FOR_REHYDRATION__")
            if script_tag:
                data = json.loads(script_tag.string)
                user_info = data.get("__DEFAULT_SCOPE__", {}).get("webapp.user-detail", {}).get("userInfo", {})
                data_result["nickname"] = user_info.get("user", {}).get("uniqueId")

        except requests.exceptions.HTTPError as e:
            data_result["error_code"] = r.status_code
        except requests.exceptions.RequestException:
            data_result["error_code"] = "CONN_ERR"
        except Exception:
            data_result["error_code"] = "UNKNOWN_ERR"

        results.append(data_result)

    return results

In [36]:
def localiza_pai(element):
    try:
        return element.find_element(By.XPATH, "./..")
    except Exception as e:
        print(f"Erro ao localizar elemento pai: {e}")
        return None

In [37]:
def pontuador(lista_elementos, parametros_verificacao):
  elementos_pontuados = []
  pontos = 0
  for el in lista_elementos:
    if el is not None:
      try:
        h = el.get_attribute("outerHTML")
        t = el.text
        for p in parametros_verificacao:
          if p in t:
            pontos += 1

        elementos_pontuados.append([el, pontos, h])
        pontos = 0


      except Exception as e:
        print(f"Erro ao obter atributos do elemento: {e}")
        pass
  elementos_pontuados = sorted(elementos_pontuados, key=lambda x: x[1], reverse=True)
  return elementos_pontuados

In [38]:
js_sibling = """var elem = arguments[0];
                var sibs = [];
                if (elem.parentNode) {
                    elem = elem.parentNode.firstChild;
                    do {
                        if (elem.nodeType === 1) { // Only include element nodes
                            sibs.push(elem);
                        }
                    } while (elem = elem.nextSibling)
                }
                return sibs;
                """

In [39]:
def localiza_irmaos(elemento):
  return elemento.find_elements(By.XPATH, "./following-sibling::*")

In [40]:
def bt_aceito(driver):
  bt = ["Aceito","Aceitar","Concordo"]
  for b in bt:
    ac = driver.find_elements(By.XPATH, f"//*[contains(text(),'{b}')]")
    for a in ac:
      try:
        clicker(driver, a)
      except:
        pass

###Principal

In [41]:
def abrir_driver():

  # Configuracao de opcoes
  options = Options()
  options.accept_insecure_certs = True
  options.add_argument("--headless=new")
  options.add_argument("--window-size=1920,1080")
  options.add_argument("--no-sandbox")
  options.add_argument("--disable-dev-shm-usage")
  options.add_argument("--disable-gpu")
  driver = webdriver.Chrome(options=options)

  # Configuracao de cliente
  retries = Retry(total=1, connect=1, read=1, backoff_factor=0.5)
  driver.command_executor._conn.connection_pool_kw['retries'] = retries
  driver.set_page_load_timeout(90)
  driver.get('chrome://settings/')
  driver.execute_script("chrome.settingsPrivate.setDefaultZoom(0.50);")

  return driver

In [42]:
def busca_todo_atributos(driver, element):
    #Retorna um dict com os atributos de cada elemento {nome_atributo: valor}
    js = """
        var items = {};
        for (var i = 0; i < arguments[0].attributes.length; i++) {
            items[arguments[0].attributes[i].name] = arguments[0].attributes[i].value;
        }
        return items;
    """
    return driver.execute_script(js, element)

In [43]:
def localiza_clicks(driver, parametro_navegacao):
    # LOCALIZA SE HÁ ELEMENTOS COM TEXTOS SELECIONADOS
    lista_elementos = []
    vistos = set()

    for p in parametro_navegacao:
      try:
        els_texto = driver.find_elements(By.XPATH, f"//*[contains(text(),'{p}')]") #BUSCA ELEMENTOS QUE TENHAM TEXTO P
        if not els_texto:
          els_texto = []
      except Exception:
        els_texto = []
        continue

      try:
        els_atribs = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]") #BUSCA ELEMENTOS QUE TENHAM ATRIBUTO P
        if not els_atribs:
          els_atribs = []
      except Exception:
        els_atribs = []
        continue

      els = els_texto + els_atribs
      for el in els:
        try:
          txt = el.text
          html = el.get_attribute("outerHTML")
          id = (txt, html)

          if id not in vistos and el not in lista_elementos:
            lista_elementos.append(el)
            vistos.add(id)
        except:
            continue

    return lista_elementos

In [44]:
def clicker(driver, el):
    try:
        main_window = driver.current_window_handle
        el.click()
        time.sleep(2)

        if len(driver.window_handles) > 1:
            for handle in driver.window_handles:
                if handle != main_window:
                    driver.switch_to.window(handle)
                    break

    except (ElementClickInterceptedException, ElementNotInteractableException):
        driver.execute_script('arguments[0].click();', el)
        time.sleep(2)
        if len(driver.window_handles) > 1:
            for handle in driver.window_handles:
                if handle != driver.current_window_handle:
                    driver.switch_to.window(handle)
                    break

In [45]:
#retorna todo texto para os elementos desejados
def busca_todo_texto(driver, local):
    #LOCALIZACAO
    elements = driver.find_elements(By.CSS_SELECTOR, local)

    #lista de texto
    lista_text = []
    lista_html = []
    for e in elements:
      try:
        if e.text is not None:
          lista_text.append(e.text)
          lista_html.append(e.get_attribute("outerHTML"))

      except Exception as e:
        print(f"Erro ao obter atributos do elemento: {e}")
        pass

    lista_text = list(set(lista_text))
    lista_html = list(set(lista_html))
    return lista_text, lista_html

In [46]:
#retorna todo texto para os elementos desejados
def busca_texto(driver, parametros_verificacao):
  parametros_verificacao = list(set([p.lower() for p in parametros_verificacao]))
  #LOCALIZACAO
  trechos = []
  texto = driver.find_element(By.TAG_NAME,"*").text
  texto.lower()

  for p in parametros_verificacao:
    if p in texto:
      pos = texto.find(p)
      trecho = texto[pos:pos+len(p)+20]
      trechos.append(trecho)

  return trechos, None, None

funcao de arquivo

In [47]:
def abrir_arquivo(driver,paramento_navegacao):
  try:
    tipo_arq = [".pdf",".doc",".xsls"]
    els = localiza_clicks(driver, parametro_navegacao)

    for el in els:
      for p in paramento_navegacao:
        if el.find_element(By.PARTIAL_LINK_TEXT, p):
          if el.find_element(By.XPATH, f".//[@*[contains(.,'.pdf')]]"):









      #verificar se elementos filhos possuem arquivo
      #se possuir atrib .pdf e texto contendo pn,

  except:

  return

IndentationError: expected an indented block after 'if' statement on line 9 (3439572049.py, line 22)

In [ ]:
url = "https://www.portalcr2.com.br/estrutura-organizacional/estrutura-congonhinhas"
driver = abrir_driver()
driver.get(url)

In [ ]:
p = "Organograma"
els = driver.find_elements(By.XPATH, f"//*[contains(text(),'{p}')]")
els_a = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]")
els = els + els_a

In [ ]:
els

[<selenium.webdriver.remote.webelement.WebElement (session="9b55e4e25b5a66dcfa3f6a82837e31d1", element="f.058556E49ADAF6059F2159CB58BE048C.d.E6C81FD4D9B43F00F6FAF296DDE4846D.e.56")>,
 <selenium.webdriver.remote.webelement.WebElement (session="9b55e4e25b5a66dcfa3f6a82837e31d1", element="f.058556E49ADAF6059F2159CB58BE048C.d.E6C81FD4D9B43F00F6FAF296DDE4846D.e.57")>]

In [ ]:
els[0].get_attribute("outerHTML")

'<div>Organograma</div>'

In [ ]:
els[1].get_attribute("outerHTML")

'<div class="bubble-element Text baUbaIaM2 clickable-element bubble-r-vertical-center" title="Organograma.png" style="white-space: pre-wrap; overflow: visible; line-height: 1; border-radius: 0px; opacity: 1; cursor: pointer; align-self: center; min-width: 360px; max-width: 360px; order: 6; min-height: 30px; width: 360px; flex-grow: 1; height: max-content; margin: 0px; font-family: var(--font_default); font-size: 24px; font-weight: 400; color: rgb(3, 147, 215); text-align: center;"><div><div class="fa fa-download"></div></div></div>'

In [ ]:
clicker(driver, els[1])

In [ ]:
driver.current_url

'https://4fdfdc7ecc7eac3fcdc8af2e4ed6ae07.cdn.bubble.io/f1738948376696x460167447951656000/Organograma.png'

In [ ]:
driver.save_screenshot("screenshot.png")

True

In [ ]:
el = els[0]
t = ".pdf"
t in el.get_attribute("outerHTML")

IndexError: list index out of range

In [ ]:
ep = localiza_pai(localiza_pai(localiza_pai(localiza_pai(localiza_pai(els[0])))))

In [ ]:
ep.get_attribute("outerHTML")

'<div class="btn-group">\n                        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">\n                            <span class="glyphicon glyphicon-list-alt"></span> Opções\n                            <span class="caret"></span>\n                        </a>\n                        <ul class="dropdown-menu multi-level" style="text-align:left;">\n                                                            <li>\n                                    <a href="/upload/tuneiras-do-oeste/leiordinarias/2076/LEI_035_2009_original.pdf" download="LEI_035_2009.pdf" title="Download PDF"><i class="fa fa-download" aria-hidden="true"></i> PDF</a>                                </li>\n                                                                                            <li class="dropdown-submenu">\n                                    <a href="#"><span class="fa fa-paperclip"></span> Anexos</a>\n                                    <ul class="dropdown-menu">\n                                                                                    <li>\n                                                <a href="/upload/tuneiras-do-oeste/anexos/12048/ORGANOAGRAMA_2009_original.pdf" download="ORGANOAGRAMA_2009.pdf">ORGANOGRAMA</a>                                            </li>\n                                                                            </ul>\n                                </li>\n                                                                                </ul>\n                    </div>'

In [ ]:
ep.is_displayed()

True

In [ ]:
clicker(driver, ep)

In [ ]:
clicker(driver, localiza_pai(els[0]))

In [ ]:
driver.current_url

'https://docmunicipal.com.br/tuneiras-do-oeste/executivoorganogramas'

In [ ]:
driver.window_handles

['D9E41E5F5A1EB959BF17947F85B35A42']

In [ ]:
driver.save_screenshot("screenshot.png")

True

In [ ]:
pdf = [el.get_attribute("href") for el in els][0]

In [ ]:
def pdf_to_text(url):
  urlc = BytesIO(requests.get(url).content)
  textos_corpo = "\n".join(
      p.get_textpage().get_text_range()
      for p in pdfium.PdfDocument(urlc)
  )
  return texto

In [ ]:
def verifica_guia(driver,url_inicial):
  if (driver.current_url != url_inicial) and (driver.window_handles == 1):
    link_arq = driver.current_url

  if (driver.current_url == url_inicial) and ( driver.window_handles > 1):
    driver.switch_to.window(driver.window_handles[1])
    time.sleep(2)
    link_arq = driver.current_url

  return link_arq

In [ ]:
driver.close()

In [ ]:
pn = ["ORGANOGRAMA"]
tipo_arq = [".pdf",".doc",".xsls"]

for p in pn:
  els = []
  els_t = []
  els_a = []
  try:
    els_t = driver.find_elements(By.XPATH, f"//*[contains(text(),'{p}')]") #busca de textos de elementos contedo p
  except:
    pass
  try:
    els_a = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]") #busca de atributos de elementos contedo p
  except:
    pass

  els = els_t + els_a

  if els:
    for el in els:
      for t in tipo_arq:
        if t in el.get_attribute("outerHTML"):
          try:
            link_arq = el.get_attribute("href")
          except:
            el_i = el
            while not el_i.is_displayed():
              el_i = localiza_pai(el_i)

            clicker(driver, el_i)
            time.sleep(2)

            link_arq = verifica_guia(driver, url_inicial)

            else:
              clicker(driver, el)
              time.sleep(2)
              link_arq = verifica_guia(driver, url_inicial)
        except:
          pass

In [ ]:
def verifica_texto(driver, texto):
  return

In [48]:
#retorna link para uma parte de texto do link desejado
def busca_link(driver, parametro):
    #FUNCAO DE LOCALIZACAO
    #driver: driver seleneium ativo
    #parametro: lista de parametro string dos atributos que serão buscados, ex.: "radar", "horario"

    lista_elementos = [] #elementos que contenham algum p
    lista = []
    link = []
    html = []

    for p in parametro:
      elementos = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]") #PARAMETRO DE BUSCA EM ATRIBUTOS

      if elementos is not None:
        lista_elementos.extend(elementos)

    for el in lista_elementos:
      if el.tag_name != 'input' and el.tag_name != 'option' and el.tag_name != 'form' and el.tag_name != "select" and el.get_attribute("option") == None:
        try:
          atribs = busca_todo_atributos(driver,el)

          for nome_atributo, valor_atributo in atribs.items():
            if (nome_atributo is not None) and (valor_atributo is not None) and any(p in valor_atributo for p in parametro):
              link.append(el.get_attribute(nome_atributo))
              html.append(el.get_attribute("outerHTML"))
              lista.append(el)

        except Exception as e:
          print(f"Erro ao obter atributos do elemento: {e}")

    lista = list(set(lista))
    link = list(set(link))
    html = list(set(html))

    return link, html, lista

In [49]:
def buscador(driver, tipo_busca, busca):
    match tipo_busca:
      case "texto":
            elemento, html_elemento = busca_todo_texto(driver, busca)

      case "link":
            elemento, html_elemento, lista = busca_link(driver, busca)

      case "texto_simples":
            elemento, html_elemento, lista = busca_texto(driver, busca)

    return elemento, html_elemento, lista

In [50]:
def filtro_questao(questao, i=None, k= None, df = None):
  qhtml = df[
           ['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']
           ].query(
                  'id_criterio == @questao and item_avaliacao == "Disponibilidade"'
                  ).drop_duplicates(
                                    subset='entidade_id', keep='first'
                                    ).reset_index(drop=True).iloc[i:k, :].reset_index(drop=True) #iloc somente para verificação por partes
  return qhtml

In [51]:
def verifica_bloqueio(driver):

  frases_bloqueio = ["Performing security verification", "Sorry, you have been blocked","403 Forbidden",
                    "A página solicitada não foi encontrada no servidor.","The request could not be satisfied.",
                    "Desculpe, não conseguimos encontrar o que você está procurando.",
                    "This page is used to test the proper operation ","ERRO 500","Bad Gateway",
                    "Blocked request this country"
                   ]

  texto = driver.find_element(By.TAG_NAME,"*").text

  # Verifica se alguma frase f de frases_bloqueio é uma substring de qualquer texto t em textos_corpo
  bloqueio = any(f.strip() in texto.strip() for f in frases_bloqueio)

  return bloqueio

In [52]:
def bt_mais(driver):
  mais_infos = ["Detalhes","Mais"]
  try:
    bt = localiza_clicks(driver, mais_isfos)
  except Exception as e:
    print(e)
    pass

In [53]:
'''#recorrencia
url_inicial = driver.current_url
url_click = driver.current_url


eh_recorrencia = False #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
  #fluxo normal


eh_recorrencia = True

if url_inicial == url_click
elementos_paginas = []
  #fluxo normal
  #tenta raspar todo elemento contento paramento
  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao

if url_inicial != url_click:
  #fluxo com reacessos a pagina inicial
  #tenta raspar todo elemento contento paramento
  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao, geralmente em elementos js

  while url_inicial != url_click #volta a pagina hub
    url_click = driver.current_url
    driver.back()
    time.sleep(2)'''

'#recorrencia\nurl_inicial = driver.current_url\nurl_click = driver.current_url\n\n\neh_recorrencia = False #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS\n  #fluxo normal\n\n\neh_recorrencia = True\n\nif url_inicial == url_click\nelementos_paginas = []\n  #fluxo normal\n  #tenta raspar todo elemento contento paramento\n  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao\n\nif url_inicial != url_click:\n  #fluxo com reacessos a pagina inicial\n  #tenta raspar todo elemento contento paramento\n  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao, geralmente em elementos js\n\n  while url_inicial != url_click #volta a pagina hub\n    url_click = driver.current_url\n    driver.back()\n    time.sleep(2)'

In [54]:
'''##BUSCA SE NÃO HOUVER ELEMENTO CONTENDO PARAMENTRO DE VERIFICACAO
if not elemento:
  try:
    bt_aceito(driver) ##ACEITAR TERMOS DE USO
    lista_elementos = localiza_clicks(driver, parametro_navegacao)
  except Exception as e:
    print(e)
    pass


    ##TENTA NAVEGAR A PARTIR DOS CLICKAVEIS LOCALIZADOS
    if lista_elementos:
      for el in lista_elementos:
        try:
          texto_click.append(el.text)
          html_click.append(el.get_attribute("outerHTML"))

          clicker(driver,el)
          url_click = driver.current_url

          elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)

          ## RETORNAR A PAGINA INICIAL
          if not lista_elementos and url_click == url_inicial:
            pass

          if not lista_elementos and url_click != url_inicial:
            driver.get(url)
            pass

          if lista_elementos:
            elemento = elemento
            html_elemento = html_elemento
            break
          ## RETORNAR A PAGINA INICIAL

        except:
          continue'''

'##BUSCA SE NÃO HOUVER ELEMENTO CONTENDO PARAMENTRO DE VERIFICACAO\nif not elemento:\n  try:\n    bt_aceito(driver) ##ACEITAR TERMOS DE USO\n    lista_elementos = localiza_clicks(driver, parametro_navegacao)\n  except Exception as e:\n    print(e)\n    pass\n\n\n    ##TENTA NAVEGAR A PARTIR DOS CLICKAVEIS LOCALIZADOS\n    if lista_elementos:\n      for el in lista_elementos:\n        try:\n          texto_click.append(el.text)\n          html_click.append(el.get_attribute("outerHTML"))\n\n          clicker(driver,el)\n          url_click = driver.current_url\n\n          elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)\n\n          ## RETORNAR A PAGINA INICIAL\n          if not lista_elementos and url_click == url_inicial:\n            pass\n\n          if not lista_elementos and url_click != url_inicial:\n            driver.get(url)\n            pass\n\n          if lista_elementos:\n            elemento = elemento\n            html_elemento = html_elemento\n            break\n          ## RETORNAR A PAGINA INICIAL\n\n        except:\n          continue'

In [55]:
def scrap_selenium(url, tipo_busca, busca, parametro_navegacao):

  inicio = time.time()
  parametro_navegacao = padroniza_parametro(parametro_navegacao)
  html_selenium = None
  elemento = None
  html_elemento = None
  error_cod = False
  error_msg = False
  texto_click = []
  html_click = []
  elemento_f = None
  html_elemento_f = None
  duracao = 0

  if pd.isna(url) or (isinstance(url, str) and not url.strip()):
    print(f"Erro: URL inválida recebida: {repr(url)}")
    return None, None, None, "URL_INVALID", "URL vazia, None ou NaN.", None, None, None

  if ("https://radardatransparencia.atricon" in url) or ("https://radar.tce.mt." in url) or ("https://www.tce." in url):
    return None, None, None, "URL_VERIFY", "Foi verificado que a URL fornecida se refere diretamente ao Radar Transparencia ou TCE-MT", None, None, None

  driver = None

  try:
    driver = abrir_driver()
    driver.set_page_load_timeout(500)
    driver.set_script_timeout(500)
    driver.get(url)
    wait = WebDriverWait(driver, 60)

    try: ##Parâmetros HTML para busca inicial
        wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
        html_selenium = driver.page_source

    except TimeoutException as e:
        html_selenium = driver.page_source
        error_cod = type(e).__name__
        error_msg = str(e)
        print(f"Timeout esperando carregamento principal para {url}, seguindo mesmo assim.")

    try:
        if verifica_bloqueio(driver):
          error_cod = "URL_BLOCKED"
          error_msg = "URL bloqueada"

        else:
          url_inicial = driver.current_url
          driver.implicitly_wait(10)
          elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca) ##BUSCA DUPLICADA DEVIDO A ERROS DE ASINC
          elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)


          ##BUSCA SE NÃO HOUVER ELEMENTO CONTENDO PARAMENTRO DE VERIFICACAO
          if not elemento:
            try:

              bt_aceito(driver) ##ACEITAR TERMOS DE USO QUE POSSA BLOQUEAR A TELA DO DRIVER
              lista_elementos = localiza_clicks(driver, parametro_navegacao)

              ##TENTA NAVEGAR A PARTIR DOS CLICKAVEIS LOCALIZADOS
              if lista_elementos:
                for el in lista_elementos:
                  try:
                    texto_click.append(el.text)
                    html_click.append(el.get_attribute("outerHTML"))
                    guia_original = driver.current_window_handle

                    clicker(driver,el)
                    url_click = driver.current_url

                    if driver.windowns_handles > 1 and driver.current_window_handle == guia_original:
                      driver.switch_to.window(driver.windowns_handles[1])

                    elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)

                    ## RETORNAR A PAGINA INICIAL
                    if not lista_elementos and url_click == url_inicial:
                      pass

                    if not lista_elementos and url_click != url_inicial:
                      if driver.windowns_handles > 1 and driver.current_window_handle != guia_original:
                        driver.close()
                        driver.switch_to.window(guia_original)
                      else:
                        driver.get(url)
                      pass

                    if lista_elementos:
                      elemento = elemento
                      html_elemento = html_elemento
                      break
                    ## RETORNAR A PAGINA INICIAL

                  except:
                    continue


              if not lista_elementos:
                error_cod = "NENHUM_ELEMENTO_NAVEGACAO"
                error_msg = f"Nenhum elemento de interação contendo: {parametro_navegacao}"

            except NoSuchElementException as e:
                error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
                error_msg = f"Nenhum elemento final localizado na página contendo: {busca} ou de interação contendo: {parametro_navegacao}"

    except Exception as e:
        if not error_cod:
            error_cod = type(e).__name__
            error_msg = str(e)
        print(f"Erro na busca de elementos para {url}: {e}")

  except WebDriverException as e:
      error_cod = type(e).__name__
      error_msg = str(e)
      print(f"WebDriver error for {url}: {error_msg}")

  except Exception as e:
      error_cod = type(e).__name__
      error_msg = str(e)
      print(f"General error for {url}: {error_msg}")

  finally:
    if (not html_elemento) and (not error_cod):
      error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
      error_msg = f"Nenhum elemento final localizado na página contendo: {busca} ou de interação contendo: {parametro_navegacao}"

    duracao = round(time.time() - inicio, 2)

    if driver:
      print(f"Tempo de execução para {url}: {duracao}s")
      driver.quit()

  return html_selenium, elemento, html_elemento, error_cod, error_msg, texto_click, html_click, duracao

In [56]:
def scrap_retry(url, tipo_busca, busca, parametro_navegacao):
    inicio = time.time()
    parametro_navegacao = padroniza_parametro(parametro_navegacao)
    html_selenium, elemento, html_elemento = None, None, None
    error_cod, error_msg = False, False
    texto_click, html_click = [], []

    if pd.isna(url) or (isinstance(url, str) and not url.strip()):
        return None, None, None, "URL_INVALID", "URL vazia.", None, None, 0

    driver = None
    try:
        # Adicionando jitter aleatório antes de iniciar o driver
        time.sleep(np.random.uniform(2, 5))

        driver = abrir_driver()
        # Timeouts estendidos para servidores municipais lentos
        driver.set_page_load_timeout(240)
        driver.set_script_timeout(240)

        driver.get(url)
        wait = WebDriverWait(driver, 100)

        try:
            wait.until(EC.presence_of_element_located((By.TAG_NAME, "body")))
            html_selenium = driver.page_source
        except TimeoutException:
            html_selenium = driver.page_source
            error_cod = "TimeoutException"
            error_msg = "Timeout persistente no reprocessamento"

        if not error_cod:
            if verifica_bloqueio(driver):
                error_cod = "URL_BLOCKED"
            else:
                elemento, html_elemento, _ = buscador(driver, tipo_busca, busca)

                if not elemento:
                    bt_aceito(driver)
                    lista_interaction = localiza_clicks(driver, parametro_navegacao)
                    for el in lista_interaction:
                        try:
                            clicker(driver, el)
                            elemento, html_elemento, _ = buscador(driver, tipo_busca, busca)
                            if elemento: break
                        except: continue

    except Exception as e:
        error_cod = type(e).__name__
        error_msg = str(e)
    finally:
        duracao = round(time.time() - inicio, 2)
        if driver: driver.quit()

    return html_selenium, elemento, html_elemento, error_cod, error_msg, texto_click, html_click, duracao

In [57]:
def q_selenium_retry(df_to_retry, questao, tipo_busca, pv, pn, threads=4):
    urls = df_to_retry['link_avaliacao'].tolist()
    results = [None] * len(urls)

    with ThreadPoolExecutor(max_workers=threads) as executor:
        future_to_index = {executor.submit(scrap_retry, url, tipo_busca, pv, pn): idx for idx, url in enumerate(urls)}

        for future in as_completed(future_to_index):
            idx = future_to_index[future]
            try:
                results[idx] = future.result()
                print(f"Retry Progress: {idx + 1}/{len(urls)}")
            except Exception as exc:
                results[idx] = (None, None, None, "RETRY_THREAD_ERROR", str(exc), [], [], 0)

    res_df = pd.DataFrame(results, columns=['pagina_scraped', 'elemento_final', 'html_elemento_final', 'error_cod', 'error_msg', 'elemento_interacao_1', 'html_elemento_interacao_1', 'duracao_segundos'])
    return pd.concat([df_to_retry.reset_index(drop=True), res_df], axis=1)

In [58]:
def q_selenium_paralelo(questao, tipo_busca, parametro_verificacao, parametro_navegacao, df=None, i=0, k=None, threads=4):
    # 1. Filtra os dados necessários
    qhtml = filtro_questao(questao, i, k, df)
    urls = qhtml['link_avaliacao'].tolist()

    # 2. Execução paralela
    results = [None] * len(urls)

    with ThreadPoolExecutor(max_workers=threads) as executor:
        # Mapeia a execução (scrap_selenium deve estar definida conforme as células anteriores)
        future_to_index = {executor.submit(scrap_selenium, url, tipo_busca, parametro_verificacao,parametro_navegacao ): idx for idx, url in enumerate(urls)}

        for future in as_completed(future_to_index):
            idx = future_to_index[future]
            try:
                data = future.result()
                results[idx] = data
                if (idx + 1) % 10 == 0:
                    print(f"Progresso: {idx + 1}/{len(urls)}")
            except Exception as exc:
                print(f"URL {urls[idx]} gerou uma exceção: {exc}")
                results[idx] = (None, None, None, "THREAD_ERROR", str(exc), [], [], 0)

    # 3. Organização dos resultados no DataFrame
    res_df = pd.DataFrame(results, columns=[
        'pagina_scraped', 'elemento_final', 'html_elemento_final',
        'error_cod', 'error_msg', 'elemento_interacao_1',
        'html_elemento_interacao_1', 'duracao_segundos'
    ])

    final_df = pd.concat([qhtml, res_df], axis=1)
    return final_df

In [59]:
def q_selenium(questao, tipo_busca, parametro_verificacao, parametro_navegacao, df, i=0, k=None):

##Selecionando do DF a questão desejada

  qhtml = filtro_questao(questao, i, k, df)


##Iniciando o driver e aplicando o scraper por url

  results = []
  for idx, url in enumerate(qhtml['link_avaliacao'], start=1):
      results.append(scrap_selenium(url, tipo_busca, parametro_verificacao, parametro_navegacao)) #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
      if idx % 10 == 0:
          print(idx)


##Adicionando os resultados no DF
  results = pd.Series(results)
  qhtml['pagina_scraped'] = results.apply(lambda x: x[0])
  qhtml['elemento_final']        = results.apply(lambda x: x[1])
  qhtml['html_elemento_final']   = results.apply(lambda x: x[2])
  qhtml['error_cod']       = results.apply(lambda x: x[3])
  qhtml['error_msg']       = results.apply(lambda x: x[4])
  qhtml['elemento_interacao_1']       = results.apply(lambda x: x[5])
  qhtml['html_elemento_interacao_1']       = results.apply(lambda x: x[6])
  qhtml['duracao_segundos'] = results.apply(lambda x: x[7])

  return qhtml

##TESTES

###UNITARIO

https://saojosedaboavista.pr.gov.br/  verificar elemento radar não acessável

In [ ]:
'''from base64 import urlsafe_b64decode, urlsafe_b64encode


from selenium.webdriver.common.virtual_authenticator import (
    Credential,
    VirtualAuthenticatorOptions,
)'''

In [ ]:
'''BASE64_ENCODED_PK = """
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDbBOu5Lhs4vpowbCnmCyLUpIE7JM9sm9QXzye2G+jr+Kr
MsinWohEce47BFPJlTaDzHSvOW2eeunBO89ZcvvVc8RLz4qyQ8rO98xS1jtgqi1NcBPETDrtzthODu/gd0sjB2Tk3TLuBGV
oPXt54a+Oo4JbBJ6h3s0+5eAfGplCbSNq6hN3Jh9YOTw5ZA6GCEy5l8zBaOgjXytd2v2OdSVoEDNiNQRkjJd2rmS2oi9AyQ
FR3B7BrPSiDlCcITZFOWgLF5C31Wp/PSHwQhlnh7/6YhnE2y9tzsUvzx0wJXrBADW13+oMxrneDK3WGbxTNYgIi1PvSqXlq
GjHtCK+R2QkXAgMBAAECggEAVc6bu7VAnP6v0gDOeX4razv4FX/adCao9ZsHZ+WPX8PQxtmWYqykH5CY4TSfsuizAgyPuQ0
+j4Vjssr9VODLqFoanspT6YXsvaKanncUYbasNgUJnfnLnw3an2XpU2XdmXTNYckCPRX9nsAAURWT3/n9ljc/XYY22ecYxM
8sDWnHu2uKZ1B7M3X60bQYL5T/lVXkKdD6xgSNLeP4AkRx0H4egaop68hoW8FIwmDPVWYVAvo8etzWCtibRXz5FcNld9MgD
/Ai7ycKy4Q1KhX5GBFI79MVVaHkSQfxPHpr7/XcmpQOEAr+BMPon4s4vnKqAGdGB3j/E3d/+4F2swykoQKBgQD8hCsp6FIQ
5umJlk9/j/nGsMl85LgLaNVYpWlPRKPc54YNumtvj5vx1BG+zMbT7qIE3nmUPTCHP7qb5ERZG4CdMCS6S64/qzZEqijLCqe
pwj6j4fV5SyPWEcpxf6ehNdmcfgzVB3Wolfwh1ydhx/96L1jHJcTKchdJJzlfTvq8wwKBgQDeCnKws1t5GapfE1rmC/h4ol
L2qZTth9oQmbrXYohVnoqNFslDa43ePZwL9Jmd9kYb0axOTNMmyrP0NTj41uCfgDS0cJnNTc63ojKjegxHIyYDKRZNVUR/d
xAYB/vPfBYZUS7M89pO6LLsHhzS3qpu3/hppo/Uc/AM/r8PSflNHQKBgDnWgBh6OQncChPUlOLv9FMZPR1ZOfqLCYrjYEqi
uzGm6iKM13zXFO4AGAxu1P/IAd5BovFcTpg79Z8tWqZaUUwvscnl+cRlj+mMXAmdqCeO8VASOmqM1ml667axeZDIR867ZG8
K5V029Wg+4qtX5uFypNAAi6GfHkxIKrD04yOHAoGACdh4wXESi0oiDdkz3KOHPwIjn6BhZC7z8mx+pnJODU3cYukxv3WTct
lUhAsyjJiQ/0bK1yX87ulqFVgO0Knmh+wNajrb9wiONAJTMICG7tiWJOm7fW5cfTJwWkBwYADmkfTRmHDvqzQSSvoC2S7aa
9QulbC3C/qgGFNrcWgcT9kCgYAZTa1P9bFCDU7hJc2mHwJwAW7/FQKEJg8SL33KINpLwcR8fqaYOdAHWWz636osVEqosRrH
zJOGpf9x2RSWzQJ+dq8+6fACgfFZOVpN644+sAHfNPAI/gnNKU5OfUv+eav8fBnzlf1A3y3GIkyMyzFN3DE7e0n/lyqxE4H
BYGpI8g==
""".strip()

def abrir_driver_cred():
    # Configuracao de opcoes
    options = Options()
    options.accept_insecure_certs = True
    options.add_argument("--headless=new")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")

    driver = webdriver.Chrome(options=options)

    # 1) Configurar Virtual Authenticator apto a Resident Credential
    va_options = VirtualAuthenticatorOptions()
    va_options.protocol = VirtualAuthenticatorOptions.Protocol.CTAP2
    va_options.has_resident_key = True
    va_options.has_user_verification = True
    va_options.is_user_verified = True
    driver.add_virtual_authenticator(va_options)  # registra o autenticador virtual[page:3]

    # 2) Criar e adicionar uma Resident Credential
    credential_id = bytearray({5, 3, 3, 4})  # id da credencial (ajuste se quiser)
    rp_id = "https://douradina.pr.gov.br/"                      # domínio do seu RP (use o domínio real do site)
    user_handle = bytearray({1})             # identificador do usuário
    private_key = urlsafe_b64decode(BASE64_ENCODED_PK)
    sign_count = 0

    resident_credential = Credential.create_resident_credential(
        credential_id,
        rp_id,
        user_handle,
        private_key,
        sign_count,
    )  # mesma assinatura do exemplo oficial em Python[page:3]

    driver.add_credential(resident_credential)  # injeta a credencial no autenticador virtual[page:3]

    # 3) Restante da sua configuração de cliente
    retries = Retry(total=1, connect=1, read=1, backoff_factor=0.5)
    driver.command_executor._conn.connection_pool_kw["retries"] = retries
    driver.set_page_load_timeout(90)
    driver.get("chrome://settings/")
    driver.execute_script("chrome.settingsPrivate.setDefaultZoom(0.75);")

    return driver'''

In [ ]:
a = q_selenium(664,64,65)
a

In [ ]:
driver =  abrir_driver()
inicio = time.time()
texto_click = []
html_click = []
e = None
f = None
b = ["radardatransparencia.atricon"]
p = padroniza_parametro(["Radar"])
try:
  driver.set_page_load_timeout(10000)
  driver.get("https://candidodeabreu.pr.gov.br/")


except Exception as e:
  print(e)

wait = WebDriverWait(driver, 40)
print(round(time.time() - inicio, 2),"in")

try:
  wait.until(
    EC.any_of(EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main")),
              EC.presence_of_all_elements_located((By.TAG_NAME,"body"))
              )
    )
  print(round(time.time() - inicio, 2),"wt")

except TimeoutException:
  print("Timeout esperando carregamento principal, seguindo mesmo assim.")



try:
  driver.implicitly_wait(10)
  url_inicial = driver.current_url
  elemento, html_elemento, lista_elementos = buscador(driver,"link", b)
  elemento, html_elemento, lista_elementos = buscador(driver,"link", b)
  print(round(time.time() - inicio, 2),"b0")

  if not elemento:
    ##FLUXO DE NENHUM ELEMENTO ENCONTRADO
    ##BUSCA POR PARAMENTRO DE NAVEGACAO
    try:

      print(round(time.time() - inicio, 2),"bt")
      bt_aceito(driver)
      lista_elementos = []
      vistos = set() # Changed to set for efficient `id` checking
      for pi in p:
          try:
              print(round(time.time() - inicio, 2),"find")
              els = driver.find_elements(By.XPATH, f'//*[contains(text(),"{pi}")]') #BUSCA ELEMENTOS QUE TENHAM TEXTO P

              if not els:
                els = []

              print(round(time.time() - inicio, 2),"find1")
              elementos_atrib = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{pi}')]]") #BUSCA ELEMENTOS QUE TENHAM ATRIBUTO P
              print(round(time.time() - inicio, 2),"find2")

              if not elementos_atrib:
                elementos_atrib = []

              for el in els + elementos_atrib:
                  try:
                      txt = el.text
                      html = el.get_attribute("outerHTML")
                      id = (txt, html)

                      if id not in vistos and el not in lista_elementos:
                          lista_elementos.append(el)
                          vistos.add(id)
                  except:
                      continue

          except NoSuchElementException:
              print('Elemento não localizado')
              pass




      if lista_elementos:
        for el in lista_elementos:
            print(round(time.time() - inicio, 2),"el")
            try:
                texto_click.append(el.text)
                html_click.append(el.get_attribute("outerHTML"))

                clicker(driver,el)
                driver.implicitly_wait(5)
                url_click = driver.current_url

                # Moved these lines inside the try block, as they were unreachable before
                elemento, html_elemento, lista_elementos = buscador(driver,"link", b)

                if not lista_elementos and url_click == url_inicial:
                    pass

                if not lista_elementos and url_click != url_inicial:
                    while url_click != url_inicial:
                        print(round(time.time() - inicio, 2),"url")
                        driver.back()
                        driver.implicitly_wait(5)
                        url_click = driver.current_url
                    pass

                if lista_elementos:
                    break
            except:
                continue # If an exception occurs, continue to the next element

      if not lista_elementos:
        print(round(time.time() - inicio, 2),"bl1")
        frases_bloqueio = ["Performing security verification", "have been blocked","403 Forbidden",
                            "A página solicitada não foi encontrada","The request could",
                            "Desculpe, não conseguimos",
                            "This page is used","ERRO 500","Bad Gateway",
                            "Blocked request"]


        texto_pg = driver.find_element(By.TAG_NAME,"*").text

        # Verifica se alguma frase f de frases_bloqueio é uma substring de qualquer texto t em textos_corpo
        print(round(time.time() - inicio, 2),"bl2")
        bloqueio = any(f in texto_pg for f in frases_bloqueio)
        print(round(time.time() - inicio, 2),"bl")


        if bloqueio == True:
          error_cod = "URL_BLOCKED"
          error_msg = "URL bloqueada"

        else:
          html_selenium = driver.page_source
          error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
          error_msg = f"Nenhum elemento final localizado na página contendo: {p} ou de interação contendo: {b}"


    except NoSuchElementException as e:
        error_cod = "NoSuchElementException"
        error_msg = str(e)
        textos_corpo, html_corpo = busca_todo_texto(driver, "body")
        texto_click = textos_corpo
        html_click = html_corpo


except Exception as e:
  if not error_cod:
      error_cod = type(e).__name__
      error_msg = str(e)
  print(f"Erro na busca de elementos para : {e}")

In [ ]:
driver.current_url

In [ ]:
driver = abrir_driver()
driver.get("https://transparencia.e-publica.net/epublica-portal/#/perola_oeste/portal?entidade=1510")

In [ ]:
el, ht, lista = busca_link(driver, p)

In [ ]:
els = localiza_clicks(driver, ["Radar"])

In [ ]:
ep = localiza_pai(els[0])

In [ ]:
driver.execute_script("arguments[0].click()",ep)

In [ ]:
actions = ActionChains(driver)
actions.move_to_element(ep).click().perform()

In [ ]:
ep.get_attribute("outerHTML")

'<div class="portal-widget-link-rectangle cursor-pointer" ng-if="component.componentType === \'LINK\' &amp;&amp; !component.hasError" ng-class="{ \'cursor-pointer\': !!component.webAddress || !!component.widgetBeanMenuLinkSelect }" ng-click="openLinkWidget(component)"><div class="portal-widget-link-title">Radar da Transparência Pública</div><i class="epublica-icon-arrow-right portal-widget-link-icon"></i></div>'

In [ ]:
try:
    print('Simulando Hover + Clique e checando abas...')
    original_window = driver.current_window_handle

    actions = ActionChains(driver)
    actions.move_to_element(ep).pause(1).click().perform()
    time.sleep(5)

    # Verifica se abriu uma nova aba
    if len(driver.window_handles) > 1:
        for handle in driver.window_handles:
            if handle != original_window:
                driver.switch_to.window(handle)
                print(f'Nova aba detectada! URL: {driver.current_url}')
                break
    else:
        print(f'URL na aba atual: {driver.current_url}')

except Exception as e:
    print(f'Erro na interação de hover/abas: {e}')

Simulando Hover + Clique e checando abas...
Erro na interação de hover/abas: Message: timeout: Timed out receiving message from renderer: 90.000
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5d374eba8a6a <unknown>
#1 0x5d374e5b7ab5 <unknown>
#2 0x5d374e59f3bb <unknown>
#3 0x5d374e59f0a4 <unknown>
#4 0x5d374e59cdeb <unknown>
#5 0x5d374e59d76f <unknown>
#6 0x5d374e5ac7a0 <unknown>
#7 0x5d374e5c64b7 <unknown>
#8 0x5d374e5ccfeb <unknown>
#9 0x5d374e59debf <unknown>
#10 0x5d374e5c624b <unknown>
#11 0x5d374e65267f <unknown>
#12 0x5d374e5fdcbf <unknown>
#13 0x5d374e5fea81 <unknown>
#14 0x5d374eb6ea64 <unknown>
#15 0x5d374eb71951 <unknown>
#16 0x5d374eb5b21e <unknown>
#17 0x5d374eb7251e <unknown>
#18 0x5d374eb41be0 <unknown>
#19 0x5d374eb959b8 <unknown>
#20 0x5d374eb95b88 <unknown>
#21 0x5d374eba74de <unknown>
#22 0x7afbbd031ac3 <unknown>

In [ ]:
driver.current_window_handle
driver.switch_to.window(driver.window_handles[1])

In [ ]:
ep.click()

In [ ]:
driver.close()

In [ ]:
driver.window_handles

['6067A2AA98113D8FBB75BC2B198ED049', '69C40EE11432E800CD3BF33597A7C2B5']

In [ ]:
bt_aceito(driver)

In [ ]:
driver.back()

###EM BLOCO

In [60]:
q = 664
tp = "link"
pv = ["radardatransparencia.atricon"]
pn = ["radar"]
df_link = links_detalhes

In [61]:
q664_1 = q_selenium_paralelo(q,tp,pv,pn, df_link, 0, 65, threads=4)

Tempo de execução para https://cianorte.oxy.elotech.com.br/portaltransparencia/1/: 9.71s
Tempo de execução para https://marmeleiro.atende.net/transparencia/: 22.77s
Tempo de execução para https://www.bocaiuvadosul.pr.gov.br/: 37.31s
Tempo de execução para https://barracao.pr.gov.br/: 39.6s
Tempo de execução para https://mandirituba.pr.gov.br/portal-da-transparencia/informacoes-gerais/radar-da-transparenciapublica: 4.94s
Tempo de execução para https://antonioolinto.eloweb.net/portaltransparencia/1/: 21.3s
Tempo de execução para https://tapira.eloweb.net/portaltransparencia/1/: 16.74s
Tempo de execução para https://terraboa.eloweb.net/portaltransparencia/1/: 11.11s
WebDriver error for https://www.marialva.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5a9d76054b6a <unknown>
#1 0x5a9d75a56265 <unknown>
#2 0x5a9d75a4d09f <unknown>
#3 0x5a9d75a3de31 <unknown>
#4 0x5a9d75a3fc2c <unknown>
#5 0x5a9d75a3e32a <unknown>
#6 0x5a9d75a3db50 <unknown>
#7 0x5a9d75a3d804 <unknown>
#8 0x5a9d75a3b54b <unknown>
#9 0x5a9d75a3bd90 <unknown>
#10 0x5a9d75a5999d <unknown>
#11 0x5a9d75af267b <unknown>
#12 0x5a9d75af1969 <unknown>
#13 0x5a9d75a9c5cf <unknown>
#14 0x5a9d75a9d391 <unknown>
#15 0x5a9d7601a04b <unknown>
#16 0x5a9d7601d00d <unknown>
#17 0x5a9d76006808 <unknown>
#18 0x5a9d7601dba0 <unknown>
#19 0x5a9d75fed280 <unknown>
#20 0x5a9d76041db8 <unknown>
#21 0x5a9d76041f88 <unknown>
#22 0x5a9d760535de <unknown>
#23 0x78e98078dac3 <unknown>

Tempo de execução para https://www.marialva.pr.gov.br/: 73.56s
Tempo de execução para https://ibipora.eloweb.net/portaltransparencia/1/publicacoes/1056: 11.66s
Tempo de execução para https://fazendariogrande.pr.gov.br/transparencia: 4.24s
Tempo de execução para https://santaizabeldooeste.atende.net/cidadao: 30.0s
Tempo de execução para https://ouroverdedooeste.atende.net/: 28.34s
General error for https://saotomepr.equiplano.com.br:7430/transparencia/: HTTPConnectionPool(host='localhost', port=36165): Read timed out. (read timeout=120)
Tempo de execução para https://saotomepr.equiplano.com.br:7430/transparencia/: 123.88s
Tempo de execução para https://www.veracruz.pr.gov.br/: 126.08s
Progresso: 10/65
Tempo de execução para https://riobranco.eloweb.net/portaltransparencia/1/: 18.29s
Progresso: 20/65
Tempo de execução para https://transparencia.cambe.pr.gov.br:8443/portal/index.xhtml: 11.48s
Tempo de execução para https://patobragado.atende.net/subportal/portal-da-transparencia: 3.21s
Tempo de execução para https://marechalcandidorondon.atende.net/cidadao: 132.49s
Tempo de execução para https://www.esperancanova.pr.gov.br/: 15.28s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=36165): Read timed out. (read timeout=120)")': /session/55ddc1c861f854519180e2c2194e0261

Tempo de execução para https://guaraniacu.atende.net/: 136.87s
Tempo de execução para https://transparencia.betha.cloud/#/cFVgtYEEPVrO7Xy4RZ_lXg==: 1.75s
WebDriver error for https://presidentecastelobranco.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5b64a1168b6a <unknown>
#1 0x5b64a0b6a265 <unknown>
#2 0x5b64a0b6109f <unknown>
#3 0x5b64a0b51e31 <unknown>
#4 0x5b64a0b53c2c <unknown>
#5 0x5b64a0b5232a <unknown>
#6 0x5b64a0b51b50 <unknown>
#7 0x5b64a0b51804 <unknown>
#8 0x5b64a0b4f54b <unknown>
#9 0x5b64a0b4fd90 <unknown>
#10 0x5b64a0b6d99d <unknown>
#11 0x5b64a0c0667b <unknown>
#12 0x5b64a0c05969 <unknown>
#13 0x5b64a0bb05cf <unknown>
#14 0x5b64a0bb1391 <unknown>
#15 0x5b64a112e04b <unknown>
#16 0x5b64a113100d <unknown>
#17 0x5b64a111a808 <unknown>
#18 0x5b64a1131ba0 <unknown>
#19 0x5b64a1101280 <unknown>
#20 0x5b64a1155db8 <unknown>
#21 0x5b64a1155f88 <unknown>
#22 0x5b64a11675de <unknown>
#23 0x7840477a2ac3 <unknown>

Tempo de execução para https://presidentecastelobranco.pr.gov.br/: 74.15s
Tempo de execução para https://www.pmcds.pr.gov.br/portalTransparencia/: 115.8s
WebDriver error for http://california.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5d38e013eb6a <unknown>
#1 0x5d38dfb40265 <unknown>
#2 0x5d38dfb3709f <unknown>
#3 0x5d38dfb27e31 <unknown>
#4 0x5d38dfb29c2c <unknown>
#5 0x5d38dfb2832a <unknown>
#6 0x5d38dfb27b50 <unknown>
#7 0x5d38dfb27804 <unknown>
#8 0x5d38dfb2554b <unknown>
#9 0x5d38dfb25d90 <unknown>
#10 0x5d38dfb4399d <unknown>
#11 0x5d38dfbdc67b <unknown>
#12 0x5d38dfbdb969 <unknown>
#13 0x5d38dfb865cf <unknown>
#14 0x5d38dfb87391 <unknown>
#15 0x5d38e010404b <unknown>
#16 0x5d38e010700d <unknown>
#17 0x5d38e00f0808 <unknown>
#18 0x5d38e0107ba0 <unknown>
#19 0x5d38e00d7280 <unknown>
#20 0x5d38e012bdb8 <unknown>
#21 0x5d38e012bf88 <unknown>
#22 0x5d38e013d5de <unknown>
#23 0x7df170672ac3 <unknown>

Tempo de execução para http://california.pr.gov.br/: 32.9s
Tempo de execução para https://loanda.eloweb.net/portaltransparencia/1/: 11.75s
Tempo de execução para https://franciscoalves.eloweb.net/portaltransparencia/1/: 14.03s
Progresso: 30/65
Tempo de execução para https://carambei.atende.net/cidadao: 27.98s
Tempo de execução para https://anahy.atende.net/: 26.27s
WebDriver error for https://www.saocarlosdoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x58b94f919b6a <unknown>
#1 0x58b94f31b265 <unknown>
#2 0x58b94f31209f <unknown>
#3 0x58b94f302e31 <unknown>
#4 0x58b94f304c2c <unknown>
#5 0x58b94f30332a <unknown>
#6 0x58b94f302b50 <unknown>
#7 0x58b94f302804 <unknown>
#8 0x58b94f30054b <unknown>
#9 0x58b94f300d90 <unknown>
#10 0x58b94f31e99d <unknown>
#11 0x58b94f3b767b <unknown>
#12 0x58b94f3b6969 <unknown>
#13 0x58b94f3615cf <unknown>
#14 0x58b94f362391 <unknown>
#15 0x58b94f8df04b <unknown>
#16 0x58b94f8e200d <unknown>
#17 0x58b94f8cb808 <unknown>
#18 0x58b94f8e2ba0 <unknown>
#19 0x58b94f8b2280 <unknown>
#20 0x58b94f906db8 <unknown>
#21 0x58b94f906f88 <unknown>
#22 0x58b94f9185de <unknown>
#23 0x79eaacd07ac3 <unknown>

Tempo de execução para https://www.saocarlosdoivai.pr.gov.br/: 65.93s
Tempo de execução para  https://cascavel.atende.net/transparencia/: 13.7s
Tempo de execução para https://transparencia.betha.cloud/#/QZgNvTT4qFk80u10mrdMPg==/consulta/75669: 4.44s
Tempo de execução para https://www.saopedrodoiguacu.pr.gov.br/: 4.44s
WebDriver error for http://www.saopedrodoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x57b849b42b6a <unknown>
#1 0x57b849544265 <unknown>
#2 0x57b84953b09f <unknown>
#3 0x57b84952be31 <unknown>
#4 0x57b84952dc2c <unknown>
#5 0x57b84952c32a <unknown>
#6 0x57b84952bb50 <unknown>
#7 0x57b84952b804 <unknown>
#8 0x57b84952954b <unknown>
#9 0x57b849529d90 <unknown>
#10 0x57b84954799d <unknown>
#11 0x57b8495e067b <unknown>
#12 0x57b8495df969 <unknown>
#13 0x57b84958a5cf <unknown>
#14 0x57b84958b391 <unknown>
#15 0x57b849b0804b <unknown>
#16 0x57b849b0b00d <unknown>
#17 0x57b849af4808 <unknown>
#18 0x57b849b0bba0 <unknown>
#19 0x57b849adb280 <unknown>
#20 0x57b849b2fdb8 <unknown>
#21 0x57b849b2ff88 <unknown>
#22 0x57b849b415de <unknown>
#23 0x79dd7f3c9ac3 <unknown>

Tempo de execução para http://www.saopedrodoivai.pr.gov.br/: 21.12s
Tempo de execução para https://guaira.atende.net/?pg=transparencia#!/: 19.44s
Progresso: 40/65
Tempo de execução para http://45.225.146.100:8090/ portaltransparencia/1/: 5.9s
Tempo de execução para https://www.grandesrios.pr.gov.br/: 13.55s
Tempo de execução para https://www.centenariodosul.pr.gov.br/index.php: 23.67s
Tempo de execução para http://www.campinadosimao.pr.gov.br/index.php: 8.62s
WebDriver error for https://www.sertaneja.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x56cb399f3b6a <unknown>
#1 0x56cb393f5265 <unknown>
#2 0x56cb393ec09f <unknown>
#3 0x56cb393dce31 <unknown>
#4 0x56cb393dec2c <unknown>
#5 0x56cb393dd32a <unknown>
#6 0x56cb393dcb50 <unknown>
#7 0x56cb393dc804 <unknown>
#8 0x56cb393da54b <unknown>
#9 0x56cb393dad90 <unknown>
#10 0x56cb393f899d <unknown>
#11 0x56cb3949167b <unknown>
#12 0x56cb39490969 <unknown>
#13 0x56cb3943b5cf <unknown>
#14 0x56cb3943c391 <unknown>
#15 0x56cb399b904b <unknown>
#16 0x56cb399bc00d <unknown>
#17 0x56cb399a5808 <unknown>
#18 0x56cb399bcba0 <unknown>
#19 0x56cb3998c280 <unknown>
#20 0x56cb399e0db8 <unknown>
#21 0x56cb399e0f88 <unknown>
#22 0x56cb399f25de <unknown>
#23 0x7d4c7ce7bac3 <unknown>

Tempo de execução para https://www.sertaneja.pr.gov.br/: 84.5s
Tempo de execução para https://transparencia.betha.cloud/#/XsTYmnrmpsOvZ8_9fe1GYw==: 3.42s
Tempo de execução para https://cambira.eloweb.net/portaltransparencia/1/: 11.32s
General error for https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: HTTPConnectionPool(host='localhost', port=41831): Read timed out. (read timeout=120)
Tempo de execução para https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: 121.36s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=46683): Read timed out. (read timeout=120)")': /session/58ecdd60e639aa1d12f978899cd35199/url

Tempo de execução para https://araruna.eloweb.net/portaltransparencia/1/: 225.28s
General error for http://177.92.1.11:7474/transparencia/: HTTPConnectionPool(host='localhost', port=37893): Read timed out. (read timeout=120)
Tempo de execução para http://177.92.1.11:7474/transparencia/: 121.59s
General error for https://campomagro.pr.gov.br/: HTTPConnectionPool(host='localhost', port=54887): Read timed out. (read timeout=120)
Tempo de execução para https://campomagro.pr.gov.br/: 121.58s
Tempo de execução para https://guaraci.eloweb.net/portaltransparencia/1/: 10.06s
Tempo de execução para https://itambe.eloweb.net/portaltransparencia/1/: 7.38s
Tempo de execução para https://www.bituruna.pr.gov.br//portalTransparencia/: 2.37s
Tempo de execução para https://transparencia.betha.cloud/#/r2cpj2e4mrz8xjHlykU8bg==: 3.31s
WebDriver error for http://www.iracemadooeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5b299c250b6a <unknown>
#1 0x5b299bc52265 <unknown>
#2 0x5b299bc4909f <unknown>
#3 0x5b299bc39e31 <unknown>
#4 0x5b299bc3bc2c <unknown>
#5 0x5b299bc3a32a <unknown>
#6 0x5b299bc39b50 <unknown>
#7 0x5b299bc39804 <unknown>
#8 0x5b299bc3754b <unknown>
#9 0x5b299bc37d90 <unknown>
#10 0x5b299bc5599d <unknown>
#11 0x5b299bcee67b <unknown>
#12 0x5b299bced969 <unknown>
#13 0x5b299bc985cf <unknown>
#14 0x5b299bc99391 <unknown>
#15 0x5b299c21604b <unknown>
#16 0x5b299c21900d <unknown>
#17 0x5b299c202808 <unknown>
#18 0x5b299c219ba0 <unknown>
#19 0x5b299c1e9280 <unknown>
#20 0x5b299c23ddb8 <unknown>
#21 0x5b299c23df88 <unknown>
#22 0x5b299c24f5de <unknown>
#23 0x7a9fca40eac3 <unknown>

Tempo de execução para http://www.iracemadooeste.pr.gov.br/: 32.97s
Tempo de execução para https://www.transparencia.curitiba.pr.gov.br/: 8.0s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=41831): Read timed out. (read timeout=120)")': /session/ae9fc26480f4b03f15176c0b64c36603
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=37893): Read timed out. (read timeout=120)")': /session/8d95a4c61c12ba0ec364f0042cf88d22

General error for https://uraipr.equiplano.com.br:7446/transparencia/: HTTPConnectionPool(host='localhost', port=33617): Read timed out. (read timeout=120)
Tempo de execução para https://uraipr.equiplano.com.br:7446/transparencia/: 121.52s
Tempo de execução para https://pmsas.pr.gov.br/: 12.99s
Progresso: 60/65

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=33617): Read timed out. (read timeout=120)")': /session/8214ababed270cba88166985bbe878d8

Tempo de execução para https://transparencia.missal.pr.gov.br/: 29.4s
Tempo de execução para https://www.iguaracu.pr.gov.br/: 22.08s
Tempo de execução para https://www.jussara.pr.gov.br/: 237.13s
Tempo de execução para https://www.itaipulandia.pr.gov.br/: 59.26s
Tempo de execução para http://s2.asp.srv.br/etransparencia.pm.santamonica.pr/servlet/wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg=: 95.0s
Progresso: 50/65
Tempo de execução para https://www.icaraima.pr.gov.br/index.php: 240.52s

In [62]:
q664_2 = q_selenium_paralelo(q,tp,pv,pn,df_link,65, 130, threads=4)

Tempo de execução para https://transparencia.betha.cloud/#/9JCGb59gmZKaC3wzdXmbRw==: 7.35s
Tempo de execução para https://www.sjpalmeiras.pr.gov.br/transparencia: 19.69s
WebDriver error for https://mariopolis.govbr.cloud/pronimtb/index.html: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x571933accb6a <unknown>
#1 0x5719334ce265 <unknown>
#2 0x5719334c509f <unknown>
#3 0x5719334b5e31 <unknown>
#4 0x5719334b7c2c <unknown>
#5 0x5719334b632a <unknown>
#6 0x5719334b5b50 <unknown>
#7 0x5719334b5804 <unknown>
#8 0x5719334b354b <unknown>
#9 0x5719334b3d90 <unknown>
#10 0x5719334d199d <unknown>
#11 0x57193356a67b <unknown>
#12 0x571933569969 <unknown>
#13 0x5719335145cf <unknown>
#14 0x571933515391 <unknown>
#15 0x571933a9204b <unknown>
#16 0x571933a9500d <unknown>
#17 0x571933a7e808 <unknown>
#18 0x571933a95ba0 <unknown>
#19 0x571933a65280 <unknown>
#20 0x571933ab9db8 <unknown>
#21 0x571933ab9f88 <unknown>
#22 0x571933acb5de <unknown>
#23 0x7b1f6dc64ac3 <unknown>

Tempo de execução para https://mariopolis.govbr.cloud/pronimtb/index.html: 5.09s
WebDriver error for https://www.cruzeirodooeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5944f6d5bb6a <unknown>
#1 0x5944f675d265 <unknown>
#2 0x5944f675409f <unknown>
#3 0x5944f6744e31 <unknown>
#4 0x5944f6746c2c <unknown>
#5 0x5944f674532a <unknown>
#6 0x5944f6744b50 <unknown>
#7 0x5944f6744804 <unknown>
#8 0x5944f674254b <unknown>
#9 0x5944f6742d90 <unknown>
#10 0x5944f676099d <unknown>
#11 0x5944f67f967b <unknown>
#12 0x5944f67f8969 <unknown>
#13 0x5944f67a35cf <unknown>
#14 0x5944f67a4391 <unknown>
#15 0x5944f6d2104b <unknown>
#16 0x5944f6d2400d <unknown>
#17 0x5944f6d0d808 <unknown>
#18 0x5944f6d24ba0 <unknown>
#19 0x5944f6cf4280 <unknown>
#20 0x5944f6d48db8 <unknown>
#21 0x5944f6d48f88 <unknown>
#22 0x5944f6d5a5de <unknown>
#23 0x7c467197eac3 <unknown>

Tempo de execução para https://www.cruzeirodooeste.pr.gov.br/: 48.86s
Tempo de execução para https://paraisodonorte.atende.net/: 25.79s
Erro: URL inválida recebida: nan
Progresso: 10/65
Tempo de execução para https://douradina.pr.gov.br/: 6.66s
Tempo de execução para https://www.angulo.pr.gov.br/: 36.31s
Tempo de execução para https://www.senges.pr.gov.br/portal/transparencia/: 11.94s
WebDriver error for https://www.pontaldoparana.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5c87928f4b6a <unknown>
#1 0x5c87922f6265 <unknown>
#2 0x5c87922ed09f <unknown>
#3 0x5c87922dde31 <unknown>
#4 0x5c87922dfc2c <unknown>
#5 0x5c87922de32a <unknown>
#6 0x5c87922ddb50 <unknown>
#7 0x5c87922dd804 <unknown>
#8 0x5c87922db54b <unknown>
#9 0x5c87922dbd90 <unknown>
#10 0x5c87922f999d <unknown>
#11 0x5c879239267b <unknown>
#12 0x5c8792391969 <unknown>
#13 0x5c879233c5cf <unknown>
#14 0x5c879233d391 <unknown>
#15 0x5c87928ba04b <unknown>
#16 0x5c87928bd00d <unknown>
#17 0x5c87928a6808 <unknown>
#18 0x5c87928bdba0 <unknown>
#19 0x5c879288d280 <unknown>
#20 0x5c87928e1db8 <unknown>
#21 0x5c87928e1f88 <unknown>
#22 0x5c87928f35de <unknown>
#23 0x7c75b9cd6ac3 <unknown>

Tempo de execução para https://www.pontaldoparana.pr.gov.br/: 55.63s
WebDriver error for http://sistemas.ivai.pr.gov.br:7020/transparencia/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x56d6deec0b6a <unknown>
#1 0x56d6de8c2265 <unknown>
#2 0x56d6de8b909f <unknown>
#3 0x56d6de8a9e31 <unknown>
#4 0x56d6de8abc2c <unknown>
#5 0x56d6de8aa32a <unknown>
#6 0x56d6de8a9b50 <unknown>
#7 0x56d6de8a9804 <unknown>
#8 0x56d6de8a754b <unknown>
#9 0x56d6de8a7d90 <unknown>
#10 0x56d6de8c599d <unknown>
#11 0x56d6de95e67b <unknown>
#12 0x56d6de95d969 <unknown>
#13 0x56d6de9085cf <unknown>
#14 0x56d6de909391 <unknown>
#15 0x56d6dee8604b <unknown>
#16 0x56d6dee8900d <unknown>
#17 0x56d6dee72808 <unknown>
#18 0x56d6dee89ba0 <unknown>
#19 0x56d6dee59280 <unknown>
#20 0x56d6deeaddb8 <unknown>
#21 0x56d6deeadf88 <unknown>
#22 0x56d6deebf5de <unknown>
#23 0x7ad0c2f31ac3 <unknown>

Tempo de execução para http://sistemas.ivai.pr.gov.br:7020/transparencia/: 13.95s
General error for https://guairacapr.equiplano.com.br:7461/transparencia/: HTTPConnectionPool(host='localhost', port=52479): Read timed out. (read timeout=120)
Tempo de execução para https://guairacapr.equiplano.com.br:7461/transparencia/: 123.92s
Tempo de execução para https://www.quitandinha.pr.gov.br/: 133.33s
WebDriver error for http://godoymoreira.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5ad2447d1b6a <unknown>
#1 0x5ad2441d3265 <unknown>
#2 0x5ad2441ca09f <unknown>
#3 0x5ad2441bae31 <unknown>
#4 0x5ad2441bcc2c <unknown>
#5 0x5ad2441bb32a <unknown>
#6 0x5ad2441bab50 <unknown>
#7 0x5ad2441ba804 <unknown>
#8 0x5ad2441b854b <unknown>
#9 0x5ad2441b8d90 <unknown>
#10 0x5ad2441d699d <unknown>
#11 0x5ad24426f67b <unknown>
#12 0x5ad24426e969 <unknown>
#13 0x5ad2442195cf <unknown>
#14 0x5ad24421a391 <unknown>
#15 0x5ad24479704b <unknown>
#16 0x5ad24479a00d <unknown>
#17 0x5ad244783808 <unknown>
#18 0x5ad24479aba0 <unknown>
#19 0x5ad24476a280 <unknown>
#20 0x5ad2447bedb8 <unknown>
#21 0x5ad2447bef88 <unknown>
#22 0x5ad2447d05de <unknown>
#23 0x7fac3317cac3 <unknown>

Tempo de execução para http://godoymoreira.pr.gov.br/: 26.66s
Tempo de execução para https://www.campinadalagoa.pr.gov.br/: 12.88s
Tempo de execução para https://www.reservadoiguacu.pr.gov.br/: 7.51s
Progresso: 20/65
Tempo de execução para https://www.cantagalo.pr.gov.br/: 16.74s
Tempo de execução para https://santoantoniodaplatina.atende.net/cidadao: 21.18s
General error for https://prudentopolispr.equiplano.com.br:7443/transparencia/: HTTPConnectionPool(host='localhost', port=46945): Read timed out. (read timeout=120)
Tempo de execução para https://prudentopolispr.equiplano.com.br:7443/transparencia/: 121.27s
Tempo de execução para https://www.pinhaldesaobento.pr.gov.br/portal/: 11.96s
Tempo de execução para https://transparencia.betha.cloud/#/bGt4VnWNiKNT6r5CBDED_Q==: 1.31s
Tempo de execução para https://transparencia.betha.cloud/#/IKR2wBO51OO0hvKMMKC60Q==: 2.07s
Tempo de execução para https://www.marumbi.pr.gov.br/: 8.72s
Tempo de execução para https://www.cruzeirodosul.pr.gov.br/: 9.49s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=52479): Read timed out. (read timeout=120)")': /session/8bde1eef2251c4f7fa572ed3f6a2ca1d

General error for https://servicos.pontagrossa.pr.gov.br/portaltransparencia/1/: HTTPConnectionPool(host='localhost', port=49037): Read timed out. (read timeout=120)
Tempo de execução para https://servicos.pontagrossa.pr.gov.br/portaltransparencia/1/: 122.88s
Tempo de execução para https://lobato.pr.gov.br/: 11.96s
Tempo de execução para https://peabiru.pr.gov.br/: 5.87s
Tempo de execução para https://kalore.pr.gov.br/index.php: 8.45s
Progresso: 30/65
Tempo de execução para https://doutorulysses.pr.gov.br/: 9.71s
Tempo de execução para https://www.jundiaidosul.pr.gov.br/: 15.25s
WebDriver error for http://pmsac.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x577c2e8eab6a <unknown>
#1 0x577c2e2ec265 <unknown>
#2 0x577c2e2e309f <unknown>
#3 0x577c2e2d3e31 <unknown>
#4 0x577c2e2d5c2c <unknown>
#5 0x577c2e2d432a <unknown>
#6 0x577c2e2d3b50 <unknown>
#7 0x577c2e2d3804 <unknown>
#8 0x577c2e2d154b <unknown>
#9 0x577c2e2d1d90 <unknown>
#10 0x577c2e2ef99d <unknown>
#11 0x577c2e38867b <unknown>
#12 0x577c2e387969 <unknown>
#13 0x577c2e3325cf <unknown>
#14 0x577c2e333391 <unknown>
#15 0x577c2e8b004b <unknown>
#16 0x577c2e8b300d <unknown>
#17 0x577c2e89c808 <unknown>
#18 0x577c2e8b3ba0 <unknown>
#19 0x577c2e883280 <unknown>
#20 0x577c2e8d7db8 <unknown>
#21 0x577c2e8d7f88 <unknown>
#22 0x577c2e8e95de <unknown>
#23 0x7cd7196b2ac3 <unknown>

Tempo de execução para http://pmsac.pr.gov.br/: 36.45s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=46945): Read timed out. (read timeout=120)")': /session/738bc50f72116dfd22a00ba6faafae47

Tempo de execução para https://honorioserpa.atende.net/transparencia/: 12.17s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=49037): Read timed out. (read timeout=120)")': /session/0b269371fb83546a31ea6b4bb8c2e6d6

Tempo de execução para https://paranacity.pr.gov.br/: 20.97s
Tempo de execução para https://floresta.eloweb.net/portaltransparencia/1/: 19.83s
Tempo de execução para https://santaamelia.pr.gov.br/site/: 3.45s
Erro: URL inválida recebida: nan
Tempo de execução para https://quatigua.eloweb.net/portaltransparencia/1/: 13.71s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=45581): Read timed out. (read timeout=120)")': /session/2938762d8e8037955d70f16947a0d7a8/url

Tempo de execução para https://eneasmarques.atende.net/transparencia/: 224.32s
Tempo de execução para https://cerroazul.pr.gov.br/: 16.44s
Tempo de execução para https://www.faxinal.pr.gov.br/: 30.44s
Tempo de execução para https://irati.oxy.elotech.com.br/portaltransparencia/1/: 5.58s
Tempo de execução para https://transparencia.betha.cloud/#/BDRKTbIGezzmnLdgQXm36Q==: 3.11s
Tempo de execução para https://www.morretes.pr.gov.br/: 248.12s
Progresso: 50/65
Tempo de execução para https://transparencia.betha.cloud/#/vJCz3bLVV13kkolCQ31vAg==: 1.76s
WebDriver error for http://florai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5cf49e6c6b6a <unknown>
#1 0x5cf49e0c8265 <unknown>
#2 0x5cf49e0bf09f <unknown>
#3 0x5cf49e0afe31 <unknown>
#4 0x5cf49e0b1c2c <unknown>
#5 0x5cf49e0b032a <unknown>
#6 0x5cf49e0afb50 <unknown>
#7 0x5cf49e0af804 <unknown>
#8 0x5cf49e0ad54b <unknown>
#9 0x5cf49e0add90 <unknown>
#10 0x5cf49e0cb99d <unknown>
#11 0x5cf49e16467b <unknown>
#12 0x5cf49e163969 <unknown>
#13 0x5cf49e10e5cf <unknown>
#14 0x5cf49e10f391 <unknown>
#15 0x5cf49e68c04b <unknown>
#16 0x5cf49e68f00d <unknown>
#17 0x5cf49e678808 <unknown>
#18 0x5cf49e68fba0 <unknown>
#19 0x5cf49e65f280 <unknown>
#20 0x5cf49e6b3db8 <unknown>
#21 0x5cf49e6b3f88 <unknown>
#22 0x5cf49e6c55de <unknown>
#23 0x7f7adaff8ac3 <unknown>

Tempo de execução para http://florai.pr.gov.br/: 33.74s
WebDriver error for http://www.novaamericadacolina.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5ceb4edeab6a <unknown>
#1 0x5ceb4e7ec265 <unknown>
#2 0x5ceb4e7e309f <unknown>
#3 0x5ceb4e7d3e31 <unknown>
#4 0x5ceb4e7d5c2c <unknown>
#5 0x5ceb4e7d432a <unknown>
#6 0x5ceb4e7d3b50 <unknown>
#7 0x5ceb4e7d3804 <unknown>
#8 0x5ceb4e7d154b <unknown>
#9 0x5ceb4e7d1d90 <unknown>
#10 0x5ceb4e7ef99d <unknown>
#11 0x5ceb4e88867b <unknown>
#12 0x5ceb4e887969 <unknown>
#13 0x5ceb4e8325cf <unknown>
#14 0x5ceb4e833391 <unknown>
#15 0x5ceb4edb004b <unknown>
#16 0x5ceb4edb300d <unknown>
#17 0x5ceb4ed9c808 <unknown>
#18 0x5ceb4edb3ba0 <unknown>
#19 0x5ceb4ed83280 <unknown>
#20 0x5ceb4edd7db8 <unknown>
#21 0x5ceb4edd7f88 <unknown>
#22 0x5ceb4ede95de <unknown>
#23 0x7a7af2eddac3 <unknown>

Tempo de execução para http://www.novaamericadacolina.pr.gov.br/: 14.58s
Tempo de execução para https://jaguapita.pr.gov.br/: 224.15s
Progresso: 40/65
WebDriver error for https://www.assischateaubriand.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5838f23c9b6a <unknown>
#1 0x5838f1dcb265 <unknown>
#2 0x5838f1dc209f <unknown>
#3 0x5838f1db2e31 <unknown>
#4 0x5838f1db4c2c <unknown>
#5 0x5838f1db332a <unknown>
#6 0x5838f1db2b50 <unknown>
#7 0x5838f1db2804 <unknown>
#8 0x5838f1db054b <unknown>
#9 0x5838f1db0d90 <unknown>
#10 0x5838f1dce99d <unknown>
#11 0x5838f1e6767b <unknown>
#12 0x5838f1e66969 <unknown>
#13 0x5838f1e115cf <unknown>
#14 0x5838f1e12391 <unknown>
#15 0x5838f238f04b <unknown>
#16 0x5838f239200d <unknown>
#17 0x5838f237b808 <unknown>
#18 0x5838f2392ba0 <unknown>
#19 0x5838f2362280 <unknown>
#20 0x5838f23b6db8 <unknown>
#21 0x5838f23b6f88 <unknown>
#22 0x5838f23c85de <unknown>
#23 0x7dec5fa05ac3 <unknown>

Tempo de execução para https://www.assischateaubriand.pr.gov.br/: 43.72s
Tempo de execução para https://quatrobarras.eloweb.net/portaltransparencia/1/: 12.81s
Erro: URL inválida recebida: nan
Tempo de execução para https://www.ibaiti.pr.gov.br/: 18.79s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=53677): Read timed out. (read timeout=120)")': /session/df589319c7be756ffaf56fa11a1fa587/url

Tempo de execução para https://www.arapoti.pr.gov.br/: 29.35s
Tempo de execução para https://juranda.atende.net/cidadao/: 241.77s
Erro: URL inválida recebida: nan
Tempo de execução para https://www.sjtriunfo.pr.gov.br/portal/transparencia: 14.29s
Tempo de execução para http://portal.boavistadaaparecida.pr.gov.br:8090/portaltransparencia/1/: 14.22s
WebDriver error for http://www.iretama.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x58c2fd7dbb6a <unknown>
#1 0x58c2fd1dd265 <unknown>
#2 0x58c2fd1d409f <unknown>
#3 0x58c2fd1c4e31 <unknown>
#4 0x58c2fd1c6c2c <unknown>
#5 0x58c2fd1c532a <unknown>
#6 0x58c2fd1c4b50 <unknown>
#7 0x58c2fd1c4804 <unknown>
#8 0x58c2fd1c254b <unknown>
#9 0x58c2fd1c2d90 <unknown>
#10 0x58c2fd1e099d <unknown>
#11 0x58c2fd27967b <unknown>
#12 0x58c2fd278969 <unknown>
#13 0x58c2fd2235cf <unknown>
#14 0x58c2fd224391 <unknown>
#15 0x58c2fd7a104b <unknown>
#16 0x58c2fd7a400d <unknown>
#17 0x58c2fd78d808 <unknown>
#18 0x58c2fd7a4ba0 <unknown>
#19 0x58c2fd774280 <unknown>
#20 0x58c2fd7c8db8 <unknown>
#21 0x58c2fd7c8f88 <unknown>
#22 0x58c2fd7da5de <unknown>
#23 0x7fcdbb22bac3 <unknown>

Tempo de execução para http://www.iretama.pr.gov.br/: 35.79s
Progresso: 60/65
Tempo de execução para https://guarapuava.atende.net/transparencia/: 16.46s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=43553): Read timed out. (read timeout=120)")': /session/29c00c52a9b64ca9f7e0bf5e895e3c71/url

Tempo de execução para https://saojosedaboavista.pr.gov.br/: 234.81s
General error for https://www.toledo.pr.gov.br/ : HTTPConnectionPool(host='localhost', port=40355): Read timed out. (read timeout=120)
Tempo de execução para https://www.toledo.pr.gov.br/ : 121.67s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=40355): Read timed out. (read timeout=120)")': /session/276e188468a2040614d6d17379fd3650

In [63]:
q664_3 = q_selenium_paralelo(q,tp,pv,pn,df_link, 130, 195, threads=4)

Tempo de execução para https://transparencia.betha.cloud/#/dB2cqHx0nAQcUV6jVAEXbA==: 10.03s
Tempo de execução para https://marilandiadosul.pr.gov.br/: 35.87s
Tempo de execução para https://ariranhadoivai.eloweb.net/portaltransparencia/1/: 33.38s
Tempo de execução para https://www.mandaguacu.pr.gov.br/pagina/72/radar-da-transparencia/: 53.54s
Tempo de execução para https://www.perola.pr.gov.br/: 55.17s
Tempo de execução para https://roncador.eloweb.net/portaltransparencia/1/: 22.3s
Tempo de execução para https://cruzeirodoiguacu.pr.gov.br/portal-transparencia: 18.89s
Tempo de execução para https://santahelena.atende.net/cidadao/pagina/radar-transparencia: 34.04s
Tempo de execução para https://barradojacare.pr.gov.br/: 11.03s
WebDriver error for http://www.ourizona.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5a0e8a19ab6a <unknown>
#1 0x5a0e89b9c265 <unknown>
#2 0x5a0e89b9309f <unknown>
#3 0x5a0e89b83e31 <unknown>
#4 0x5a0e89b85c2c <unknown>
#5 0x5a0e89b8432a <unknown>
#6 0x5a0e89b83b50 <unknown>
#7 0x5a0e89b83804 <unknown>
#8 0x5a0e89b8154b <unknown>
#9 0x5a0e89b81d90 <unknown>
#10 0x5a0e89b9f99d <unknown>
#11 0x5a0e89c3867b <unknown>
#12 0x5a0e89c37969 <unknown>
#13 0x5a0e89be25cf <unknown>
#14 0x5a0e89be3391 <unknown>
#15 0x5a0e8a16004b <unknown>
#16 0x5a0e8a16300d <unknown>
#17 0x5a0e8a14c808 <unknown>
#18 0x5a0e8a163ba0 <unknown>
#19 0x5a0e8a133280 <unknown>
#20 0x5a0e8a187db8 <unknown>
#21 0x5a0e8a187f88 <unknown>
#22 0x5a0e8a1995de <unknown>
#23 0x7e26f33d5ac3 <unknown>

Tempo de execução para http://www.ourizona.pr.gov.br/: 35.69s
Erro: URL inválida recebida: nan
Progresso: 10/65
Tempo de execução para https://saojoaodocaiua.eloweb.net/portaltransparencia/1/: 12.27s
Tempo de execução para http://187.95.103.124:7474/transparencia/: 36.45s
Progresso: 20/65
Tempo de execução para https://santafe.oxy.elotech.com.br/portaltransparencia/1/: 4.0s
Tempo de execução para https://pmsjorge.pr.gov.br/: 13.54s
Tempo de execução para https://www.jacarezinho.pr.gov.br/: 7.65s
Tempo de execução para https://jardimolinda.eloweb.net/portaltransparencia/1/: 10.9s
WebDriver error for http://www.rosariodoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5939925bfb6a <unknown>
#1 0x593991fc1265 <unknown>
#2 0x593991fb809f <unknown>
#3 0x593991fa8e31 <unknown>
#4 0x593991faac2c <unknown>
#5 0x593991fa932a <unknown>
#6 0x593991fa8b50 <unknown>
#7 0x593991fa8804 <unknown>
#8 0x593991fa654b <unknown>
#9 0x593991fa6d90 <unknown>
#10 0x593991fc499d <unknown>
#11 0x59399205d67b <unknown>
#12 0x59399205c969 <unknown>
#13 0x5939920075cf <unknown>
#14 0x593992008391 <unknown>
#15 0x59399258504b <unknown>
#16 0x59399258800d <unknown>
#17 0x593992571808 <unknown>
#18 0x593992588ba0 <unknown>
#19 0x593992558280 <unknown>
#20 0x5939925acdb8 <unknown>
#21 0x5939925acf88 <unknown>
#22 0x5939925be5de <unknown>
#23 0x79b0664f9ac3 <unknown>

Tempo de execução para http://www.rosariodoivai.pr.gov.br/: 35.5s
Tempo de execução para https://entreriosdooeste.atende.net/transparencia/: 15.13s
WebDriver error for http://itaunadosul.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x55a157224b6a <unknown>
#1 0x55a156c26265 <unknown>
#2 0x55a156c1d09f <unknown>
#3 0x55a156c0de31 <unknown>
#4 0x55a156c0fc2c <unknown>
#5 0x55a156c0e32a <unknown>
#6 0x55a156c0db50 <unknown>
#7 0x55a156c0d804 <unknown>
#8 0x55a156c0b54b <unknown>
#9 0x55a156c0bd90 <unknown>
#10 0x55a156c2999d <unknown>
#11 0x55a156cc267b <unknown>
#12 0x55a156cc1969 <unknown>
#13 0x55a156c6c5cf <unknown>
#14 0x55a156c6d391 <unknown>
#15 0x55a1571ea04b <unknown>
#16 0x55a1571ed00d <unknown>
#17 0x55a1571d6808 <unknown>
#18 0x55a1571edba0 <unknown>
#19 0x55a1571bd280 <unknown>
#20 0x55a157211db8 <unknown>
#21 0x55a157211f88 <unknown>
#22 0x55a1572235de <unknown>
#23 0x7d4bd0199ac3 <unknown>

Tempo de execução para http://itaunadosul.pr.gov.br/: 32.82s
Tempo de execução para https://amoreira.oxy.elotech.com.br/portaltransparencia/1/: 3.5s
General error for https://cafearapr.equiplano.com.br:7473/transparencia/: HTTPConnectionPool(host='localhost', port=57745): Read timed out. (read timeout=120)
Tempo de execução para https://cafearapr.equiplano.com.br:7473/transparencia/: 126.84s
WebDriver error for https://www.iguatu.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5793172e2b6a <unknown>
#1 0x579316ce4265 <unknown>
#2 0x579316cdb09f <unknown>
#3 0x579316ccbe31 <unknown>
#4 0x579316ccdc2c <unknown>
#5 0x579316ccc32a <unknown>
#6 0x579316ccbb50 <unknown>
#7 0x579316ccb804 <unknown>
#8 0x579316cc954b <unknown>
#9 0x579316cc9d90 <unknown>
#10 0x579316ce799d <unknown>
#11 0x579316d8067b <unknown>
#12 0x579316d7f969 <unknown>
#13 0x579316d2a5cf <unknown>
#14 0x579316d2b391 <unknown>
#15 0x5793172a804b <unknown>
#16 0x5793172ab00d <unknown>
#17 0x579317294808 <unknown>
#18 0x5793172abba0 <unknown>
#19 0x57931727b280 <unknown>
#20 0x5793172cfdb8 <unknown>
#21 0x5793172cff88 <unknown>
#22 0x5793172e15de <unknown>
#23 0x7d973209bac3 <unknown>

Tempo de execução para https://www.iguatu.pr.gov.br/: 96.42s
Tempo de execução para https://siqueiracampos.pr.gov.br/portal-da-transparencia: 13.44s
General error for https://tijucasdosulpr.equiplano.com.br:7025/transparencia/: HTTPConnectionPool(host='localhost', port=59885): Read timed out. (read timeout=120)
Tempo de execução para https://tijucasdosulpr.equiplano.com.br:7025/transparencia/: 123.3s
Tempo de execução para https://quartocentenario.eloweb.net/portaltransparencia/1/: 9.05s
Tempo de execução para https://bomjesusdosul.pr.gov.br/: 19.56s
General error for https://www.sjp.pr.gov.br/: HTTPConnectionPool(host='localhost', port=33995): Read timed out. (read timeout=120)
Tempo de execução para https://www.sjp.pr.gov.br/: 121.48s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=57745): Read timed out. (read timeout=120)")': /session/0031b6798e0f8a365d6b4a59360228ed
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=59885): Read timed out. (read timeout=120)")': /session/3ed16c1741a57ddd7bf86dcd3d619394

Tempo de execução para http://www.virmond.pr.gov.br/index.php: 110.6s
Tempo de execução para https://mambore.atende.net/: 27.95s
Tempo de execução para https://clevelandia.atende.net/transparencia/: 13.38s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=33995): Read timed out. (read timeout=120)")': /session/79365005879a4fc894d29596adb59423

Tempo de execução para https://mariahelena.eloweb.net/portaltransparencia/1/: 7.68s
Tempo de execução para https://porecatu.pr.gov.br/#: 8.2s
Progresso: 40/65
Tempo de execução para https://itambaraca.eloweb.net/portaltransparencia/1/			: 12.05s
Tempo de execução para https://www.ramilandia.pr.gov.br/site/: 6.72s
WebDriver error for https://wenceslaubraz.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x55d1e8a5db6a <unknown>
#1 0x55d1e845f265 <unknown>
#2 0x55d1e845609f <unknown>
#3 0x55d1e8446e31 <unknown>
#4 0x55d1e8448c2c <unknown>
#5 0x55d1e844732a <unknown>
#6 0x55d1e8446b50 <unknown>
#7 0x55d1e8446804 <unknown>
#8 0x55d1e844454b <unknown>
#9 0x55d1e8444d90 <unknown>
#10 0x55d1e846299d <unknown>
#11 0x55d1e84fb67b <unknown>
#12 0x55d1e84fa969 <unknown>
#13 0x55d1e84a55cf <unknown>
#14 0x55d1e84a6391 <unknown>
#15 0x55d1e8a2304b <unknown>
#16 0x55d1e8a2600d <unknown>
#17 0x55d1e8a0f808 <unknown>
#18 0x55d1e8a26ba0 <unknown>
#19 0x55d1e89f6280 <unknown>
#20 0x55d1e8a4adb8 <unknown>
#21 0x55d1e8a4af88 <unknown>
#22 0x55d1e8a5c5de <unknown>
#23 0x7d3488935ac3 <unknown>

Tempo de execução para https://wenceslaubraz.pr.gov.br/: 66.34s
Tempo de execução para https://fenix.oxy.elotech.com.br/portaltransparencia/1/: 4.37s
Tempo de execução para https://www.ipora.pr.gov.br/: 13.89s
Tempo de execução para https://catanduvas.pr.gov.br/: 23.84s
Progresso: 30/65
Tempo de execução para https://paranavai.atende.net/transparencia/: 17.27s
WebDriver error for https://patobranco.govbr.cloud/pronimtb/index.html: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x55e907b28b6a <unknown>
#1 0x55e90752a265 <unknown>
#2 0x55e90752109f <unknown>
#3 0x55e907511e31 <unknown>
#4 0x55e907513c2c <unknown>
#5 0x55e90751232a <unknown>
#6 0x55e907511b50 <unknown>
#7 0x55e907511804 <unknown>
#8 0x55e90750f54b <unknown>
#9 0x55e90750fd90 <unknown>
#10 0x55e90752d99d <unknown>
#11 0x55e9075c667b <unknown>
#12 0x55e9075c5969 <unknown>
#13 0x55e9075705cf <unknown>
#14 0x55e907571391 <unknown>
#15 0x55e907aee04b <unknown>
#16 0x55e907af100d <unknown>
#17 0x55e907ada808 <unknown>
#18 0x55e907af1ba0 <unknown>
#19 0x55e907ac1280 <unknown>
#20 0x55e907b15db8 <unknown>
#21 0x55e907b15f88 <unknown>
#22 0x55e907b275de <unknown>
#23 0x787ab2bbdac3 <unknown>

Tempo de execução para https://patobranco.govbr.cloud/pronimtb/index.html: 4.52s
General error for https://www.maringa.pr.gov.br/: HTTPConnectionPool(host='localhost', port=49837): Read timed out. (read timeout=120)
Tempo de execução para https://www.maringa.pr.gov.br/: 122.19s
Tempo de execução para https://corumbatai.eloweb.net/portaltransparencia/1/: 12.59s
WebDriver error for https://www.manoelribas.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x557a3717db6a <unknown>
#1 0x557a36b7f265 <unknown>
#2 0x557a36b7609f <unknown>
#3 0x557a36b66e31 <unknown>
#4 0x557a36b68c2c <unknown>
#5 0x557a36b6732a <unknown>
#6 0x557a36b66b50 <unknown>
#7 0x557a36b66804 <unknown>
#8 0x557a36b6454b <unknown>
#9 0x557a36b64d90 <unknown>
#10 0x557a36b8299d <unknown>
#11 0x557a36c1b67b <unknown>
#12 0x557a36c1a969 <unknown>
#13 0x557a36bc55cf <unknown>
#14 0x557a36bc6391 <unknown>
#15 0x557a3714304b <unknown>
#16 0x557a3714600d <unknown>
#17 0x557a3712f808 <unknown>
#18 0x557a37146ba0 <unknown>
#19 0x557a37116280 <unknown>
#20 0x557a3716adb8 <unknown>
#21 0x557a3716af88 <unknown>
#22 0x557a3717c5de <unknown>
#23 0x7d86ffa13ac3 <unknown>

Tempo de execução para https://www.manoelribas.pr.gov.br/: 44.26s
General error for https://franciscobeltraopr.equiplano.com.br:7035/transparencia/: HTTPConnectionPool(host='localhost', port=43369): Read timed out. (read timeout=120)
Tempo de execução para https://franciscobeltraopr.equiplano.com.br:7035/transparencia/: 123.39s
Tempo de execução para https://mandaguari.oxy.elotech.com.br/portaltransparencia/1/: 3.88s
Tempo de execução para https://www.brasilandiadosul.pr.gov.br/index.php#: 122.99s
Progresso: 50/65

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=49837): Read timed out. (read timeout=120)")': /session/efa9a4f96ff2b6e9c04f5788c7ee8bb7

WebDriver error for https://candidodeabreu.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x59a6c8c14b6a <unknown>
#1 0x59a6c8616265 <unknown>
#2 0x59a6c860d09f <unknown>
#3 0x59a6c85fde31 <unknown>
#4 0x59a6c85ffc2c <unknown>
#5 0x59a6c85fe32a <unknown>
#6 0x59a6c85fdb50 <unknown>
#7 0x59a6c85fd804 <unknown>
#8 0x59a6c85fb54b <unknown>
#9 0x59a6c85fbd90 <unknown>
#10 0x59a6c861999d <unknown>
#11 0x59a6c86b267b <unknown>
#12 0x59a6c86b1969 <unknown>
#13 0x59a6c865c5cf <unknown>
#14 0x59a6c865d391 <unknown>
#15 0x59a6c8bda04b <unknown>
#16 0x59a6c8bdd00d <unknown>
#17 0x59a6c8bc6808 <unknown>
#18 0x59a6c8bddba0 <unknown>
#19 0x59a6c8bad280 <unknown>
#20 0x59a6c8c01db8 <unknown>
#21 0x59a6c8c01f88 <unknown>
#22 0x59a6c8c135de <unknown>
#23 0x7c7d0e6c2ac3 <unknown>

Tempo de execução para https://candidodeabreu.pr.gov.br/: 79.29s
Tempo de execução para https://contenda.oxy.elotech.com.br/portaltransparencia/1/: 2.4s
WebDriver error for http://200.24.78.254:7474/transparencia/: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5cd8fd021b6a <unknown>
#1 0x5cd8fca23265 <unknown>
#2 0x5cd8fca1a09f <unknown>
#3 0x5cd8fca0ae31 <unknown>
#4 0x5cd8fca0cc2c <unknown>
#5 0x5cd8fca0b32a <unknown>
#6 0x5cd8fca0ab50 <unknown>
#7 0x5cd8fca0a804 <unknown>
#8 0x5cd8fca0854b <unknown>
#9 0x5cd8fca08d90 <unknown>
#10 0x5cd8fca2699d <unknown>
#11 0x5cd8fcabf67b <unknown>
#12 0x5cd8fcabe969 <unknown>
#13 0x5cd8fca695cf <unknown>
#14 0x5cd8fca6a391 <unknown>
#15 0x5cd8fcfe704b <unknown>
#16 0x5cd8fcfea00d <unknown>
#17 0x5cd8fcfd3808 <unknown>
#18 0x5cd8fcfeaba0 <unknown>
#19 0x5cd8fcfba280 <unknown>
#20 0x5cd8fd00edb8 <unknown>
#21 0x5cd8fd00ef88 <unknown>
#22 0x5cd8fd0205de <unknown>
#23 0x7a5c0b591ac3 <unknown>

Tempo de execução para http://200.24.78.254:7474/transparencia/: 2.71s
Progresso: 60/65

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=43369): Read timed out. (read timeout=120)")': /session/51108194f405e6c38fae99a9f416c962

General error for http://45.228.123.128:8090/portaltransparencia/1	: HTTPConnectionPool(host='localhost', port=40823): Read timed out. (read timeout=120)
Tempo de execução para http://45.228.123.128:8090/portaltransparencia/1	: 122.64s
Tempo de execução para https://novaolimpia.eloweb.net/portaltransparencia/1/: 8.79s
Tempo de execução para https://www.goioere.pr.gov.br/site/: 3.98s
Tempo de execução para https://jandaiadosul.oxy.elotech.com.br/portaltransparencia/1/: 2.99s
Tempo de execução para https://www.salgadofilho.pr.gov.br/: 4.23s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=40823): Read timed out. (read timeout=120)")': /session/cf11750bd87bb3c177f6ccfdb175ca73
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=39165): Read timed out. (read timeout=120)")': /session/344f3f723212526a5ce540d6bb6a8c77/url

Tempo de execução para https://transparencia.e-publica.net/epublica-portal/#/quatro_pontes/portal?entidade=2026: 251.48s

In [ ]:
q664_4 = q_selenium_paralelo(q,tp,pv,pn,df_link, 195, 260, threads=4)

Tempo de execução para https://transparencia.betha.cloud/#/9SlBc07aXpHeQj7dCV0R6A==: 14.53s
Tempo de execução para https://altamiradoparana.oxy.elotech.com.br/portaltransparencia/1/: 12.0s
Tempo de execução para https://transparencia.betha.cloud/#/q5mtUmu2n7J91WloUtIiFQ==: 4.29s
Tempo de execução para http://www.saltodolontra.pr.gov.br: 34.7s
Tempo de execução para http://transparencia.pibema.pr.gov.br:8087/portaltransparencia/1/publicacoes/1097/295: 35.5s
Tempo de execução para https://castro.atende.net/transparencia/grupo/controle-interno#conteudo: 16.81s
WebDriver error for https://www.lindoeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5a06472c3b6a <unknown>
#1 0x5a0646cc5265 <unknown>
#2 0x5a0646cbc09f <unknown>
#3 0x5a0646cace31 <unknown>
#4 0x5a0646caec2c <unknown>
#5 0x5a0646cad32a <unknown>
#6 0x5a0646cacb50 <unknown>
#7 0x5a0646cac804 <unknown>
#8 0x5a0646caa54b <unknown>
#9 0x5a0646caad90 <unknown>
#10 0x5a0646cc899d <unknown>
#11 0x5a0646d6167b <unknown>
#12 0x5a0646d60969 <unknown>
#13 0x5a0646d0b5cf <unknown>
#14 0x5a0646d0c391 <unknown>
#15 0x5a064728904b <unknown>
#16 0x5a064728c00d <unknown>
#17 0x5a0647275808 <unknown>
#18 0x5a064728cba0 <unknown>
#19 0x5a064725c280 <unknown>
#20 0x5a06472b0db8 <unknown>
#21 0x5a06472b0f88 <unknown>
#22 0x5a06472c25de <unknown>
#23 0x78ecd2661ac3 <unknown>

Tempo de execução para https://www.lindoeste.pr.gov.br/: 55.61s
Tempo de execução para https://matelandia.oxy.elotech.com.br/portaltransparencia/1/publicacoes/1119/378: 3.52s
Tempo de execução para https://pinhais.atende.net/ : 25.61s
WebDriver error for http://www.guamiranga.pr.gov.br/#: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x561a3946eb6a <unknown>
#1 0x561a38e70265 <unknown>
#2 0x561a38e6709f <unknown>
#3 0x561a38e57e31 <unknown>
#4 0x561a38e59c2c <unknown>
#5 0x561a38e5832a <unknown>
#6 0x561a38e57b50 <unknown>
#7 0x561a38e57804 <unknown>
#8 0x561a38e5554b <unknown>
#9 0x561a38e55d90 <unknown>
#10 0x561a38e7399d <unknown>
#11 0x561a38f0c67b <unknown>
#12 0x561a38f0b969 <unknown>
#13 0x561a38eb65cf <unknown>
#14 0x561a38eb7391 <unknown>
#15 0x561a3943404b <unknown>
#16 0x561a3943700d <unknown>
#17 0x561a39420808 <unknown>
#18 0x561a39437ba0 <unknown>
#19 0x561a39407280 <unknown>
#20 0x561a3945bdb8 <unknown>
#21 0x561a3945bf88 <unknown>
#22 0x561a3946d5de <unknown>
#23 0x7c8383968ac3 <unknown>

Tempo de execução para http://www.guamiranga.pr.gov.br/#: 35.11s
Tempo de execução para https://marilena.eloweb.net/portaltransparencia/1/: 12.62s
Tempo de execução para https://cidadegaucha.pr.gov.br/: 14.57s
Tempo de execução para https://transparencia.betha.cloud/#/psLceViNSNqXqEh4NmI-9Q==: 2.21s
WebDriver error for https://www.munhozdemello.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5831e3083b6a <unknown>
#1 0x5831e2a85265 <unknown>
#2 0x5831e2a7c09f <unknown>
#3 0x5831e2a6ce31 <unknown>
#4 0x5831e2a6ec2c <unknown>
#5 0x5831e2a6d32a <unknown>
#6 0x5831e2a6cb50 <unknown>
#7 0x5831e2a6c804 <unknown>
#8 0x5831e2a6a54b <unknown>
#9 0x5831e2a6ad90 <unknown>
#10 0x5831e2a8899d <unknown>
#11 0x5831e2b2167b <unknown>
#12 0x5831e2b20969 <unknown>
#13 0x5831e2acb5cf <unknown>
#14 0x5831e2acc391 <unknown>
#15 0x5831e304904b <unknown>
#16 0x5831e304c00d <unknown>
#17 0x5831e3035808 <unknown>
#18 0x5831e304cba0 <unknown>
#19 0x5831e301c280 <unknown>
#20 0x5831e3070db8 <unknown>
#21 0x5831e3070f88 <unknown>
#22 0x5831e30825de <unknown>
#23 0x79f6a58e3ac3 <unknown>

Tempo de execução para https://www.munhozdemello.pr.gov.br/: 86.06s
Progresso: 10/65
Tempo de execução para https://www.indianopolis.pr.gov.br/: 31.93s
Tempo de execução para https://www.saomateusdosul.pr.gov.br/: 40.83s
Tempo de execução para https://planalto.pr.gov.br/portal-transparencia: 4.42s
Tempo de execução para https://transparencia.betha.cloud/#/ZAA6t2_GdA4J1ZCwMJsJgw==: 2.43s
Tempo de execução para https://www.portoamazonas.pr.gov.br/: 3.94s
General error for https://novalaranjeiraspr.equiplano.com.br:7076/transparencia/menuCustomizavel?idAcao=50014: HTTPConnectionPool(host='localhost', port=59833): Read timed out. (read timeout=120)
Tempo de execução para https://novalaranjeiraspr.equiplano.com.br:7076/transparencia/menuCustomizavel?idAcao=50014: 125.57s
Tempo de execução para https://acessoainformacao.tamboara.pr.gov.br/: 18.17s
Tempo de execução para https://www.candoi.pr.gov.br/: 4.26s
Tempo de execução para https://www.jaboti.pr.gov.br/: 28.27s
Tempo de execução para https://transparencia.betha.cloud/#/H5O-RxfRurTWXzQsfU63HQ==: 1.56s
Progresso: 30/65
Tempo de execução para https://www.boaesperancadoiguacu.pr.gov.br/: 27.05s
Tempo de execução para https://portal.londrina.pr.gov.br/transparencia: 14.32s
Tempo de execução para https://laranjal.pr.gov.br/ : 38.57s
WebDriver error for http://www.terrarica.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5c3f03664b6a <unknown>
#1 0x5c3f03066265 <unknown>
#2 0x5c3f0305d09f <unknown>
#3 0x5c3f0304de31 <unknown>
#4 0x5c3f0304fc2c <unknown>
#5 0x5c3f0304e32a <unknown>
#6 0x5c3f0304db50 <unknown>
#7 0x5c3f0304d804 <unknown>
#8 0x5c3f0304b54b <unknown>
#9 0x5c3f0304bd90 <unknown>
#10 0x5c3f0306999d <unknown>
#11 0x5c3f0310267b <unknown>
#12 0x5c3f03101969 <unknown>
#13 0x5c3f030ac5cf <unknown>
#14 0x5c3f030ad391 <unknown>
#15 0x5c3f0362a04b <unknown>
#16 0x5c3f0362d00d <unknown>
#17 0x5c3f03616808 <unknown>
#18 0x5c3f0362dba0 <unknown>
#19 0x5c3f035fd280 <unknown>
#20 0x5c3f03651db8 <unknown>
#21 0x5c3f03651f88 <unknown>
#22 0x5c3f036635de <unknown>
#23 0x7c7d08ae8ac3 <unknown>

Tempo de execução para http://www.terrarica.pr.gov.br/: 36.02s
Tempo de execução para https://doisvizinhos.pr.gov.br: 13.51s
Tempo de execução para https://santacruzdemontecastelo.eloweb.net/portaltransparencia/1/: 8.65s
WebDriver error for https://transparencia.ivaipora.pr.gov.br/portaltransparencia/1/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x59a7da509b6a <unknown>
#1 0x59a7d9f0b265 <unknown>
#2 0x59a7d9f0209f <unknown>
#3 0x59a7d9ef2e31 <unknown>
#4 0x59a7d9ef4c2c <unknown>
#5 0x59a7d9ef332a <unknown>
#6 0x59a7d9ef2b50 <unknown>
#7 0x59a7d9ef2804 <unknown>
#8 0x59a7d9ef054b <unknown>
#9 0x59a7d9ef0d90 <unknown>
#10 0x59a7d9f0e99d <unknown>
#11 0x59a7d9fa767b <unknown>
#12 0x59a7d9fa6969 <unknown>
#13 0x59a7d9f515cf <unknown>
#14 0x59a7d9f52391 <unknown>
#15 0x59a7da4cf04b <unknown>
#16 0x59a7da4d200d <unknown>
#17 0x59a7da4bb808 <unknown>
#18 0x59a7da4d2ba0 <unknown>
#19 0x59a7da4a2280 <unknown>
#20 0x59a7da4f6db8 <unknown>
#21 0x59a7da4f6f88 <unknown>
#22 0x59a7da5085de <unknown>
#23 0x7f82158a3ac3 <unknown>

Tempo de execução para https://transparencia.ivaipora.pr.gov.br/portaltransparencia/1/: 71.18s
Tempo de execução para https://amapora.eloweb.net/portaltransparencia/1/: 4.63s
Tempo de execução para https://www.mercedes.pr.gov.br/index.php: 18.23s
Progresso: 40/65
Tempo de execução para https://terraroxa.atende.net/cidadao: 33.98s
Tempo de execução para https://www.capanema.pr.gov.br/: 10.62s
Tempo de execução para https://www.sarandi.pr.gov.br/web/: 29.55s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=51279): Read timed out. (read timeout=120)")': /session/de3750c18acefbd7fb4e0ad8246baa05/url

Tempo de execução para http://transparencia.serranopolis.pr.gov.br/portaltransparencia/1/: 13.21s
Tempo de execução para https://www.japura.pr.gov.br/pagina/81_Radar-da-Transparencia.html: 9.9s
Tempo de execução para https://santaisabeldoivai.eloweb.net/portaltransparencia/1/: 11.38s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=46801): Read timed out. (read timeout=120)")': /session/83c575e9a1d5697898b2006ea4a319f9/url

Tempo de execução para https://arapongas.atende.net/transparencia  : 233.1s
Tempo de execução para https://colombo.atende.net/transparencia/: 14.9s
Progresso: 50/65
Tempo de execução para https://www.stitaipu.pr.gov.br/portal-da-transparencia.html: 298.45s
Progresso: 20/65
Tempo de execução para https://espigaoaltodoiguacu.pr.gov.br/: 20.49s
Tempo de execução para https://campomourao.atende.net/: 37.7s
Tempo de execução para https://luiziana.eloweb.net/portaltransparencia/1/: 21.26s
Tempo de execução para https://servicos.umuarama.pr.gov.br/portaltransparencia/1/: 21.06s
Tempo de execução para https://www.generalcarneiro.pr.gov.br/portal-da-transparencia: 102.76s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=37713): Read timed out. (read timeout=120)")': /session/ac12588dc8bfb1a564bf3ec1b74448e6/url

WebDriver error for https://www.ampere.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=147.0.7727.55)
Stacktrace:
#0 0x5c7f87120b6a <unknown>
#1 0x5c7f86b22265 <unknown>
#2 0x5c7f86b1909f <unknown>
#3 0x5c7f86b09e31 <unknown>
#4 0x5c7f86b0bc2c <unknown>
#5 0x5c7f86b0a32a <unknown>
#6 0x5c7f86b09b50 <unknown>
#7 0x5c7f86b09804 <unknown>
#8 0x5c7f86b0754b <unknown>
#9 0x5c7f86b07d90 <unknown>
#10 0x5c7f86b2599d <unknown>
#11 0x5c7f86bbe67b <unknown>
#12 0x5c7f86bbd969 <unknown>
#13 0x5c7f86b685cf <unknown>
#14 0x5c7f86b69391 <unknown>
#15 0x5c7f870e604b <unknown>
#16 0x5c7f870e900d <unknown>
#17 0x5c7f870d2808 <unknown>
#18 0x5c7f870e9ba0 <unknown>
#19 0x5c7f870b9280 <unknown>
#20 0x5c7f8710ddb8 <unknown>
#21 0x5c7f8710df88 <unknown>
#22 0x5c7f8711f5de <unknown>
#23 0x7d923f61dac3 <unknown>

Tempo de execução para https://www.ampere.pr.gov.br/: 67.78s
Progresso: 60/65
Tempo de execução para https://www.conselheiromairinck.pr.gov.br/: 248.9s
Tempo de execução para https://novasantarosa.atende.net/cidadao/acesso-informacao/banner/11: 16.5s
Tempo de execução para  https://www.rolandia.pr.gov.br/: 31.82s
General error for http://177.185.208.166:8080/portaltransparencia/1/: HTTPConnectionPool(host='localhost', port=34361): Read timed out. (read timeout=120)
Tempo de execução para http://177.185.208.166:8080/portaltransparencia/1/: 127.77s
Tempo de execução para https://portovitoria.pr.gov.br/: 122.31s
General error for http://200.195.136.147:7476/pronimtb/index.html: HTTPConnectionPool(host='localhost', port=42021): Read timed out. (read timeout=120)
Tempo de execução para http://200.195.136.147:7476/pronimtb/index.html: 127.67s
Tempo de execução para https://www.ivate.pr.gov.br/: 125.72s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='localhost', port=34361): Read timed out. (read timeout=120)")': /session/724a650201fc058b6e2f5c6eeeaa25b3

In [ ]:
q664_5 = q_selenium_paralelo(q,tp,pv,pn,df_link, 260, 325, threads=4)

In [ ]:
q664_6 = q_selenium_paralelo(q,tp,pv,pn,df_link, 325, None , threads=4)

In [ ]:
q_selenium_664 = pd.concat([q664_1,
                            q664_2,
                            q664_3,
                            q664_4,
                            q664_5,
                            q664_6
                          ],ignore_index=True)
q_selenium_664
q_selenium_664.to_csv( 'q_selenium_664.csv', index=False)

In [ ]:
q_selenium_664.head()

In [ ]:
p = ["radardatransparencia"]
v = q_selenium_664.copy()

v["verificado"] = v.elemento_final.apply(lambda x: pd.Series(verifica_lista(x, p)).drop_duplicates().tolist())
v

In [ ]:
v

In [ ]:
elemento_localizado = v[v["verificado"].apply(lambda x: x != [])]
elemento_localizado.shape

In [ ]:
elemento_localizado[elemento_localizado["html_elemento_interacao_1"].apply(lambda x: x != [])]

In [ ]:
elemento_ausente_interacao = v[v["verificado"].apply(lambda x: x == []) & v['html_elemento_interacao_1'].apply(lambda x: x != []) & v['html_elemento_interacao_1'].notna()]
elemento_ausente_interacao.shape

In [ ]:
elemento_ausente_interacao

In [ ]:
indices_para_excluir = elemento_localizado.index.union(elemento_ausente_interacao.index)
elemento_ausente = v.drop(indices_para_excluir)
elemento_ausente.shape

In [ ]:
display(elemento_localizado.duracao_segundos.describe())
display(elemento_localizado.duracao_segundos.sum())
display(elemento_localizado.shape)

display(elemento_ausente_interacao.duracao_segundos.describe())
display(elemento_ausente_interacao.duracao_segundos.sum())
display(elemento_ausente_interacao.shape)

display(elemento_ausente.duracao_segundos.describe())
display(elemento_ausente.duracao_segundos.sum())
display(elemento_ausente.shape)

display(elemento_ausente.error_cod.value_counts())

In [ ]:
q_selenium_664.query("error_cod == 'WebDriverException' or error_cod =='URL_BLOCKED' or error_cod == 'ReadTimeoutError'")

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
3,1270,664,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True,<html><head><title>403 Forbidden</title></head...,None,None,URL_BLOCKED,URL bloqueada,[],[],8.12
4,2949,664,Disponibilidade,https://www.marialva.pr.gov.br/,True,None,None,None,WebDriverException,Message: unknown error: net::ERR_NAME_NOT_RESO...,[],[],52.87
7,2888,664,Disponibilidade,https://mandirituba.pr.gov.br/portal-da-transp...,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",None,None,URL_BLOCKED,URL bloqueada,[],[],4.54
8,4910,664,Disponibilidade,https://saotomepr.equiplano.com.br:7430/transp...,False,None,None,None,ReadTimeoutError,"HTTPConnectionPool(host='localhost', port=4527...",[],[],121.88
15,1754,664,Disponibilidade,https://fazendariogrande.pr.gov.br/transparencia,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",None,None,URL_BLOCKED,URL bloqueada,[],[],1.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,34,664,Disponibilidade,https://transparencia.betha.cloud/#/k7LmvDe0yL...,True,"<html><head><meta http-equiv=""Content-Type"" co...",None,None,URL_BLOCKED,URL bloqueada,[],[],3.26
379,4067,664,Disponibilidade,https://quedasdoiguacupr.equiplano.com.br:7006...,True,None,None,None,ReadTimeoutError,"HTTPConnectionPool(host='localhost', port=5910...",[],[],122.02
388,4168,664,Disponibilidade,http://rcpnetworks.com.br:8091/portaltranspare...,True,None,None,None,WebDriverException,Message: unknown error: net::ERR_NAME_NOT_RESO...,[],[],2.36
394,5196,664,Disponibilidade,https://telemacoborba.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",None,None,URL_BLOCKED,URL bloqueada,[],[],2.67
396,3380,664,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,<html><head><title>403 Forbidden</title></head...,None,None,URL_BLOCKED,URL bloqueada,[],[],4.09

In [ ]:
retry = q_selenium_664.query("error_cod == 'WebDriverException' or error_cod =='URL_BLOCKED' or error_cod == 'ReadTimeoutError'").copy()

In [ ]:
q = 664
tp = "link"
pv = ["radardatransparencia.atricon"]
pn = ["radar"]

In [ ]:
df_retry = q_selenium_paralelo(q,tp,pv,pn, retry, 0, None , threads=4)
df_retry

Tempo de execução para https://transparencia.betha.cloud/#/XsTYmnrmpsOvZ8_9fe1GYw==: 13.28s
Tempo de execução para https://cianorte.oxy.elotech.com.br/portaltransparencia/1/: 15.95s
Tempo de execução para https://mandirituba.pr.gov.br/portal-da-transparencia/informacoes-gerais/radar-da-transparenciapublica: 16.72s
Tempo de execução para https://fazendariogrande.pr.gov.br/transparencia: 18.13s
Tempo de execução para https://patobragado.atende.net/subportal/portal-da-transparencia: 18.73s
Tempo de execução para https://transparencia.betha.cloud/#/cFVgtYEEPVrO7Xy4RZ_lXg==: 5.24s
WebDriver error for http://www.saopedrodoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5cafc0e38a6a <unknown>
#1 0x5cafc0847ab5 <unknown>
#2 0x5cafc083e9bf <unknown>
#3 0x5cafc082f6d1 <unknown>
#4 0x5cafc08314cc <unknown>
#5 0x5cafc082fbca <unknown>
#6 0x5cafc082f3f0 <unknown>
#7 0x5cafc082f0a4 <unknown>
#8 0x5cafc082cdeb <unknown>
#9 0x5cafc082d630 <unknown>
#10 0x5cafc084b1ed <unknown>
#11 0x5cafc08e34bb <unknown>
#12 0x5cafc08e27b6 <unknown>
#13 0x5cafc088dcbf <unknown>
#14 0x5cafc088ea81 <unknown>
#15 0x5cafc0dfea64 <unknown>
#16 0x5cafc0e01951 <unknown>
#17 0x5cafc0deb21e <unknown>
#18 0x5cafc0e0251e <unknown>
#19 0x5cafc0dd1be0 <unknown>
#20 0x5cafc0e259b8 <unknown>
#21 0x5cafc0e25b88 <unknown>
#22 0x5cafc0e374de <unknown>
#23 0x7ce3f4276ac3 <unknown>

Tempo de execução para http://www.saopedrodoivai.pr.gov.br/: 48.18s
Tempo de execução para https://campomagro.pr.gov.br/: 61.9s
Tempo de execução para https://www.bituruna.pr.gov.br//portalTransparencia/: 4.12s
WebDriver error for http://california.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5a1c78118a6a <unknown>
#1 0x5a1c77b27ab5 <unknown>
#2 0x5a1c77b1e9bf <unknown>
#3 0x5a1c77b0f6d1 <unknown>
#4 0x5a1c77b114cc <unknown>
#5 0x5a1c77b0fbca <unknown>
#6 0x5a1c77b0f3f0 <unknown>
#7 0x5a1c77b0f0a4 <unknown>
#8 0x5a1c77b0cdeb <unknown>
#9 0x5a1c77b0d630 <unknown>
#10 0x5a1c77b2b1ed <unknown>
#11 0x5a1c77bc34bb <unknown>
#12 0x5a1c77bc27b6 <unknown>
#13 0x5a1c77b6dcbf <unknown>
#14 0x5a1c77b6ea81 <unknown>
#15 0x5a1c780dea64 <unknown>
#16 0x5a1c780e1951 <unknown>
#17 0x5a1c780cb21e <unknown>
#18 0x5a1c780e251e <unknown>
#19 0x5a1c780b1be0 <unknown>
#20 0x5a1c781059b8 <unknown>
#21 0x5a1c78105b88 <unknown>
#22 0x5a1c781174de <unknown>
#23 0x7c6d1d5d5ac3 <unknown>

Tempo de execução para http://california.pr.gov.br/: 41.43s
Tempo de execução para https://transparencia.betha.cloud/#/r2cpj2e4mrz8xjHlykU8bg==: 10.94s
WebDriver error for https://www.marialva.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5a0dbdf20a6a <unknown>
#1 0x5a0dbd92fab5 <unknown>
#2 0x5a0dbd9269bf <unknown>
#3 0x5a0dbd9176d1 <unknown>
#4 0x5a0dbd9194cc <unknown>
#5 0x5a0dbd917bca <unknown>
#6 0x5a0dbd9173f0 <unknown>
#7 0x5a0dbd9170a4 <unknown>
#8 0x5a0dbd914deb <unknown>
#9 0x5a0dbd915630 <unknown>
#10 0x5a0dbd9331ed <unknown>
#11 0x5a0dbd9cb4bb <unknown>
#12 0x5a0dbd9ca7b6 <unknown>
#13 0x5a0dbd975cbf <unknown>
#14 0x5a0dbd976a81 <unknown>
#15 0x5a0dbdee6a64 <unknown>
#16 0x5a0dbdee9951 <unknown>
#17 0x5a0dbded321e <unknown>
#18 0x5a0dbdeea51e <unknown>
#19 0x5a0dbdeb9be0 <unknown>
#20 0x5a0dbdf0d9b8 <unknown>
#21 0x5a0dbdf0db88 <unknown>
#22 0x5a0dbdf1f4de <unknown>
#23 0x7e71f986bac3 <unknown>

Tempo de execução para https://www.marialva.pr.gov.br/: 94.72s
Tempo de execução para https://transparencia.betha.cloud/#/QZgNvTT4qFk80u10mrdMPg==/consulta/75669: 2.9s
WebDriver error for https://presidentecastelobranco.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x58694cb3aa6a <unknown>
#1 0x58694c549ab5 <unknown>
#2 0x58694c5409bf <unknown>
#3 0x58694c5316d1 <unknown>
#4 0x58694c5334cc <unknown>
#5 0x58694c531bca <unknown>
#6 0x58694c5313f0 <unknown>
#7 0x58694c5310a4 <unknown>
#8 0x58694c52edeb <unknown>
#9 0x58694c52f630 <unknown>
#10 0x58694c54d1ed <unknown>
#11 0x58694c5e54bb <unknown>
#12 0x58694c5e47b6 <unknown>
#13 0x58694c58fcbf <unknown>
#14 0x58694c590a81 <unknown>
#15 0x58694cb00a64 <unknown>
#16 0x58694cb03951 <unknown>
#17 0x58694caed21e <unknown>
#18 0x58694cb0451e <unknown>
#19 0x58694cad3be0 <unknown>
#20 0x58694cb279b8 <unknown>
#21 0x58694cb27b88 <unknown>
#22 0x58694cb394de <unknown>
#23 0x7cb20bfe7ac3 <unknown>

Tempo de execução para https://presidentecastelobranco.pr.gov.br/: 73.53s
Tempo de execução para https://www.saopedrodoiguacu.pr.gov.br/: 16.45s
WebDriver error for http://www.iracemadooeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x58fdd3747a6a <unknown>
#1 0x58fdd3156ab5 <unknown>
#2 0x58fdd314d9bf <unknown>
#3 0x58fdd313e6d1 <unknown>
#4 0x58fdd31404cc <unknown>
#5 0x58fdd313ebca <unknown>
#6 0x58fdd313e3f0 <unknown>
#7 0x58fdd313e0a4 <unknown>
#8 0x58fdd313bdeb <unknown>
#9 0x58fdd313c630 <unknown>
#10 0x58fdd315a1ed <unknown>
#11 0x58fdd31f24bb <unknown>
#12 0x58fdd31f17b6 <unknown>
#13 0x58fdd319ccbf <unknown>
#14 0x58fdd319da81 <unknown>
#15 0x58fdd370da64 <unknown>
#16 0x58fdd3710951 <unknown>
#17 0x58fdd36fa21e <unknown>
#18 0x58fdd371151e <unknown>
#19 0x58fdd36e0be0 <unknown>
#20 0x58fdd37349b8 <unknown>
#21 0x58fdd3734b88 <unknown>
#22 0x58fdd37464de <unknown>
#23 0x7d10a9485ac3 <unknown>

Tempo de execução para http://www.iracemadooeste.pr.gov.br/: 40.84s
General error for https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: HTTPConnectionPool(host='localhost', port=37681): Read timed out. (read timeout=120)
Tempo de execução para https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: 133.15s
General error for http://177.92.1.11:7474/transparencia/: HTTPConnectionPool(host='localhost', port=58325): Read timed out. (read timeout=120)
Tempo de execução para http://177.92.1.11:7474/transparencia/: 133.76s
General error for https://saotomepr.equiplano.com.br:7430/transparencia/: HTTPConnectionPool(host='localhost', port=41847): Read timed out. (read timeout=120)
Tempo de execução para https://saotomepr.equiplano.com.br:7430/transparencia/: 133.99s
Tempo de execução para https://www.transparencia.curitiba.pr.gov.br/: 10.12s
WebDriver error for https://www.saocarlosdoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5bd7e0b49a6a <unknown>
#1 0x5bd7e0558ab5 <unknown>
#2 0x5bd7e054f9bf <unknown>
#3 0x5bd7e05406d1 <unknown>
#4 0x5bd7e05424cc <unknown>
#5 0x5bd7e0540bca <unknown>
#6 0x5bd7e05403f0 <unknown>
#7 0x5bd7e05400a4 <unknown>
#8 0x5bd7e053ddeb <unknown>
#9 0x5bd7e053e630 <unknown>
#10 0x5bd7e055c1ed <unknown>
#11 0x5bd7e05f44bb <unknown>
#12 0x5bd7e05f37b6 <unknown>
#13 0x5bd7e059ecbf <unknown>
#14 0x5bd7e059fa81 <unknown>
#15 0x5bd7e0b0fa64 <unknown>
#16 0x5bd7e0b12951 <unknown>
#17 0x5bd7e0afc21e <unknown>
#18 0x5bd7e0b1351e <unknown>
#19 0x5bd7e0ae2be0 <unknown>
#20 0x5bd7e0b369b8 <unknown>
#21 0x5bd7e0b36b88 <unknown>
#22 0x5bd7e0b484de <unknown>
#23 0x7df837609ac3 <unknown>

Tempo de execução para https://www.saocarlosdoivai.pr.gov.br/: 68.25s
Progresso: 10/133
WebDriver error for http://www.saopedrodoivai.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5bf327307a6a <unknown>
#1 0x5bf326d16ab5 <unknown>
#2 0x5bf326d0d9bf <unknown>
#3 0x5bf326cfe6d1 <unknown>
#4 0x5bf326d004cc <unknown>
#5 0x5bf326cfebca <unknown>
#6 0x5bf326cfe3f0 <unknown>
#7 0x5bf326cfe0a4 <unknown>
#8 0x5bf326cfbdeb <unknown>
#9 0x5bf326cfc630 <unknown>
#10 0x5bf326d1a1ed <unknown>
#11 0x5bf326db24bb <unknown>
#12 0x5bf326db17b6 <unknown>
#13 0x5bf326d5ccbf <unknown>
#14 0x5bf326d5da81 <unknown>
#15 0x5bf3272cda64 <unknown>
#16 0x5bf3272d0951 <unknown>
#17 0x5bf3272ba21e <unknown>
#18 0x5bf3272d151e <unknown>
#19 0x5bf3272a0be0 <unknown>
#20 0x5bf3272f49b8 <unknown>
#21 0x5bf3272f4b88 <unknown>
#22 0x5bf3273064de <unknown>
#23 0x7caedb1e2ac3 <unknown>

Tempo de execução para http://www.saopedrodoivai.pr.gov.br/: 46.1s
Tempo de execução para http://45.225.146.100:8090/ portaltransparencia/1/: 6.3s
Tempo de execução para https://transparencia.betha.cloud/#/XsTYmnrmpsOvZ8_9fe1GYw==: 2.78s
Tempo de execução para https://transparencia.missal.pr.gov.br/: 29.2s
General error for https://uraipr.equiplano.com.br:7446/transparencia/: HTTPConnectionPool(host='localhost', port=60225): Read timed out. (read timeout=120)
Tempo de execução para https://uraipr.equiplano.com.br:7446/transparencia/: 126.73s
Tempo de execução para https://transparencia.betha.cloud/#/9JCGb59gmZKaC3wzdXmbRw==: 4.28s
WebDriver error for https://mariopolis.govbr.cloud/pronimtb/index.html: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5b1fc1fd7a6a <unknown>
#1 0x5b1fc19e6ab5 <unknown>
#2 0x5b1fc19dd9bf <unknown>
#3 0x5b1fc19ce6d1 <unknown>
#4 0x5b1fc19d04cc <unknown>
#5 0x5b1fc19cebca <unknown>
#6 0x5b1fc19ce3f0 <unknown>
#7 0x5b1fc19ce0a4 <unknown>
#8 0x5b1fc19cbdeb <unknown>
#9 0x5b1fc19cc630 <unknown>
#10 0x5b1fc19ea1ed <unknown>
#11 0x5b1fc1a824bb <unknown>
#12 0x5b1fc1a817b6 <unknown>
#13 0x5b1fc1a2ccbf <unknown>
#14 0x5b1fc1a2da81 <unknown>
#15 0x5b1fc1f9da64 <unknown>
#16 0x5b1fc1fa0951 <unknown>
#17 0x5b1fc1f8a21e <unknown>
#18 0x5b1fc1fa151e <unknown>
#19 0x5b1fc1f70be0 <unknown>
#20 0x5b1fc1fc49b8 <unknown>
#21 0x5b1fc1fc4b88 <unknown>
#22 0x5b1fc1fd64de <unknown>
#23 0x78c03fa30ac3 <unknown>

Tempo de execução para https://mariopolis.govbr.cloud/pronimtb/index.html: 7.7s
Tempo de execução para https://douradina.pr.gov.br/: 5.51s
WebDriver error for https://www.sertaneja.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5d0c08ca0a6a <unknown>
#1 0x5d0c086afab5 <unknown>
#2 0x5d0c086a69bf <unknown>
#3 0x5d0c086976d1 <unknown>
#4 0x5d0c086994cc <unknown>
#5 0x5d0c08697bca <unknown>
#6 0x5d0c086973f0 <unknown>
#7 0x5d0c086970a4 <unknown>
#8 0x5d0c08694deb <unknown>
#9 0x5d0c08695630 <unknown>
#10 0x5d0c086b31ed <unknown>
#11 0x5d0c0874b4bb <unknown>
#12 0x5d0c0874a7b6 <unknown>
#13 0x5d0c086f5cbf <unknown>
#14 0x5d0c086f6a81 <unknown>
#15 0x5d0c08c66a64 <unknown>
#16 0x5d0c08c69951 <unknown>
#17 0x5d0c08c5321e <unknown>
#18 0x5d0c08c6a51e <unknown>
#19 0x5d0c08c39be0 <unknown>
#20 0x5d0c08c8d9b8 <unknown>
#21 0x5d0c08c8db88 <unknown>
#22 0x5d0c08c9f4de <unknown>
#23 0x7d880c0b9ac3 <unknown>

Tempo de execução para https://www.sertaneja.pr.gov.br/: 94.34s
Tempo de execução para https://campomagro.pr.gov.br/: 38.29s
Tempo de execução para https://www.bituruna.pr.gov.br//portalTransparencia/: 5.97s
Tempo de execução para https://transparencia.betha.cloud/#/r2cpj2e4mrz8xjHlykU8bg==: 10.14s
WebDriver error for https://www.cruzeirodooeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x57827d32ca6a <unknown>
#1 0x57827cd3bab5 <unknown>
#2 0x57827cd329bf <unknown>
#3 0x57827cd236d1 <unknown>
#4 0x57827cd254cc <unknown>
#5 0x57827cd23bca <unknown>
#6 0x57827cd233f0 <unknown>
#7 0x57827cd230a4 <unknown>
#8 0x57827cd20deb <unknown>
#9 0x57827cd21630 <unknown>
#10 0x57827cd3f1ed <unknown>
#11 0x57827cdd74bb <unknown>
#12 0x57827cdd67b6 <unknown>
#13 0x57827cd81cbf <unknown>
#14 0x57827cd82a81 <unknown>
#15 0x57827d2f2a64 <unknown>
#16 0x57827d2f5951 <unknown>
#17 0x57827d2df21e <unknown>
#18 0x57827d2f651e <unknown>
#19 0x57827d2c5be0 <unknown>
#20 0x57827d3199b8 <unknown>
#21 0x57827d319b88 <unknown>
#22 0x57827d32b4de <unknown>
#23 0x79313e230ac3 <unknown>

Tempo de execução para https://www.cruzeirodooeste.pr.gov.br/: 79.19s
WebDriver error for https://www.pontaldoparana.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5c9075c49a6a <unknown>
#1 0x5c9075658ab5 <unknown>
#2 0x5c907564f9bf <unknown>
#3 0x5c90756406d1 <unknown>
#4 0x5c90756424cc <unknown>
#5 0x5c9075640bca <unknown>
#6 0x5c90756403f0 <unknown>
#7 0x5c90756400a4 <unknown>
#8 0x5c907563ddeb <unknown>
#9 0x5c907563e630 <unknown>
#10 0x5c907565c1ed <unknown>
#11 0x5c90756f44bb <unknown>
#12 0x5c90756f37b6 <unknown>
#13 0x5c907569ecbf <unknown>
#14 0x5c907569fa81 <unknown>
#15 0x5c9075c0fa64 <unknown>
#16 0x5c9075c12951 <unknown>
#17 0x5c9075bfc21e <unknown>
#18 0x5c9075c1351e <unknown>
#19 0x5c9075be2be0 <unknown>
#20 0x5c9075c369b8 <unknown>
#21 0x5c9075c36b88 <unknown>
#22 0x5c9075c484de <unknown>
#23 0x7acd0550bac3 <unknown>

Tempo de execução para https://www.pontaldoparana.pr.gov.br/: 65.74s
General error for https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: HTTPConnectionPool(host='localhost', port=51237): Read timed out. (read timeout=120)
Tempo de execução para https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: 125.17s
General error for http://177.92.1.11:7474/transparencia/: HTTPConnectionPool(host='localhost', port=55713): Read timed out. (read timeout=120)
Tempo de execução para http://177.92.1.11:7474/transparencia/: 121.3s
WebDriver error for http://sistemas.ivai.pr.gov.br:7020/transparencia/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x574665f38a6a <unknown>
#1 0x574665947ab5 <unknown>
#2 0x57466593e9bf <unknown>
#3 0x57466592f6d1 <unknown>
#4 0x5746659314cc <unknown>
#5 0x57466592fbca <unknown>
#6 0x57466592f3f0 <unknown>
#7 0x57466592f0a4 <unknown>
#8 0x57466592cdeb <unknown>
#9 0x57466592d630 <unknown>
#10 0x57466594b1ed <unknown>
#11 0x5746659e34bb <unknown>
#12 0x5746659e27b6 <unknown>
#13 0x57466598dcbf <unknown>
#14 0x57466598ea81 <unknown>
#15 0x574665efea64 <unknown>
#16 0x574665f01951 <unknown>
#17 0x574665eeb21e <unknown>
#18 0x574665f0251e <unknown>
#19 0x574665ed1be0 <unknown>
#20 0x574665f259b8 <unknown>
#21 0x574665f25b88 <unknown>
#22 0x574665f374de <unknown>
#23 0x799dfdc66ac3 <unknown>

Tempo de execução para http://sistemas.ivai.pr.gov.br:7020/transparencia/: 31.5s
WebDriver error for http://www.iracemadooeste.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x58d0f9688a6a <unknown>
#1 0x58d0f9097ab5 <unknown>
#2 0x58d0f908e9bf <unknown>
#3 0x58d0f907f6d1 <unknown>
#4 0x58d0f90814cc <unknown>
#5 0x58d0f907fbca <unknown>
#6 0x58d0f907f3f0 <unknown>
#7 0x58d0f907f0a4 <unknown>
#8 0x58d0f907cdeb <unknown>
#9 0x58d0f907d630 <unknown>
#10 0x58d0f909b1ed <unknown>
#11 0x58d0f91334bb <unknown>
#12 0x58d0f91327b6 <unknown>
#13 0x58d0f90ddcbf <unknown>
#14 0x58d0f90dea81 <unknown>
#15 0x58d0f964ea64 <unknown>
#16 0x58d0f9651951 <unknown>
#17 0x58d0f963b21e <unknown>
#18 0x58d0f965251e <unknown>
#19 0x58d0f9621be0 <unknown>
#20 0x58d0f96759b8 <unknown>
#21 0x58d0f9675b88 <unknown>
#22 0x58d0f96874de <unknown>
#23 0x7dfce897bac3 <unknown>

Tempo de execução para http://www.iracemadooeste.pr.gov.br/: 37.94s
Tempo de execução para https://www.transparencia.curitiba.pr.gov.br/: 10.21s
WebDriver error for http://godoymoreira.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5942ab35ea6a <unknown>
#1 0x5942aad6dab5 <unknown>
#2 0x5942aad649bf <unknown>
#3 0x5942aad556d1 <unknown>
#4 0x5942aad574cc <unknown>
#5 0x5942aad55bca <unknown>
#6 0x5942aad553f0 <unknown>
#7 0x5942aad550a4 <unknown>
#8 0x5942aad52deb <unknown>
#9 0x5942aad53630 <unknown>
#10 0x5942aad711ed <unknown>
#11 0x5942aae094bb <unknown>
#12 0x5942aae087b6 <unknown>
#13 0x5942aadb3cbf <unknown>
#14 0x5942aadb4a81 <unknown>
#15 0x5942ab324a64 <unknown>
#16 0x5942ab327951 <unknown>
#17 0x5942ab31121e <unknown>
#18 0x5942ab32851e <unknown>
#19 0x5942ab2f7be0 <unknown>
#20 0x5942ab34b9b8 <unknown>
#21 0x5942ab34bb88 <unknown>
#22 0x5942ab35d4de <unknown>
#23 0x7a9cc1accac3 <unknown>

Tempo de execução para http://godoymoreira.pr.gov.br/: 32.23s
WebDriver error for https://www.reservadoiguacu.pr.gov.br/: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x576f3e78aa6a <unknown>
#1 0x576f3e199ab5 <unknown>
#2 0x576f3e1909bf <unknown>
#3 0x576f3e1816d1 <unknown>
#4 0x576f3e1834cc <unknown>
#5 0x576f3e181bca <unknown>
#6 0x576f3e1813f0 <unknown>
#7 0x576f3e1810a4 <unknown>
#8 0x576f3e17edeb <unknown>
#9 0x576f3e17f630 <unknown>
#10 0x576f3e19d1ed <unknown>
#11 0x576f3e2354bb <unknown>
#12 0x576f3e2347b6 <unknown>
#13 0x576f3e1dfcbf <unknown>
#14 0x576f3e1e0a81 <unknown>
#15 0x576f3e750a64 <unknown>
#16 0x576f3e753951 <unknown>
#17 0x576f3e73d21e <unknown>
#18 0x576f3e75451e <unknown>
#19 0x576f3e723be0 <unknown>
#20 0x576f3e7779b8 <unknown>
#21 0x576f3e777b88 <unknown>
#22 0x576f3e7894de <unknown>
#23 0x7dcccd32aac3 <unknown>

Tempo de execução para https://www.reservadoiguacu.pr.gov.br/: 5.37s
Tempo de execução para https://transparencia.betha.cloud/#/bGt4VnWNiKNT6r5CBDED_Q==: 2.69s
General error for https://guairacapr.equiplano.com.br:7461/transparencia/: HTTPConnectionPool(host='localhost', port=43425): Read timed out. (read timeout=120)
Tempo de execução para https://guairacapr.equiplano.com.br:7461/transparencia/: 124.17s
Tempo de execução para https://transparencia.betha.cloud/#/IKR2wBO51OO0hvKMMKC60Q==: 4.85s
Tempo de execução para https://transparencia.missal.pr.gov.br/: 23.2s
Tempo de execução para https://transparencia.betha.cloud/#/9JCGb59gmZKaC3wzdXmbRw==: 1.31s
General error for https://uraipr.equiplano.com.br:7446/transparencia/: HTTPConnectionPool(host='localhost', port=55265): Read timed out. (read timeout=120)
Tempo de execução para https://uraipr.equiplano.com.br:7446/transparencia/: 122.64s
WebDriver error for https://mariopolis.govbr.cloud/pronimtb/index.html: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x568d7ffd1a6a <unknown>
#1 0x568d7f9e0ab5 <unknown>
#2 0x568d7f9d79bf <unknown>
#3 0x568d7f9c86d1 <unknown>
#4 0x568d7f9ca4cc <unknown>
#5 0x568d7f9c8bca <unknown>
#6 0x568d7f9c83f0 <unknown>
#7 0x568d7f9c80a4 <unknown>
#8 0x568d7f9c5deb <unknown>
#9 0x568d7f9c6630 <unknown>
#10 0x568d7f9e41ed <unknown>
#11 0x568d7fa7c4bb <unknown>
#12 0x568d7fa7b7b6 <unknown>
#13 0x568d7fa26cbf <unknown>
#14 0x568d7fa27a81 <unknown>
#15 0x568d7ff97a64 <unknown>
#16 0x568d7ff9a951 <unknown>
#17 0x568d7ff8421e <unknown>
#18 0x568d7ff9b51e <unknown>
#19 0x568d7ff6abe0 <unknown>
#20 0x568d7ffbe9b8 <unknown>
#21 0x568d7ffbeb88 <unknown>
#22 0x568d7ffd04de <unknown>
#23 0x7be2f0313ac3 <unknown>

Tempo de execução para https://mariopolis.govbr.cloud/pronimtb/index.html: 3.31s
WebDriver error for http://pmsac.pr.gov.br/: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=146.0.7680.177)
Stacktrace:
#0 0x5c7a3b79ca6a <unknown>
#1 0x5c7a3b1abab5 <unknown>
#2 0x5c7a3b1a29bf <unknown>
#3 0x5c7a3b1936d1 <unknown>
#4 0x5c7a3b1954cc <unknown>
#5 0x5c7a3b193bca <unknown>
#6 0x5c7a3b1933f0 <unknown>
#7 0x5c7a3b1930a4 <unknown>
#8 0x5c7a3b190deb <unknown>
#9 0x5c7a3b191630 <unknown>
#10 0x5c7a3b1af1ed <unknown>
#11 0x5c7a3b2474bb <unknown>
#12 0x5c7a3b2467b6 <unknown>
#13 0x5c7a3b1f1cbf <unknown>
#14 0x5c7a3b1f2a81 <unknown>
#15 0x5c7a3b762a64 <unknown>
#16 0x5c7a3b765951 <unknown>
#17 0x5c7a3b74f21e <unknown>
#18 0x5c7a3b76651e <unknown>
#19 0x5c7a3b735be0 <unknown>
#20 0x5c7a3b7899b8 <unknown>
#21 0x5c7a3b789b88 <unknown>
#22 0x5c7a3b79b4de <unknown>
#23 0x7fc8a8e05ac3 <unknown>

Tempo de execução para http://pmsac.pr.gov.br/: 34.22s
General error for https://prudentopolispr.equiplano.com.br:7443/transparencia/: HTTPConnectionPool(host='localhost', port=55249): Read timed out. (read timeout=120)
Tempo de execução para https://prudentopolispr.equiplano.com.br:7443/transparencia/: 122.59s
Tempo de execução para https://douradina.pr.gov.br/: 9.69s
Progresso: 30/133

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
0,1270,664,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True,<html><head><title>403 Forbidden</title></head...,None,None,URL_BLOCKED,URL bloqueada,[],[],15.95
1,2949,664,Disponibilidade,https://www.marialva.pr.gov.br/,True,None,None,None,WebDriverException,Message: unknown error: net::ERR_NAME_NOT_RESO...,[],[],94.72
2,2888,664,Disponibilidade,https://mandirituba.pr.gov.br/portal-da-transp...,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",None,None,URL_BLOCKED,URL bloqueada,[],[],16.72
3,4910,664,Disponibilidade,https://saotomepr.equiplano.com.br:7430/transp...,False,None,None,None,ReadTimeoutError,"HTTPConnectionPool(host='localhost', port=4184...",[],[],133.99
4,1754,664,Disponibilidade,https://fazendariogrande.pr.gov.br/transparencia,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",None,None,URL_BLOCKED,URL bloqueada,[],[],18.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,34,664,Disponibilidade,https://transparencia.betha.cloud/#/k7LmvDe0yL...,True,"<html><head><meta http-equiv=""Content-Type"" co...",None,None,URL_BLOCKED,URL bloqueada,[],[],2.02
129,4067,664,Disponibilidade,https://quedasdoiguacupr.equiplano.com.br:7006...,True,None,None,None,ReadTimeoutError,"HTTPConnectionPool(host='localhost', port=3338...",[],[],123.79
130,4168,664,Disponibilidade,http://rcpnetworks.com.br:8091/portaltranspare...,True,None,None,None,WebDriverException,Message: unknown error: net::ERR_NAME_NOT_RESO...,[],[],3.84
131,5196,664,Disponibilidade,https://telemacoborba.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",None,None,URL_BLOCKED,URL bloqueada,[],[],1.73
132,3380,664,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,<html><head><title>403 Forbidden</title></head...,None,None,URL_BLOCKED,URL bloqueada,[],[],2.17

In [ ]:
df_retry.error_cod.value_counts()

error_cod
URL_BLOCKED           59
WebDriverException    49
ReadTimeoutError      22
False                  3
Name: count, dtype: int64

In [ ]:
df_retry.query("error_cod == False")

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
18,978,664,Disponibilidade,https://campomagro.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[https://radardatransparencia.atricon.org.br/],"[<a class=""dropdown-item"" href=""https://radard...",False,False,[],[],38.29
23,1508,664,Disponibilidade,https://www.transparencia.curitiba.pr.gov.br/,True,"<html lang=""pt-br""><head><title>\n\tPortal da ...","[https://radardatransparencia.atricon.org.br/,...","[<a href=""https://radardatransparencia.atricon...",False,False,[],[],10.21
24,3100,664,Disponibilidade,https://transparencia.missal.pr.gov.br/,True,"<html lang=""pt-BR"" style=""font-size: 100%;""><h...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",False,False,[],[],23.20

Verficando a questão 664, relacionada a existência de um elemento que leve ao site do Radar da Transparência (https://radardatransparencia.atricon.org.br/)  foi localizada em 239 dos 397 link testados, sendo 10 vazios, 45 erros de link informados (https://www.tce.pr.gov.br/, https://radar.tce.mt.gov.br/, https://radardatransparencia.atricon.org.br/), 39 página possuem um elemento contendo um trecho "RADAR/Radar/radar", porém o elemento final não leva ao portal da atricon

###OUTROS SCRAPS

In [ ]:
def scrape_sync():
    URL = "https://rionegro.pr.gov.br/transparencia"
    page = StealthyFetcher.fetch(
        URL,
        headless=True,
        network_idle=True
    )
    return page

page = scrape_sync()
print(page.status)

In [ ]:
URL = "https://rionegro.pr.gov.br/transparencia"
page = StealthyFetcher.fetch(URL, headless=True, network_idle=True)  # Fetch website under the radar!


html = page.html
print("Status:", page.status)

In [ ]:
URL = "https://rionegro.pr.gov.br/transparencia"

page = StealthyFetcher.fetch(URL, headless=True, network_idle=True)  # Fetch website under the radar!


html = page.html
print("Status:", page.status)

In [ ]:
url = "https://rionegro.pr.gov.br/transparencia"

def scrap_http_1(url):
    page = Fetcher.get(url)
    return page.html, page.title or "", None, None

def scrap_http_session(url):
    try:
        with FetcherSession(impersonate='chrome') as session:
            page = session.get(url, stealthy_headers=True)
        return page.html, page.title or "", None, None
    except Exception as e:
        return None, None, type(e).__name__, str(e)

html, title, err, msg = scrap_http_session(url)

In [ ]:
##Tipo Select##

url = "https://www.ingadigital.com.br/transparencia/?id_cliente=11986"

driver = abrir_driver()

html0 = None
html1 = None
html2 = None

try:
  driver.set_page_load_timeout(30)
  driver.get(url)

  html0 = driver.page_source
  wait = WebDriverWait(driver, 30)
  try:
    wait.until(
      EC.any_of(
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                )
    )
    html1 = driver.page_source
    check_input = driver.find_element(By.ID, 'filterFilterano') #{PARAMENTOS DE BUSCAS PARA FILTRAGEM}
    select = Select(check_input)
    select.select_by_value("2024")
    check_click = driver.find_element(By.CLASS_NAME, 'submit')
    check_click.click()
    wait.until(
        EC.any_of(
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                  )
        )

  except TimeoutException:
    print("Timeout esperando carregamento principal, seguindo mesmo assim.")
    html2 = driver.page_source

  except Exception as e:
    titulo_text = None
    print(f"Não foi possível encontrar o título para {url}: {e}")

except WebDriverException as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"WebDriver error for {url}: {error_msg}")


except Exception as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"General error for {url}: {error_msg}")
    html2 = driver.page_source
    driver.quit()
finally:
    driver.quit()

In [ ]:
##Tipo elementos de texto##

url = "https://www.instagram.com/saomanoeldopr/"

driver = abrir_driver()

html0 = None
html1 = None
html2 = None

try:
  driver.set_page_load_timeout(30)
  driver.get(url)

  html0 = driver.page_source
  wait = WebDriverWait(driver, 10)

  try:
    wait.until(
      EC.any_of(
                EC.presence_of_all_elements_located((By.NAME,"username")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".bth-card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                )
    )


    html1 = driver.page_source

    #FUNCAO DE LOCALIZACAO
    elements = driver.find_elements(By.TAG_NAME, 'title') #PARAMETRO DE BUSCA

    #FUNCAO DE BUSCA
    #lista de perguntas
    lista_text = []
    for e in elements:
      lista_text.append(e.text)



  except TimeoutException:
    print("Timeout esperando carregamento principal, seguindo mesmo assim.")
    html2 = driver.page_source

  except Exception as e:
    titulo_text = None
    print(f"Não foi possível encontrar o título para {url}: {e}")

except WebDriverException as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"WebDriver error for {url}: {error_msg}")


except Exception as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"General error for {url}: {error_msg}")
    html2 = driver.page_source
    driver.quit()
finally:
    driver.quit()

In [ ]:
url =  ["https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/servlet/wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg="]

for i in url:

  html_selenium = None
  elemento = None
  html_elemento = None
  error_cod = False
  error_msg = False
  texto_click = None
  html_click = None
  elemento_f = None
  html_elemento_f = None
  tipo_busca = "link"

  if not url:
    print("Erro: URL vazia ou não localizada para raspagem.")


  try:
    driver = abrir_driver()
    driver.get(i)
    wait = WebDriverWait(driver, 40)
    driver.set_page_load_timeout(60)
    driver.implicitly_wait(5)


    try: ##Parâmetros HTML para busca inicial
        wait.until(
            EC.any_of(
                      EC.presence_of_all_elements_located((By.TAG_NAME,"a")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                      )
            )

        html_selenium = driver.page_source

    except TimeoutException:
        print(f"Timeout esperando carregamento principal para {url}, seguindo mesmo assim.")

    try:
        parametros = ["RADAR","atricon"] #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS

        c , d = buscador(driver, "link", parametros  )

        parametro_navegacao = ["RADAR"]

        for p in parametro_navegacao:
          element_click = driver.find_element(By.XPATH , f'//*[contains(text(),"{p}")]')

          texto = element_click.text
          html = element_click.get_attribute("outerHTML")

          element_click.click()
          driver.implicitly_wait(5)



        e , f = buscador(driver, "link", parametros  )

    except Exception as e:
        error_cod = type(e).__name__
        error_msg = str(e)
        print(f"Erro na busca por elementos: {error_msg}")

  finally:
      driver.quit()

print("Encontrados os seguintes links:", c)
print("HTML dos elementos encontrados:", d )
print("Encontrados os seguintes links:", e)
print("HTML dos elementos encontrados:", f )

Encontrados os seguintes links: []
HTML dos elementos encontrados: []
Encontrados os seguintes links: ['https://radardatransparencia.atricon.org.br/radar-da-transparencia-publica.html']
HTML dos elementos encontrados: ['<a id="ygtvlabelel20" class="BasicNodeTextDecoration" style="background:url(/etransparencia.pm.santamonica.pr/static/Resources/RelAnexos.gif) no-repeat;padding-left: 20px;" href="https://radardatransparencia.atricon.org.br/radar-da-transparencia-publica.html" target="_blank" onclick="return YAHOO.widget.TreeView.getNode(\'TREEVIEW1Container\',20).onLabelClick(YAHOO.widget.TreeView.getNode(\'TREEVIEW1Container\',20))"><span id="ygtvlabelel20Span" class="NodeTextDecoration" style=" undefined">Link Acesso..</span></a>']

In [ ]:
html

'<span id="ygtvlabelel19Span" class="NodeTextDecoration" style=" undefined">RADAR NACIONAL DE TRANSPARÊNCIA</span>'

In [ ]:
html_selenium

'<html lang="pt"><head>\n<meta name="generator" content="GeneXus Java 15_0_6-116888">\n<meta name="description" content="ww Modelo">\n<!--[if IE]><meta http-equiv="page-enter" content="blendTrans(Duration=0.1)"/><![endif]-->\n<meta name="fragment" content="!">\n<meta http-equiv="content-type" content="text/html; charset=UTF-8">\n<title>e-transparência</title>\n<link rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/AspSelectBox/tema/jquery-ui-1.10.1.custom.css">\n<link rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/AspSelectBox/tema/jquery.ui.combogrid.css">\n<style id="gx-dom-fixes">.gx-center-align {text-align:center;}.gx-center-align > p,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-center-align > table,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-center-align > div,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-center-align > fieldset,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:auto;margin-right:auto;}.gx-right-align {text-align:right;}.gx-right-align > p,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-right-align > table,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-right-align > div,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-right-align > fieldset,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:auto;margin-right:0;}.gx-left-align {text-align:left;}.gx-left-align > p,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-left-align > table,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-left-align > div,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-left-align > fieldset,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:0;margin-right:auto;}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}</style><link id="gxtheme_css_reference" rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/Resources/Portuguese/tmPortal.css?2025121115525298">\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/jquery.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxtimezone.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxgral.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxcfg.js?202512111551741"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/yahoo.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/event.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/treeview.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/dom.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/yahoo-dom-event.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/dragdrop.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/DDSend.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/TreeviewRender.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/js/jquery-ui-1.10.1.custom.min.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/js/jquery.ui.combogrid-1.6.3.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/AspSelectBoxRender.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/JSHandler/JSHandlerRender.js"></script>\n<link rel="shortcut icon" href="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/imgIconePadrao.ico" type="images/x-icon"><style>[vw] [vw-access-button]{display:none;flex-direction:row-reverse;width:40px;height:40px;cursor:pointer;overflow:hidden;position:absolute;border-radius:8px;transition:all 0.5s ease;right:0;left:auto}[vw] [vw-access-button] img{max-height:40px;transition:all 0.5s ease;border-radius:8px;opacity:1 !important;visibility:visible !important}[vw] [vw-access-button] .vp-access-button{width:40px;height:40px;z-index:1}[vw] [vw-access-button] .vp-pop-up{position:absolute;height:40px;min-width:150px;z-index:0;left:0;right:auto}[vw] [vw-access-button]:hover{width:200px}[vw] [vw-access-button].isLeft{flex-direction:row;left:0;right:auto}[vw] [vw-access-button].isLeft .vp-pop-up{left:auto;right:0}[vw] [vw-access-button].isTopOrBottom:hover{bottom:-20px;top:0;margin-right:-80px}[vw] [vw-access-button].active{display:flex}\n</style><style>[vw].left [vw-plugin-wrapper]{float:left}[vw] [vw-plugin-wrapper]{position:relative;display:none;width:300px;height:100%;float:right;background:white;-webkit-box-shadow:0px 0px 15px rgba(0,0,0,0.2);-moz-box-shadow:0px 0px 15px rgba(0,0,0,0.2);box-shadow:0px 0px 15px rgba(0,0,0,0.2);border-radius:12px;-moz-border-radius:12px;-webkit-border-radius:12px}[vw] [vw-plugin-wrapper].active{display:-webkit-flex;display:flex;flex-direction:column;-webkit-flex-direction:column;height:450px;max-width:100%;min-height:100%}\n</style><style>div[vw]{position:fixed;max-width:95vw;min-height:40px;min-width:40px;z-index:2147483645 !important;display:none;margin:10px !important}div[vw].enabled{display:block}div[vw].active{margin-top:-285px}div[vw].left{left:0;right:initial}\n</style><link type="text/css" rel="stylesheet" media="screen" href="https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/static/Treeview/assets/css/default/tree.css"></head>\n<body class="Form Form-fx" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);" data-hasenter="false" data-skiponenter="false">\n<form id="MAINFORM" name="MAINFORM" method="post" tabindex="-1" class="Form" data-gx-class="Form" novalidate="" action="wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg=">\n\n\n\n<div class="gx-call-target top off empty"><div class="gxwebcomponent" id="gxHTMLWrpMPW9996"></div></div><div id="gx-column-targets"><div class="gx-call-target left off empty"><div class="gxwebcomponent" id="gxHTMLWrpMPW9999"></div></div><div class="gx-center-target"><input type="submit" style="display:none"><table id="TABFUNDO_MPAGE" class="gx-tab-spacing-fix-0 Table" data-cellpadding="0" data-cellspacing="0" style="margin-left:auto; margin-right: auto; height: 100%; width: 100%;"><tbody><tr><td class="gx-tab-padding-fix-0 "><table id="TABIMAGEM_MPAGE" class="gx-tab-spacing-fix-0 TabelaImgFundo" data-cellpadding="0" data-cellspacing="0" style="height: 100%; width: 100%;"><tbody><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center;vertical-align:top" class="gx-tab-padding-fix-0  "><table id="TABPRINCIPAL_MPAGE" class="gx-tab-spacing-fix-0 Table" data-cellpadding="0" data-cellspacing="0" style="height: 100%; width: 1000px;"><tbody><tr><td style="height:100px" class="gx-tab-padding-fix-0   "><div class="gxwebcomponent" id="gxHTMLWrpMPW0011"><script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspFontSize/AspFontSizeRender.js"></script>\n<div class="gxwebcomponent-body Form-fx"><div><span class="gx_ev ErrorViewerBullet" id="MPW0011gxErrorViewer"></span></div><table id="MPW0011TABCABLOGOTIPO" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td data-align="right" style="text-align:-khtml-right;text-align:-moz-right;text-align:-webkit-right;height:5px" class="gx-tab-padding-fix-0     ">&nbsp;</td></tr><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center" class="gx-tab-padding-fix-0     "><table id="MPW0011TABLE3" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td class="gx-tab-padding-fix-0       "><table id="MPW0011TABLE4" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 15px;"><tbody><tr><td class="gx-tab-padding-fix-0         "></td></tr></tbody></table></td><td class="gx-tab-padding-fix-0       "><a href="portal" class="gx-image-link"><img src="https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/PublicTempStorage/multimedia/SantaMonica_ITP2025_Prata_ia_759bad3beb99441ebe689af6d60b5045.JPG" id="MPW0011IMGPARAM" alt="" class="Image"></a></td><td style="width:100%" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><a href="portal" class="gx-image-link"><img src="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/logo_etransparencia_head.png" id="MPW0011IMGLOGO" alt="" class="Image"></a></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TABLE2" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 15px;"><tbody><tr><td class="gx-tab-padding-fix-0         "></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td style="height:15px" class="gx-tab-padding-fix-0     "></td></tr></tbody></table><table id="MPW0011TABCABECALHOPERSOLANIZADO" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="display:none; width: 100%;"><tbody><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center" class="gx-tab-padding-fix-0     "><table id="MPW0011TABLE7" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td style="width:1px" class="gx-tab-padding-fix-0       "></td><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center;height:175px;width:100%" class="gx-tab-padding-fix-0       "><img src="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/ActionDisabled.gif" id="MPW0011IMGCABPERSONALIZADO" alt="" class="Image"></td><td style="width:100%" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "></td></tr></tbody></table></td></tr></tbody></table><div class="gx_usercontrol" id="MPW0011ASPFONTSIZE1Container"></div><table id="MPW0011TABLECONTAINERCONTRASTE" class="gx-tab-spacing-fix-2  TabelaFlutuante" data-cellpadding="1" data-cellspacing="2"><tbody><tr><td data-align="right" style="text-align:-khtml-right;text-align:-moz-right;text-align:-webkit-right" class="gx-tab-padding-fix-1     "><table id="MPW0011TABLE6" class="gx-tab-spacing-fix-0  TabelaFundoBotao" data-cellpadding="0" data-cellspacing="0" style="margin-left:auto;"><tbody><tr><td style="width:3px" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBDADOSABERTOS" class="gx-tab-spacing-fix-2  VLibras" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><img src="/etransparencia.pm.santamonica.pr/static/Resources/open_padlock_01.png" data-gx-evt="5" id="MPW0011IMAGE2" alt="Dados Abertos" title="Dados Abertos" class="Image" style="width: 21px;height: 19px" onfocus="gx.evt.onfocus(this, 46,\'MPW0011\',false,\'\',0)" data-gx-evt-control="IMAGE2" data-gx-context="[&quot;MPW0011&quot;,false]" tabindex="0"></td></tr></tbody></table></td><td style="width:3px" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBESPACO" class="gx-tab-spacing-fix-2  Table" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><span class="TextBlock" style="display:none;" id="MPW0011TXESPACO">espaco</span></td></tr></tbody></table></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBACESSIBILIDADE" class="gx-tab-spacing-fix-2  Table" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><span class="TextBlock" id="MPW0011TXACESSIBILIDADE">ACESSIBILIDA