<a href="https://colab.research.google.com/github/leonardosilva-sepl/Consulta_ITP24-25_PR/blob/main/AUTP_ITP2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Instalações e Imports

In [1]:
import nest_asyncio
nest_asyncio.apply()

In [2]:
#INSTALANDO O CHROME NO AMBIENTE
!apt-get update
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update
!apt-get install -y google-chrome-stable

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,954 kB]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,803 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,955 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,842 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,309 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,173 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,620 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,011 kB]
Fetched 38.1 MB in 8s (4,491 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Get:3 http://dl.google.com/linux/chrome/deb stable InRelease [1,825 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:8 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,211 B]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,036 B in 1s (2,461 B/s)
Reading package lists... Done
W: http://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libvulkan1 libxcomposite1 libxtst6
  mesa-vulkan-drivers session-migration
The following NEW packages will be installed:
  at-spi2-core google-chrome-stable gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libvulkan1
  libxcomposite1 libxtst6 mesa-vulkan-drivers session-migration
0 upgraded, 12 newly installed, 0 to remove and 24 not upgraded.
Need to get 139 MB of archives.
After this operation, 468 MB of additional disk space will be used.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 146.0.7680.164-1 [128 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 23.2.1-1ubuntu3.1~22.04.3 [10.7 MB]
Fetched 139 MB in 2s (76.7 MB/s)
Selecting previously unselected package libatk1.0-data.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../01-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../02-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../03-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../04-libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../05-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package google-chrome-stable.
Preparing to unpack .../06-google-chrome-stable_146.0.7680.164-1_amd64.deb ...
Unpacking google-chrome-stable (146.0.7680.164-1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../07-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../08-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../09-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../10-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../11-mesa-vulkan-drivers_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up google-chrome-stable (146.0.7680.164-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...

In [3]:
#SELENIUM E SUAS DEPENDENCIAS
%pip install selenium
%pip install webdriver-manager
!pip install selenium-stealth
!pip install undetected-chromedriver

Collecting selenium
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.2.25)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 77.5 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 28.0 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 9.9 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, trio, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.41.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 wsproto-1.3.2
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (2026.2.25)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-4.0.2
Collecting selenium-stealth
  Downloading selenium_stealth-1.0.6-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: selenium in /usr/local/lib/python3.12/dist-packages (from selenium-stealth) (4.41.0)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->selenium-stealth) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->selenium-stealth) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (3.11)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->selenium-stealth) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->selenium-stealth) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->selenium-stealth) (0.16.0)
Downloading selenium_stealth-1.0.6-py3-none-any.whl (32 kB)
Installing collected packages: selenium-stealth
Successfully installed selenium-stealth-1.0.6
Collecting undetected-chromedriver
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: selenium>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver) (4.41.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver) (2.32.4)
Requirement already satisfied: websockets in /usr/local/lib/python3.12/dist-packages (from undetected-chromedriver) (15.0.1)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium>=4.9.0->undetected-chromedriver) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->undetected-chromedriver) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->undetected-chromedriver) (3.11)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.12/dist-packages (from trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium>=4.9.0->undetected-chromedriver) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium>=4.9.0->undetected-chromedriver) (0.16.0)
Building wheels for collected packages: undetected-chromedriver
  Building wheel for undetected-chromedriver (setup.py) ... done
  Created wheel for undetected-chromedriver: filename=undetected_chromedriver-3.5.5-py3-none-any.whl size=47047 sha256=03a9d487c86da676b107bc6031052224dc8d608618d31175579164e938bb95d5
  Stored in directory: /root/.cache/pip/wheels/c4/f1/aa/9de6cf276210554d91e9c0526864563e850a428c5e76da4914
Successfully built undetected-chromedriver
Installing collected packages: undetected-chromedriver
Successfully installed undetected-chromedriver-3.5.5

In [4]:
#SCRAPLING
!pip install "scrapling[fetchers]"
!scrapling install           # normal install
!scrapling install  --force  # force reinstall

Collecting scrapling[fetchers]
  Downloading scrapling-0.4.3-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: lxml>=6.0.2 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (6.0.2)
Collecting cssselect>=1.4.0 (from scrapling[fetchers])
  Downloading cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: orjson>=3.11.7 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (3.11.7)
Collecting tld>=0.13.2 (from scrapling[fetchers])
  Downloading tld-0.13.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting w3lib>=2.4.1 (from scrapling[fetchers])
  Downloading w3lib-2.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (4.15.0)
Requirement already satisfied: click>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (8.3.1)
Requirement already satisfied: curl_cffi>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (0.14.0)
Collecting playwright==1.58.0 (from scrapling[fetchers])
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Collecting patchright==1.58.2 (from scrapling[fetchers])
  Downloading patchright-1.58.2-py3-none-manylinux1_x86_64.whl.metadata (11 kB)
Collecting browserforge>=1.2.4 (from scrapling[fetchers])
  Downloading browserforge-1.2.4-py3-none-any.whl.metadata (28 kB)
Collecting apify-fingerprint-datapoints>=0.11.0 (from scrapling[fetchers])
  Downloading apify_fingerprint_datapoints-0.11.0-py3-none-any.whl.metadata (14 kB)
Collecting msgspec>=0.20.0 (from scrapling[fetchers])
  Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: anyio>=4.12.1 in /usr/local/lib/python3.12/dist-packages (from scrapling[fetchers]) (4.12.1)
Collecting pyee<14,>=13 (from patchright==1.58.2->scrapling[fetchers])
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from patchright==1.58.2->scrapling[fetchers]) (3.3.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.12.1->scrapling[fetchers]) (3.11)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.14.0->scrapling[fetchers]) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.14.0->scrapling[fetchers]) (2026.2.25)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.14.0->scrapling[fetchers]) (3.0)
Downloading patchright-1.58.2-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 6.6 MB/s eta 0:00:00
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 5.2 MB/s eta 0:00:00
Downloading apify_fingerprint_datapoints-0.11.0-py3-none-any.whl (726 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 726.5/726.5 kB 12.1 MB/s eta 0:00:00
Downloading browserforge-1.2.4-py3-none-any.whl (37 kB)
Downloading cssselect-1.4.0-py3-none-any.whl (18 kB)
Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 7.9 MB/s eta 0:00:00
Downloading tld-0.13.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 10.6 MB/s eta 0:00:00
Downloading w3lib-2.4.1-py3-none-any.whl (21 kB)
Downloading scrapling-0.4.3-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.9/119.9 kB 6.1 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: w3lib, tld, pyee, msgspec, cssselect, apify-fingerprint-datapoints, scrapling, playwright, patchright, browserforge
Successfully installed apify-fingerprint-datapoints-0.11.0 browserforge-1.2.4 cssselect-1.4.0 msgspec-0.20.0 patchright-1.58.2 playwright-1.58.0 pyee-13.0.1 scrapling-0.4.3 tld-0.13.2 w3lib-2.4.1
Installing Playwright browsers...
(node:9739) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9790) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:9805) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
Installing Playwright dependencies...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Installing Playwright browsers...
Installing Playwright dependencies...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [5]:
#BASE PARA MANEJAR DADOS ITP
import pandas as pd
import numpy as np
import zipfile
import re

from io import BytesIO
import os
import time
import warnings
import time

warnings.filterwarnings('ignore')

In [6]:
#SELENIUM
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.proxy import Proxy, ProxyType
from selenium.webdriver.remote.client_config import ClientConfig
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.remote.remote_connection import RemoteConnection
from selenium.common.exceptions import WebDriverException, TimeoutException, NoSuchElementException, ElementClickInterceptedException, ElementNotInteractableException
from selenium.webdriver.common.print_page_options import PrintOptions


#SELENIUM STEALTH + UC
from selenium_stealth import stealth
import undetected_chromedriver as uc

#SCRAPLING
from scrapling.fetchers import StealthyFetcher

#OUTROS
from webdriver_manager.chrome import ChromeDriverManager
from urllib3.util import Retry, Timeout
import requests
from requests.adapters import HTTPAdapter
from bs4 import BeautifulSoup

##Extração e visualizações do ITP25/PR

Devido ao tamanho original do arquivo disponibilizado em https://radardatransparencia.atricon.org.br/downloads.html não era extrair de modo direto os dados do portal. Portanto foi realizado uma query filtrando os dados referentes as entidades paranaense avaliadas no ITP e criando um .zip alocado no github https://github.com/leonardosilva-sepl/Consulta_ITP24-25_PR/

In [7]:
url2025 = 'https://github.com/leonardosilva-sepl/Consulta_ITP24-25_PR/raw/refs/heads/main/itp2025_pr.zip'

In [8]:
filebytes2025 = BytesIO(requests.get(url2025).content)
zip2025 = zipfile.ZipFile(filebytes2025)
zip2025.extractall('questionario2025')

In [9]:
itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")
itp_2025_pr.head()

,id_avaliacao,entidade_id,entidade_nome,ibge,municipio_nome,uf,id_dimensao,dimensao_texto,id_criterio,criterio_texto,...,resposta_revisao,justificativa_avaliacao,justificativa_validacao,justificativa_revisao,link_avaliacao,link_validacao,link_revisao,imagem_avaliacao,imagem_validacao,imagem_revisao
0,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,652,1.1 Possui sítio oficial próprio na internet?,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
1,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,653,1.2 Possui portal da transparência próprio ou ...,...,NaN,NaN,NaN,NaN,https://planaltopr.equiplano.com.br:7030/trans...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
2,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,654,1.3 O acesso ao portal transparência está visí...,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
3,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,41,Informações Prioritárias,655,1.4 O site e o portal tranparência contêm fer...,...,NaN,NaN,NaN,NaN,https://planaltopr.equiplano.com.br:7030/trans...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN
4,25699,9446,Câmara Municipal de Planalto,4119806,Planalto,PR,42,Informações Institucionais,656,2.1 Divulga a sua estrutura organizacional?,...,NaN,NaN,NaN,NaN,https://www.cmvp.pr.gov.br/imprensa/institucio...,NaN,NaN,https://avalia-desenvolvimento.s3.amazonaws.co...,NaN,NaN

In [10]:
itp_2025_pr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276403 entries, 0 to 276402
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_avaliacao             276403 non-null  int64
 1   entidade_id              276403 non-null  int64
 2   entidade_nome            276403 non-null  object
 3   ibge                     276403 non-null  int64
 4   municipio_nome           276403 non-null  object
 5   uf                       276403 non-null  object
 6   id_dimensao              276403 non-null  int64
 7   dimensao_texto           276403 non-null  object
 8   id_criterio              276403 non-null  int64
 9   criterio_texto           276403 non-null  object
 10  exigibilidade            276403 non-null  object
 11  item_avaliacao           276403 non-null  object
 12  resposta_avaliacao       276403 non-null  bool
 13  resposta_validacao       254041 non-null  object
 14  resposta_revisao         16728 non-null   object
 15  justificativa_avaliacao  42291 non-null   object
 16  justificativa_validacao  29766 non-null   object
 17  justificativa_revisao    2401 non-null    object
 18  link_avaliacao           130311 non-null  object
 19  link_validacao           3678 non-null    object
 20  link_revisao             457 non-null     object
 21  imagem_avaliacao         82753 non-null   object
 22  imagem_validacao         10380 non-null   object
 23  imagem_revisao           2064 non-null    object
dtypes: bool(1), int64(5), object(18)
memory usage: 48.8+ MB

In [11]:
display(itp_2025_pr.item_avaliacao.value_counts(dropna = False),itp_2025_pr.resposta_avaliacao.value_counts(dropna = False),itp_2025_pr.resposta_validacao.value_counts(dropna = False),itp_2025_pr.resposta_revisao.value_counts(dropna = False))

item_avaliacao
Disponibilidade           137285
Atualidade                 41931
Filtros de Pesquisa        37566
Série Histórica            34475
Gravação de Relatórios     25146
Name: count, dtype: int64

resposta_avaliacao
True     250151
False     26252
Name: count, dtype: int64

resposta_validacao
True     201136
False     52905
NaN       22362
Name: count, dtype: int64

resposta_revisao
NaN      259675
True      14653
False      2075
Name: count, dtype: int64

Dataframe de links respostas ENTIDADE x QUESTÃO

In [12]:
itp_2025_pr = pd.read_csv('/content/questionario2025/itp2025_pr.csv', sep = ";")
itp_2025_pr.head()

#Filtrando questões avaliadas para prefeituras
questoes_prefeituras = itp_2025_pr[itp_2025_pr['entidade_nome']== 'Prefeitura Municipal de Abatiá'][['id_criterio','criterio_texto']].drop_duplicates()
questoes_prefeituras = questoes_prefeituras.reset_index(drop= True)

#Localizando as entidades "PREFEITURA"
itp_2025_pr['entidade_nome'] = itp_2025_pr.entidade_nome.str.lower()
entidades_pr = itp_2025_pr[['entidade_id','entidade_nome']].drop_duplicates().reset_index(drop= True)
prefeituras_pr = entidades_pr[entidades_pr['entidade_nome'].str.find('prefeitura')== 0]

#DF ENTIDADE X QUESTAO
links = itp_2025_pr[['id_criterio','criterio_texto','entidade_id','link_avaliacao']]
links = links[links['link_avaliacao'].notna()]
links = links[links['entidade_id'].isin(prefeituras_pr.entidade_id)].reset_index(drop= True)
links = links.drop_duplicates()
a = prefeituras_pr['entidade_id']
for id in questoes_prefeituras.id_criterio:
  a = pd.DataFrame(a).merge(links[links['id_criterio'] == id].drop_duplicates(subset= 'entidade_id', keep='last')[['entidade_id','link_avaliacao']],
                                                        on = 'entidade_id', how='left')
  a.rename(columns = {'link_avaliacao':id}, inplace = True)
a

,entidade_id,652,653,654,655,656,657,658,659,660,...,746,747,748,749,750,751,752,753,754,755
0,509,https://barracao.pr.gov.br/,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/\t,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/secretarias,https://barracao.pr.gov.br/common/uploads/arqu...,https://barracao.pr.gov.br/,...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://transparencia.betha.cloud/#/kW0Em6GT_f...,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-saude,https://consud-portal.ids.inf.br/portalcidadao...,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-saude,https://barracao.pr.gov.br/secretaria-educacao,https://barracao.pr.gov.br/secretaria-educacao
1,660,https://www.bocaiuvadosul.pr.gov.br/,https://bocaiuva.eloweb.net/portaltransparenci...,https://www.bocaiuvadosul.pr.gov.br/,https://www.bocaiuvadosul.pr.gov.br/,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretarias/9,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretaria...,https://www.bocaiuvadosul.pr.gov.br/secretaria...,...,NaN,https://bocaiuva.eloweb.net/portaltransparenci...,https://bocaiuva.eloweb.net/portaltransparenci...,https://www.bocaiuvadosul.pr.gov.br/legislacao...,https://www.bocaiuvadosul.pr.gov.br/secretarias/4,NaN,NaN,https://www.bocaiuvadosul.pr.gov.br/secretarias/4,https://www.bocaiuvadosul.pr.gov.br/pagina-site/5,https://www.bocaiuvadosul.pr.gov.br/educacao
2,2972,http://www.marmeleiro.pr.gov.br/,https://marmeleiro.atende.net/?pg=transparencia,http://www.marmeleiro.pr.gov.br/,ttps://marmeleiro.atende.net/?pg=transparencia,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/gr...,http://www.marmeleiro.pr.gov.br/,...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro.atende.net/transparencia/it...,https://consud-portal.ids.inf.br/portalcidadao...,https://marmeleiro.atende.net/transparencia/it...,https://marmeleiro-saudetransparente.ids.inf.b...,https://marmeleiro.atende.net/transparencia/gr...,https://marmeleiro.atende.net/transparencia/it...
3,1270,http://www.cianorte.pr.gov.br/site/,https://cianorte.oxy.elotech.com.br/portaltran...,http://www.cianorte.pr.gov.br/site/,https://www.cianorte.pr.gov.br/servicos/,https://cianorte.oxy.elotech.com.br/portaltran...,https://www.cianorte.pr.gov.br/secretarias/,https://www.cianorte.pr.gov.br/secretarias/,https://www.cianorte.pr.gov.br/secretarias/,http://www.cianorte.pr.gov.br/secretarias/,...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,https://cianorte.oxy.elotech.com.br/portaltran...,http://c3189prd.cloudmv.com.br/portal/agendaPr...,http://c3189prd.cloudmv.com.br/portal/listaEsp...,https://cianorte.pr.gov.br/pagina/194_RELACAO-...,https://cianorte.oxy.elotech.com.br/portaltran...,https://www.cianorte.pr.gov.br/secretaria/educ...,https://www.cianorte.pr.gov.br/pagina/83_Centr...
4,2949,https://www.marialva.pr.gov.br/,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://marialva.oxy.elotech.com.br/portaltran...,https://www.marialva.pr.gov.br/index.php?sessa...,https://www.marialva.pr.gov.br//index.php?sess...,https://www.marialva.pr.gov.br/,https://www.marialva.pr.gov.br/,...,https://www.ingadigital.com.br/transparencia/?...,NaN,NaN,https://marialva.oxy.elotech.com.br/portaltran...,https://www.marialva.pr.gov.br//index.php?sess...,NaN,https://www.ingadigital.com.br/transparencia/?...,https://www.ingadigital.com.br/transparencia/?...,NaN,https://www.ingadigital.com.br/transparencia/i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,4405,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/,https://santaines.pr.gov.br/,NaN,NaN,https://santaines.pr.gov.br/,https://santaines.eloweb.net/portaltransparenc...,https://santaines.pr.gov.br/cidade/noticia/cen...
393,1554,https://www.diamantedonorte.pr.gov.br/,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,https://www.diamantedonorte.pr.gov.br/conteudo...,https://www.diamantedonorte.pr.gov.br/expediente,...,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...,NaN,NaN,https://diamantedonorte.eloweb.net/portaltrans...,NaN,NaN,NaN,https://diamantedonorte.eloweb.net/portaltrans...,https://diamantedonorte.eloweb.net/portaltrans...
394,5196,https://telemacoborba.pr.gov.br/,https://telemacoborba.atende.net/transparencia/,https://telemacoborba.pr.gov.br/,https://telemacoborba.pr.gov.br/,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,https://telemacoborba.pr.gov.br/index.php/a-pr...,...,https://telemacoborba.atende.net/transparencia...,https://telemacoborba.atende.net/transparencia...,NaN,NaN,NaN,NaN,https://telemacoborba.atende.net/transparencia...,https://telemacoborba.pr.gov.br/index.php/info...,https://telemacoborba.atende.net/transparencia...,NaN
395,3341,https://www.novalondrina.pr.gov.br/,https://novalondrina.eloweb.net/portaltranspar...,https://www.novalondrina.pr.gov.br/,https://www.novalondrina.pr.gov.br/,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,...,NaN,https://dd-publico.serpro.gov.br/extensions/pa...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.eloweb.net/portaltranspar...,NaN,NaN,NaN,https://novalondrina.eloweb.net/portaltranspar...,https://novalondrina.vagou.ngf.net.br/lista-de...
396,3380,https://www.novatebas.pr.gov.br/,https://novatebas.oxy.elotech.com.br/portaltra...,https://www.novatebas.pr.gov.br/,https://www.novatebas.pr.gov.br/,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...,https://novatebas.oxy.elotech.com.br/portaltra...

In [13]:
#Detalhamento das questões
links_detalhes = itp_2025_pr[['entidade_id','id_criterio','criterio_texto','item_avaliacao','link_avaliacao','resposta_avaliacao','resposta_validacao','resposta_revisao']]
links_detalhes = links_detalhes[links_detalhes['entidade_id'].isin(prefeituras_pr.entidade_id)].reset_index(drop= True)
links_detalhes = links_detalhes.drop_duplicates()
links_detalhes

,entidade_id,id_criterio,criterio_texto,item_avaliacao,link_avaliacao,resposta_avaliacao,resposta_validacao,resposta_revisao
0,509,652,1.1 Possui sítio oficial próprio na internet?,Disponibilidade,https://barracao.pr.gov.br/,True,True,True
1,509,653,1.2 Possui portal da transparência próprio ou ...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True
2,509,654,1.3 O acesso ao portal transparência está visí...,Disponibilidade,https://barracao.pr.gov.br/\t,True,True,True
3,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://barracao.pr.gov.br/,True,True,True
4,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True
...,...,...,...,...,...,...,...,...
136943,3380,754,19.1 Divulga o plano de educação e o respectiv...,Série Histórica,NaN,True,True,NaN
136944,3380,754,19.1 Divulga o plano de educação e o respectiv...,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,True,NaN
136945,3380,754,19.1 Divulga o plano de educação e o respectiv...,Atualidade,NaN,True,True,NaN
136946,3380,755,19.2 Divulga a lista de espera em creches públ...,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,False,NaN
136947,3380,755,19.2 Divulga a lista de espera em creches públ...,Atualidade,NaN,True,False,NaN

Criando uma coluna de Resultado final, para localizar a resposta que foi utilizada para a visualização contida no site do ITP2025

In [14]:
links_detalhes['resultado_final'] = False
links_detalhes.loc[links_detalhes['resposta_validacao'] == True, 'resultado_final'] = True
links_detalhes.loc[links_detalhes['resposta_revisao'] == True, 'resultado_final'] = True
links_detalhes.loc[links_detalhes['resposta_revisao'] == False, 'resultado_final'] = False
links_detalhes.head()

,entidade_id,id_criterio,criterio_texto,item_avaliacao,link_avaliacao,resposta_avaliacao,resposta_validacao,resposta_revisao,resultado_final
0,509,652,1.1 Possui sítio oficial próprio na internet?,Disponibilidade,https://barracao.pr.gov.br/,True,True,True,True
1,509,653,1.2 Possui portal da transparência próprio ou ...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True,True
2,509,654,1.3 O acesso ao portal transparência está visí...,Disponibilidade,https://barracao.pr.gov.br/\t,True,True,True,True
3,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://barracao.pr.gov.br/,True,True,True,True
4,509,655,1.4 O site e o portal tranparência contêm fer...,Disponibilidade,https://transparencia.betha.cloud/#/kW0Em6GT_f...,True,True,True,True

In [15]:
links_detalhes.query("resposta_revisao.notna() and  resposta_revisao != resposta_validacao").value_counts("resultado_final")

resultado_final
False    544
True      42
Name: count, dtype: int64

In [16]:
links_detalhes.query('resultado_final == False and resposta_revisao == True ')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [17]:
links_detalhes.query('resultado_final == True and resposta_revisao == False')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [18]:
links_detalhes.query('resultado_final == False and resposta_validacao == True and resposta_revisao == True')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [19]:
links_detalhes.query('resultado_final == False and resposta_validacao == True and resposta_revisao.isna()')

Empty DataFrame
Columns: [entidade_id, id_criterio, criterio_texto, item_avaliacao, link_avaliacao, resposta_avaliacao, resposta_validacao, resposta_revisao, resultado_final]
Index: []

In [20]:
#visuallização das questões respondidas por prefeituras
links_detalhes[['id_criterio','criterio_texto']].drop_duplicates()

     id_criterio                                     criterio_texto
0            652      1.1 Possui sítio oficial próprio na internet?
1            653  1.2 Possui portal da transparência próprio ou ...
2            654  1.3 O acesso ao portal transparência está visí...
3            655  1.4 O site e o  portal tranparência contêm fer...
7            656        2.1 Divulga a sua estrutura organizacional?
..           ...                                                ...
298          751  18.3 Divulga a lista de espera de regulação pa...
299          752  18.4 Divulga lista dos medicamentos a serem fo...
303          753  18.5 Divulga os estoques de medicamentos das f...
306          754  19.1 Divulga o plano de educação e o respectiv...
310          755  19.2 Divulga a lista de espera em creches públ...

[91 rows x 2 columns]

Verificando possiveis erros de digitação nos links informados em uma questão de exemplo

In [21]:
teste = links_detalhes[['entidade_id',
                        'id_criterio',
                        'item_avaliacao',
                        'link_avaliacao',
                        'resultado_final']].query('item_avaliacao == "Disponibilidade"')

In [22]:
teste[teste.link_avaliacao.str.contains(",") == True]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
7927,4014,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/i...,True
8533,910,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
8534,910,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
8819,910,730,Disponibilidade,https://www.ingadigital.com.br/transparencia/?...,True
9806,1092,661,Disponibilidade,https://www.ingadigital.com.br/transparencia/i...,True
...,...,...,...,...,...
126138,4445,663,Disponibilidade,http://santamariana.pr.gov.br/index.php?sessao...,True
126285,4445,698,Disponibilidade,http://177.220.171.162:7474/transparencia/cont...,True
126357,4445,731,Disponibilidade,"O portal apresenta, no topo das páginas intern...",True
135273,1784,661,Disponibilidade,"www,figueira.pr.gov.br",False
135475,1784,734,Disponibilidade,"www,figueira.pr.gov.br",False

In [23]:
teste[teste.link_avaliacao.str.contains(" ") == True]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
8,509,657,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
1005,1270,659,Disponibilidade,https://www.cianorte.pr.gov.br/secretarias/,True
1007,1270,660,Disponibilidade,http://www.cianorte.pr.gov.br/secretarias/,True
1011,1270,661,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True
1035,1270,667,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True
...,...,...,...,...,...
134335,5318,699,Disponibilidade,: https://docmunicipal.com.br/executivolicitac...,True
134371,5318,724,Disponibilidade,https://www.tuneirasdooeste.pr.gov.br/fisco,True
136010,1554,726,Disponibilidade,https://diamantedonorte.1doc.com.br/b.php?pg=...,True
136259,5196,699,Disponibilidade,https://pit.tce.pr.gov.br/Obra,True
136268,5196,700,Disponibilidade,https://pit.tce.pr.gov.br/Obra,True

In [24]:
teste[teste.link_avaliacao.str.count("https") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
1658,266,676,Disponibilidade,https://antonioolinto.eloweb.net/portahttps://...,True
5210,1754,676,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",True
5231,1754,680,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
5380,1754,743,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
...,...,...,...,...,...
123661,2737,661,Disponibilidade,https://sapl.lapa.pr.leg.br/norma/pesquisar ...,True
123678,2737,666,Disponibilidade,https://lapa.atende.net/transparencia/grupo/re...,True
123735,2737,678,Disponibilidade,https://lapa.atende.net/transparencia/item/rel...,True
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
135722,4405,707,Disponibilidade,https://santaines.eloweb.net/portaltransparenc...,False

In [25]:
teste[teste.link_avaliacao.str.count(".com") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
7,509,656,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
8,509,657,Disponibilidade,https://barracao.pr.gov.br/common/uploads/arqu...,True
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
2228,2888,665,Disponibilidade,https://e-gov.betha.com.br/transparencia/01037...,True
2230,2888,666,Disponibilidade,https://e-gov.betha.com.br/transparencia/01037...,True
...,...,...,...,...,...
127373,4576,684,Disponibilidade,http://santoinaciopr.equiplano.com.br:7609/tra...,False
128657,3779,665,Disponibilidade,https://portal-prefeitura-pien.equiplano.cloud...,True
128904,3779,741,Disponibilidade,https://leismunicipais.com.br/a/pr/p/pien/decr...,True
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
134330,5318,697,Disponibilidade,https://tuneirasdooeste-pr.portaltp.com.br/con...,True

In [26]:
teste[teste.link_avaliacao.str.count("htt") >1]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
605,2972,659,Disponibilidade,https://marmeleiro.atende.net/transparencia/gr...,True
1658,266,676,Disponibilidade,https://antonioolinto.eloweb.net/portahttps://...,True
5210,1754,676,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",True
5231,1754,680,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
5380,1754,743,Disponibilidade,"""https://transparencia.betha.cloud/#/_c7j-Rm9f...",False
...,...,...,...,...,...
123678,2737,666,Disponibilidade,https://lapa.atende.net/transparencia/grupo/re...,True
123735,2737,678,Disponibilidade,https://lapa.atende.net/transparencia/item/rel...,True
127373,4576,684,Disponibilidade,http://santoinaciopr.equiplano.com.br:7609/tra...,False
133637,256,663,Disponibilidade,https://www.facebook.com/checkpoint/1501092823...,True
135722,4405,707,Disponibilidade,https://santaines.eloweb.net/portaltransparenc...,False

In [27]:
teste[teste.link_avaliacao.str.contains("http") == False]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final
596,2972,655,Disponibilidade,ttps://marmeleiro.atende.net/?pg=transparencia,True
2792,5470,656,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/ANEXO%...,True
2795,5470,657,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/Lei%20...,False
2863,5470,674,Disponibilidade,file:///C:/Users/Usuário/Downloads/Termo de co...,False
2864,5470,674,Disponibilidade,file:///C:/Users/Usu%C3%A1rio/Downloads/Termo%...,False
...,...,...,...,...,...
135474,1784,733,Disponibilidade,www.figueira.pr.gov.br,False
135475,1784,734,Disponibilidade,"www,figueira.pr.gov.br",False
135480,1784,739,Disponibilidade,www.figueira.pr.gov.br,False
135503,1784,747,Disponibilidade,www.figueira.pr.gov.br,False
135509,1784,748,Disponibilidade,www.figueira.pr.gov.br,False

## FUNÇÕES DE WEB SCRAPING

###Outras

In [28]:
def scrape_url(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    try:
        if pd.isna(url) or url == '':
            print("Erro: URL vazia ou não localizada para raspagem.")
            return False, "URL_EMPTY", "URL vazia ou não localizada para raspagem."
        else:
            response = requests.get(url, headers=headers, timeout=20)
            time.sleep(10)
            response.raise_for_status()
            time.sleep(10)
            soup = BeautifulSoup(response.content, 'html.parser')
            return soup, False, False

    except requests.exceptions.HTTPError as http_err:
        error_msg = f"HTTP error occurred for {url}: {http_err}"
        print(error_msg)
        error_cod = http_err.response.status_code
        error_msg = http_err.response.reason
        return False, error_cod, error_msg

    except requests.exceptions.ConnectionError as conn_err:
        error_msg = f"Connection error occurred for {url}: {conn_err}"
        print(error_msg)
        error_cod = type(conn_err).__name__
        error_msg = "ConnectionError"
        return False, error_cod, error_msg

    except requests.exceptions.Timeout as timeout_err:
        error_msg = f"Connection error occurred for {url}: {timeout_err}"
        print(error_msg)
        error_cod = type(timeout_err).__name__
        error_msg = "timeout_err"
        return False, error_cod, error_msg

    except requests.exceptions.RequestException as req_err:
        error_msg = f"An unexpected request error occurred for {url}: {req_err}"
        print(error_msg)
        error_cod = type(req_err).__name__
        error_msg = "req_err"
        return False, error_cod, error_msg

    except Exception as e:
        error_msg = f"An unexpected error occurred for {url}: {e}"
        print(error_msg)
        error_cod = e.response.status_code if hasattr(e, 'response') and hasattr(e.response, 'status_code') else type(e).__name__
        error_msg = e.response.reason if hasattr(e, 'response') and hasattr(e.response, 'reason') else str(e)
        return False, error_cod, error_msg

In [29]:
def abrir_driver_stealth():
  options = uc.ChromeOptions()
  options.add_argument("--window-size=1550,1000")
  options.add_argument("--disable-extensions")
  options.add_argument("--disable-application-cache")
  options.add_argument("--disable-gpu")
  options.add_argument("--no-sandbox")
  options.add_argument("--disable-setuid-sandbox")
  options.add_argument("--disable-dev-shm-usage")


  driver = uc.Chrome(options=options, headless=True, version_main=145)

  stealth(
      driver,
      languages=["en-US", "en"],
      vendor="Google Inc.",
      platform="Win32",
      webgl_vendor="Intel Inc.",
      renderer="Intel Iris OpenGL Engine",
      fix_hairline=True,
  )
  return driver

In [30]:
def scrape_info_stealth(driver, url):
    if not url:
        print("Erro: URL vazia ou não localizada para raspagem.")
        return False, "URL_EMPTY", "URL vazia ou não localizada para raspagem."

    try:
        driver.get(url)
        driver.implicitly_wait(20)
        response_text = driver.page_source
        soup = BeautifulSoup(response_text, "html.parser")
        return soup, False, False

    except Exception as e:
        err = f"Erro ao raspar {url}: {e}"
        print(err)
        return False, type(e).__name__, str(e)

In [31]:
def q_scraper(questao):
  q = questao
  qhtml= links_detalhes[['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']].iloc[1005:1011,:].query('id_criterio == @q and item_avaliacao =="Disponibilidade"').drop_duplicates(subset='entidade_id', keep = 'first')
  results = qhtml['link_avaliacao'].apply(scrape_url)
  extracted_data = results.apply(pd.Series)
  qhtml['pagina_scraped'] = extracted_data[0]
  qhtml['error_cod'] = extracted_data[1]
  qhtml['error_msg'] = extracted_data[2]
  return qhtml

In [32]:
def q_stealth(questao):
  q = questao
  qhtml= links_detalhes[['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']].query('id_criterio == @q and item_avaliacao =="Disponibilidade"').drop_duplicates(subset='entidade_id', keep = 'first')
  driver = abrir_driver_stealth()
  results = qhtml['link_avaliacao'].apply(lambda url: scrape_info_stealth(driver, url))
  qhtml['pagina_scraped'] = results.apply(lambda x: x[0])
  qhtml['error_cod'] = results.apply(lambda x: x[1])
  qhtml['error_msg'] = results.apply(lambda x: x[2])
  driver.quit()

  return qhtml

###Auxiliar

In [33]:
def padroniza_parametro(parametro):
    list_paramento = []

    for p in parametro:
        p = p.lower()
        list_paramento.append(p)

        p = p.upper()
        list_paramento.append(p)

        p = p.capitalize()
        list_paramento.append(p)

    return list_paramento

In [34]:
def verifica_lista(lista, parametro):
  lista_verificada = []
  if lista is not None:
    for el in lista:
      for p in parametro:
        if p in el:
          lista_verificada.append([el, True])


  return lista_verificada

In [35]:
### verifica se rede social esta online // tiktok ok, youtube ok, face/x/insta off


def url_online(url: str, timeout: int = 5) -> bool:
    HEADERS = {
              "User-Agent": (
                  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/122.0 Safari/537.36"
              )
          }

    try:
        # HEAD é mais leve; se o servidor não suportar, cai para GET
        resp = requests.head(
            url,
            headers=HEADERS,
            allow_redirects=True,
            timeout=timeout
        )
        if resp.status_code in (301, 302, 303, 307, 308):
            # já fizemos allow_redirects=True, então nesta altura
            # normalmente já estamos no destino final
            pass

        if resp.status_code in (403, 405):  # alguns bloqueiam HEAD
            resp = requests.get(
                url,
                headers=HEADERS,
                allow_redirects=True,
                timeout=timeout
            )

        return resp.status_code == 200
    except requests.exceptions.RequestException as e:
        print(f"Error checking if URL {url} is online: {e}") # Modified this line
        return False

def checker(urls):
    results = []

    for u in urls:
        data_result = {"url": u, "titulo": None, "nickname": None, "error_code": None}

        try:
            # Verificação inicial online
            if not url_online(u):
                data_result["error_code"] = "OFFLINE"
                results.append(data_result)
                continue

            r = requests.get(url=u, timeout=5, headers=HEADERS)
            data_result["error_code"] = r.status_code
            r.raise_for_status()

            soup = BeautifulSoup(r.text, "html.parser")
            data_result["titulo"] = soup.title.string.strip() if soup.title else "Sem título"

            data_result["html"]  = soup

            # Extração de Nickname (específico para TikTok)
            script_tag = soup.find("script", id="__UNIVERSAL_DATA_FOR_REHYDRATION__")
            if script_tag:
                data = json.loads(script_tag.string)
                user_info = data.get("__DEFAULT_SCOPE__", {}).get("webapp.user-detail", {}).get("userInfo", {})
                data_result["nickname"] = user_info.get("user", {}).get("uniqueId")

        except requests.exceptions.HTTPError as e:
            data_result["error_code"] = r.status_code
        except requests.exceptions.RequestException:
            data_result["error_code"] = "CONN_ERR"
        except Exception:
            data_result["error_code"] = "UNKNOWN_ERR"

        results.append(data_result)

    return results

In [36]:
def localiza_pai(element):
    try:
        return element.find_element(By.XPATH, "./..")
    except Exception as e:
        print(f"Erro ao localizar elemento pai: {e}")
        return None

In [37]:
def pontuador(lista_elementos, parametros_verificacao):
  elementos_pontuados = []
  pontos = 0
  for el in lista_elementos:
    if el is not None:
      try:
        h = el.get_attribute("outerHTML")
        t = el.text
        for p in parametros_verificacao:
          if p in t:
            pontos += 1

        elementos_pontuados.append([el, pontos, h])
        pontos = 0


      except Exception as e:
        print(f"Erro ao obter atributos do elemento: {e}")
        pass
  elementos_pontuados = sorted(elementos_pontuados, key=lambda x: x[1], reverse=True)
  return elementos_pontuados

In [38]:
js_sibling = """var elem = arguments[0];
                var sibs = [];
                if (elem.parentNode) {
                    elem = elem.parentNode.firstChild;
                    do {
                        if (elem.nodeType === 1) { // Only include element nodes
                            sibs.push(elem);
                        }
                    } while (elem = elem.nextSibling)
                }
                return sibs;
                """

In [39]:
def localiza_irmaos(elemento):
  return elemento.find_elements(By.XPATH, "./following-sibling::*")

In [40]:
def bt_aceito(driver):
  bt = ["Aceito","aceito","ACEITO"]
  for b in bt:
    ac = driver.find_elements(By.XPATH, f"//*[contains(text(),'{b}')]")
    for a in ac:
      try:
        clicker(driver, a)
      except:
        pass

###Principal

In [41]:
def abrir_driver():

  # Configuracao de opcoes
  options = Options()
  options.accept_insecure_certs = True
  options.add_argument("--headless=new")
  options.add_argument("--window-size=1920,1080")
  options.add_argument("--no-sandbox")
  options.add_argument("--disable-dev-shm-usage")
  options.add_argument("--disable-gpu")
  driver = webdriver.Chrome(options=options)

  # Configuracao de cliente
  retries = Retry(total=1, connect=1, read=1, backoff_factor=0.5)
  driver.command_executor._conn.connection_pool_kw['retries'] = retries
  driver.set_page_load_timeout(90)
  driver.get('chrome://settings/')
  driver.execute_script("chrome.settingsPrivate.setDefaultZoom(0.50);")

  return driver

In [42]:
def busca_todo_atributos(driver, element):
    #Retorna um dict com os atributos de cada elemento {nome_atributo: valor}
    js = """
        var items = {};
        for (var i = 0; i < arguments[0].attributes.length; i++) {
            items[arguments[0].attributes[i].name] = arguments[0].attributes[i].value;
        }
        return items;
    """
    return driver.execute_script(js, element)

In [43]:
def localiza_clicks(driver, parametro_navegacao):
    # LOCALIZA SE HÁ ELEMENTOS COM TEXTOS SELECIONADOS
    lista_elementos = []
    vistos = set()

    for p in parametro_navegacao:
        try:
            els = driver.find_elements(By.XPATH, f'//*[contains(text(),"{p}")]') #BUSCA ELEMENTOS QUE TENHAM TEXTO P
            if not els:
              els = []

            elementos_atrib = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]") #BUSCA ELEMENTOS QUE TENHAM ATRIBUTO P
            if not elementos_atrib:
              elementos_atrib = []

            for el in els + elementos_atrib:
                try:
                    txt = el.text
                    html = el.get_attribute("outerHTML")
                    id = (txt, html)

                    if id not in vistos and el not in lista_elementos:
                        lista_elementos.append(el)
                        vistos.add(id)
                except:
                    continue

        except NoSuchElementException:
            print('Elemento não localizado')
            pass

    return lista_elementos

In [44]:
#Tenta realizar um click simples ou click JS  no elemento chamado
def clicker(driver,el):
  try:
    el.click()
    driver.implicitly_wait(5)

  except (ElementClickInterceptedException, ElementNotInteractableException):
    driver.execute_script('arguments[0].click();',el)
    driver.implicitly_wait(5)

In [45]:
#retorna todo texto para os elementos desejados
def busca_todo_texto(driver, local):
    #LOCALIZACAO
    elements = driver.find_elements(By.CSS_SELECTOR, local)

    #lista de texto
    lista_text = []
    lista_html = []
    for e in elements:
      try:
        if e.text is not None:
          lista_text.append(e.text)
          lista_html.append(e.get_attribute("outerHTML"))

      except Exception as e:
        print(f"Erro ao obter atributos do elemento: {e}")
        pass

    lista_text = list(set(lista_text))
    lista_html = list(set(lista_html))
    return lista_text, lista_html

In [46]:
def verifica_texto(driver, texto):

  return

In [47]:
#retorna link para uma parte de texto do link desejado
def busca_link(driver, parametro):
    #FUNCAO DE LOCALIZACAO
    #driver: driver seleneium ativo
    #parametro: lista de parametro string dos atributos que serão buscados, ex.: "radar", "horario"

    lista_elementos = [] #elementos que contenham algum p
    lista = []
    link = []
    html = []

    for p in parametro:
      elementos = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{p}')]]") #PARAMETRO DE BUSCA EM ATRIBUTOS

      if elementos is not None:
        lista_elementos.extend(elementos)

    for el in lista_elementos:
      if el.tag_name != 'input' and el.tag_name != 'option' and el.tag_name != 'form' and el.tag_name != "select" and el.get_attribute("option") == None:
        try:
          atribs = busca_todo_atributos(driver,el)

          for nome_atributo, valor_atributo in atribs.items():
            if (nome_atributo is not None) and (valor_atributo is not None) and any(p in valor_atributo for p in parametro):
              link.append(el.get_attribute(nome_atributo))
              html.append(el.get_attribute("outerHTML"))
              lista.append(el)

        except Exception as e:
          print(f"Erro ao obter atributos do elemento: {e}")

    lista = list(set(lista))
    link = list(set(link))
    html = list(set(html))

    return link, html, lista

In [48]:
def buscador(driver, tipo_busca, busca):
    match tipo_busca:
      case "texto":
            elemento, html_elemento = busca_todo_texto(driver, busca)

      case "link":
            elemento, html_elemento, lista = busca_link(driver, busca)

    return elemento, html_elemento, lista

In [49]:
def filtro_questao(questao, i=None, k= None):
  qhtml = links_detalhes[
           ['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']
           ].query(
                  'id_criterio == @questao and item_avaliacao == "Disponibilidade"'
                  ).drop_duplicates(
                                    subset='entidade_id', keep='first'
                                    ).reset_index(drop=True).iloc[i:k, :].reset_index(drop=True) #iloc somente para verificação por partes
  return qhtml

In [50]:
def verifica_bloqueio(driver, frases_bloqueio):
  texto = driver.find_element(By.XPATH, "//body")

  # Verifica se alguma frase f de frases_bloqueio é uma substring de qualquer texto t em textos_corpo
  bloqueio = any(f in t for f in frases_bloqueio for t in textos_corpo)

  return bloqueio

In [51]:
'''#recorrencia
url_inicial = driver.current_url
url_click = driver.current_url



eh_recorrencia = False #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
  #fluxo normal




eh_recorrencia = True
if url_inicial == url_click

  #fluxo normal
  #tenta rasspar todo elemento contento paramento
  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao

if url_inicial != url_click:
  #fluxo com reacessos a pagina inicial
  #tenta rasspar todo elemento contento paramento
  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao, geralmente em elementos js

  while url_inicial != url_click #volta a pagina hub
    url_click = driver.current_url
    driver.back()
    time.sleep(2)'''

'#recorrencia\nurl_inicial = driver.current_url\nurl_click = driver.current_url\n\n\n\neh_recorrencia = False #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS\n  #fluxo normal\n\n\n\n\neh_recorrencia = True\nif url_inicial == url_click\n\n  #fluxo normal\n  #tenta rasspar todo elemento contento paramento\n  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao\n\nif url_inicial != url_click:\n  #fluxo com reacessos a pagina inicial\n  #tenta rasspar todo elemento contento paramento\n  #se pontuacao baixa tenta interagir com elemento contendo paramento de navegacao, geralmente em elementos js\n\n  while url_inicial != url_click #volta a pagina hub\n    url_click = driver.current_url\n    driver.back()\n    time.sleep(2)'

In [52]:
def scrap_selenium(url, tipo_busca = None):

  inicio = time.time()
  busca = ["radardatransparencia.atricon"]        #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
  parametro_navegacao = padroniza_parametro(["Radar"]) #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
  html_selenium = None
  elemento = None
  html_elemento = None
  error_cod = False
  error_msg = False
  texto_click = []
  html_click = []
  elemento_f = None
  html_elemento_f = None
  duracao = 0

  if pd.isna(url) or (isinstance(url, str) and not url.strip()):
    print(f"Erro: URL inválida recebida: {repr(url)}")
    return None, None, None, "URL_INVALID", "URL vazia, None ou NaN.", None, None, None

  if ("https://radardatransparencia.atricon" in url) or ("https://radar.tce.mt." in url) or ("https://www.tce." in url):
    return None, None, None, "URL_VERIFY", "Foi verificado que a URL fornecida se refere diretamente ao Radar Transparencia ou TCE-MT", None, None, None

  driver = None

  try:
    driver = abrir_driver()
    driver.set_page_load_timeout(30)
    driver.get(url)
    wait = WebDriverWait(driver, 40)

    try: ##Parâmetros HTML para busca inicial
        wait.until(
            EC.any_of(EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                      EC.presence_of_all_elements_located((By.TAG_NAME,"body")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                      )
            )

        html_selenium = driver.page_source

    except TimeoutException as e:
        html_selenium = driver.page_source
        error_cod = type(e).__name__
        error_msg = str(e)
        print(f"Timeout esperando carregamento principal para {url}, seguindo mesmo assim.")

    try:
        url_inicial = driver.current_url
        driver.implicitly_wait(10)
        elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)
        elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)

        if not elemento:
          try:
            bt_aceito(driver)
            lista_elementos = localiza_clicks(driver, parametro_navegacao)
            if lista_elementos:
              for el in lista_elementos:
                texto_click.append(el.text)
                html_click.append(el.get_attribute("outerHTML"))

                clicker(driver,el)
                url_click = driver.current_url

                elemento, html_elemento, lista_elementos = buscador(driver,tipo_busca, busca)

                if not lista_elementos and url_click == url_inicial:
                  pass

                if not lista_elementos and url_click != url_inicial:
                  while url_click != url_inicial:
                    url_click = driver.current_url
                    driver.back()
                    driver.implicitly_wait(5)
                  pass

                if lista_elementos:
                  break

            if not lista_elementos:
              frases_bloqueio = ["Performing security verification", "Sorry, you have been blocked","403 Forbidden",
                                 "A página solicitada não foi encontrada no servidor.","The request could not be satisfied.",
                                 "Desculpe, não conseguimos encontrar o que você está procurando.",
                                 "This page is used to test the proper operation ","ERRO 500","Bad Gateway",
                                 "Blocked request this country"
                                ]
              bloqueio = verifica_bloqueio(driver, frases_bloqueio)

              if bloqueio == True:
                error_cod = "URL_BLOCKED"
                error_msg = "URL bloqueada"

              else:
                html_selenium = driver.page_source
                error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
                error_msg = f"Nenhum elemento final localizado na página contendo: {busca} ou de interação contendo: {parametro_navegacao}"


          except NoSuchElementException as e:
              error_cod = "NoSuchElementException"
              error_msg = str(e)
              textos_corpo, html_corpo = busca_todo_texto(driver, "body")
              texto_click = textos_corpo
              html_click = html_corpo


    except Exception as e:
        if not error_cod:
            error_cod = type(e).__name__
            error_msg = str(e)
        print(f"Erro na busca de elementos para {url}: {e}")

  except WebDriverException as e:
      error_cod = type(e).__name__
      error_msg = str(e)
      print(f"WebDriver error for {url}: {error_msg}")

  except Exception as e:
      error_cod = type(e).__name__
      error_msg = str(e)
      print(f"General error for {url}: {error_msg}")

  finally:
    if (not elemento and not html_elemento) and (not error_msg and not error_cod):
      error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
      error_msg = f"Nenhum elemento final localizado na página contendo: {busca} ou de interação contendo: {parametro_navegacao}"

    if (elemento and html_elemento) or (texto_click and html_click):
      error_cod = None
      error_msg = None

    duracao = round(time.time() - inicio, 2)

    if driver:
      print(f"Tempo de execução para {url}: {duracao}s")
      driver.quit()

  return html_selenium, elemento, html_elemento, error_cod, error_msg, texto_click, html_click, duracao

In [53]:
def q_selenium(questao, i=0, k= None):

##Selecionando do DF a questão desejada

  qhtml = filtro_questao(questao, i, k)


##Iniciando o driver e aplicando o scraper por url

  results = []
  for idx, url in enumerate(qhtml['link_avaliacao'], start=1):
      results.append(scrap_selenium(url, "link")) #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS
      if idx % 10 == 0:
          print(idx)


##Adicionando os resultados no DF
  results = pd.Series(results)
  qhtml['pagina_scraped'] = results.apply(lambda x: x[0])
  qhtml['elemento_final']        = results.apply(lambda x: x[1])
  qhtml['html_elemento_final']   = results.apply(lambda x: x[2])
  qhtml['error_cod']       = results.apply(lambda x: x[3])
  qhtml['error_msg']       = results.apply(lambda x: x[4])
  qhtml['elemento_interacao_1']       = results.apply(lambda x: x[5])
  qhtml['html_elemento_interacao_1']       = results.apply(lambda x: x[6])
  qhtml['duracao_segundos'] = results.apply(lambda x: x[7])

  return qhtml

##TESTES

###UNITARIO

https://saojosedaboavista.pr.gov.br/  verificar elemento radar não acessável

In [ ]:
'''from base64 import urlsafe_b64decode, urlsafe_b64encode


from selenium.webdriver.common.virtual_authenticator import (
    Credential,
    VirtualAuthenticatorOptions,
)'''

In [ ]:
'''BASE64_ENCODED_PK = """
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDbBOu5Lhs4vpowbCnmCyLUpIE7JM9sm9QXzye2G+jr+Kr
MsinWohEce47BFPJlTaDzHSvOW2eeunBO89ZcvvVc8RLz4qyQ8rO98xS1jtgqi1NcBPETDrtzthODu/gd0sjB2Tk3TLuBGV
oPXt54a+Oo4JbBJ6h3s0+5eAfGplCbSNq6hN3Jh9YOTw5ZA6GCEy5l8zBaOgjXytd2v2OdSVoEDNiNQRkjJd2rmS2oi9AyQ
FR3B7BrPSiDlCcITZFOWgLF5C31Wp/PSHwQhlnh7/6YhnE2y9tzsUvzx0wJXrBADW13+oMxrneDK3WGbxTNYgIi1PvSqXlq
GjHtCK+R2QkXAgMBAAECggEAVc6bu7VAnP6v0gDOeX4razv4FX/adCao9ZsHZ+WPX8PQxtmWYqykH5CY4TSfsuizAgyPuQ0
+j4Vjssr9VODLqFoanspT6YXsvaKanncUYbasNgUJnfnLnw3an2XpU2XdmXTNYckCPRX9nsAAURWT3/n9ljc/XYY22ecYxM
8sDWnHu2uKZ1B7M3X60bQYL5T/lVXkKdD6xgSNLeP4AkRx0H4egaop68hoW8FIwmDPVWYVAvo8etzWCtibRXz5FcNld9MgD
/Ai7ycKy4Q1KhX5GBFI79MVVaHkSQfxPHpr7/XcmpQOEAr+BMPon4s4vnKqAGdGB3j/E3d/+4F2swykoQKBgQD8hCsp6FIQ
5umJlk9/j/nGsMl85LgLaNVYpWlPRKPc54YNumtvj5vx1BG+zMbT7qIE3nmUPTCHP7qb5ERZG4CdMCS6S64/qzZEqijLCqe
pwj6j4fV5SyPWEcpxf6ehNdmcfgzVB3Wolfwh1ydhx/96L1jHJcTKchdJJzlfTvq8wwKBgQDeCnKws1t5GapfE1rmC/h4ol
L2qZTth9oQmbrXYohVnoqNFslDa43ePZwL9Jmd9kYb0axOTNMmyrP0NTj41uCfgDS0cJnNTc63ojKjegxHIyYDKRZNVUR/d
xAYB/vPfBYZUS7M89pO6LLsHhzS3qpu3/hppo/Uc/AM/r8PSflNHQKBgDnWgBh6OQncChPUlOLv9FMZPR1ZOfqLCYrjYEqi
uzGm6iKM13zXFO4AGAxu1P/IAd5BovFcTpg79Z8tWqZaUUwvscnl+cRlj+mMXAmdqCeO8VASOmqM1ml667axeZDIR867ZG8
K5V029Wg+4qtX5uFypNAAi6GfHkxIKrD04yOHAoGACdh4wXESi0oiDdkz3KOHPwIjn6BhZC7z8mx+pnJODU3cYukxv3WTct
lUhAsyjJiQ/0bK1yX87ulqFVgO0Knmh+wNajrb9wiONAJTMICG7tiWJOm7fW5cfTJwWkBwYADmkfTRmHDvqzQSSvoC2S7aa
9QulbC3C/qgGFNrcWgcT9kCgYAZTa1P9bFCDU7hJc2mHwJwAW7/FQKEJg8SL33KINpLwcR8fqaYOdAHWWz636osVEqosRrH
zJOGpf9x2RSWzQJ+dq8+6fACgfFZOVpN644+sAHfNPAI/gnNKU5OfUv+eav8fBnzlf1A3y3GIkyMyzFN3DE7e0n/lyqxE4H
BYGpI8g==
""".strip()

def abrir_driver_cred():
    # Configuracao de opcoes
    options = Options()
    options.accept_insecure_certs = True
    options.add_argument("--headless=new")
    options.add_argument("--window-size=1920,1080")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")

    driver = webdriver.Chrome(options=options)

    # 1) Configurar Virtual Authenticator apto a Resident Credential
    va_options = VirtualAuthenticatorOptions()
    va_options.protocol = VirtualAuthenticatorOptions.Protocol.CTAP2
    va_options.has_resident_key = True
    va_options.has_user_verification = True
    va_options.is_user_verified = True
    driver.add_virtual_authenticator(va_options)  # registra o autenticador virtual[page:3]

    # 2) Criar e adicionar uma Resident Credential
    credential_id = bytearray({5, 3, 3, 4})  # id da credencial (ajuste se quiser)
    rp_id = "https://douradina.pr.gov.br/"                      # domínio do seu RP (use o domínio real do site)
    user_handle = bytearray({1})             # identificador do usuário
    private_key = urlsafe_b64decode(BASE64_ENCODED_PK)
    sign_count = 0

    resident_credential = Credential.create_resident_credential(
        credential_id,
        rp_id,
        user_handle,
        private_key,
        sign_count,
    )  # mesma assinatura do exemplo oficial em Python[page:3]

    driver.add_credential(resident_credential)  # injeta a credencial no autenticador virtual[page:3]

    # 3) Restante da sua configuração de cliente
    retries = Retry(total=1, connect=1, read=1, backoff_factor=0.5)
    driver.command_executor._conn.connection_pool_kw["retries"] = retries
    driver.set_page_load_timeout(90)
    driver.get("chrome://settings/")
    driver.execute_script("chrome.settingsPrivate.setDefaultZoom(0.75);")

    return driver'''

In [ ]:
a = q_selenium(664,62,63)
a

Tempo de execução para http://s2.asp.srv.br/etransparencia.pm.santamonica.pr/servlet/wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg=: 76.22s

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
0,4447,664,Disponibilidade,http://s2.asp.srv.br/etransparencia.pm.santamo...,True,"<html lang=""pt""><head>\n<meta name=""generator""...",[https://radardatransparencia.atricon.org.br/r...,"[<a id=""ygtvlabelel20"" class=""BasicNodeTextDec...",None,None,"[, RADAR NACIONAL DE TRANSPARÊNCIA]","[<input type=""hidden"" name=""GXState"" value=""{&...",76.22

In [ ]:
a.html_elemento_interacao_1[0][0]

'<a class="d-flex p-4 transition h-100" title="Link de acesso ao site Radar da Transparência Pública" href="https://radar.tce.mt.gov.br/extensions/radar-da-transparencia-publica/radar-da-transparencia-publica.html" target="_blank">\n                    <article class="text-center">\n                        <img class="w-100 p-4" src="https://www.pien.pr.gov.br/themes/prefeitura-web/assets/images/logo-radar.png" title="Brasão da Radar da Transparência Pública" alt="[Brasão da Radar da Transparência Pública]">\n                        <h3>Radar da Transparência Pública</h3>\n                    </article>\n                </a>'

In [ ]:
a.html_elemento_interacao_1[0]

['<a href="/portal-da-transparencia/radar/">\n\t\t\t\t\t\t\t<img decoding="async" src="https://cr2.co/wp-content/uploads/logo-radar.png" title="" alt="logo-radar" loading="lazy">\t\t\t\t\t\t\t\t</a>']

In [ ]:
a.html_elemento_interacao_1[0]

['<a target="_blank" rel="noopener" href="https://tce.pr.gov.br/transparencia/radar-da-transparencia.htm" title="Radar Transparência Pública" class="link-acesso-rapido"><span class="icon-acesso-rapido"><i class="fas fa-external-link-square-alt"></i></span> <span class="titulo-servico">Radar Transparência Pública</span></a>',
 '<span class="titulo-servico">Radar Transparência Pública</span>']

In [58]:
driver =  abrir_driver()
inicio = time.time()
texto_click = []
html_click = []
e = None
f = None
b = ["radardatransparencia.atricon"]
p = padroniza_parametro(["Radar"])
try:
  driver.set_page_load_timeout(30)
  driver.get("https://fazendariogrande.pr.gov.br/transparencia")


except Exception as e:
  print(e)

wait = WebDriverWait(driver, 40)
print(round(time.time() - inicio, 2),"in")

try:
  wait.until(
    EC.any_of(EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
              EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main")),
              EC.presence_of_all_elements_located((By.TAG_NAME,"body"))
              )
    )
  print(round(time.time() - inicio, 2),"wt")

except TimeoutException:
  print("Timeout esperando carregamento principal, seguindo mesmo assim.")



try:
  url_inicial = driver.current_url
  driver.implicitly_wait(10)
  elemento, html_elemento, lista_elementos = buscador(driver,"link", b)
  elemento, html_elemento, lista_elementos = buscador(driver,"link", b)
  print(round(time.time() - inicio, 2),"b0")

  if not elemento:
    try:

      print(round(time.time() - inicio, 2),"bt")
      bt_aceito(driver)
      lista_elementos = []
      vistos = []
      for pi in p:
          try:
              print(round(time.time() - inicio, 2),"find")
              els = driver.find_elements(By.XPATH, f'//*[contains(text(),"{pi}")]') #BUSCA ELEMENTOS QUE TENHAM TEXTO P

              if not els:
                els = []

              print(round(time.time() - inicio, 2),"find1")
              elementos_atrib = driver.find_elements(By.XPATH, f"//*[@*[contains(.,'{pi}')]]") #BUSCA ELEMENTOS QUE TENHAM ATRIBUTO P
              print(round(time.time() - inicio, 2),"find2")

              if not elementos_atrib:
                elementos_atrib = []

              for el in els + elementos_atrib:
                  try:
                      txt = el.text
                      html = el.get_attribute("outerHTML")
                      id = (txt, html)

                      if id not in vistos and el not in lista_elementos:
                          lista_elementos.append(el)
                          vistos.add(id)
                  except:
                      continue

          except NoSuchElementException:
              print('Elemento não localizado')
              pass




      if lista_elementos:
        for el in lista_elementos:
          print(round(time.time() - inicio, 2),"el")

          texto_click.append(el.text)
          html_click.append(el.get_attribute("outerHTML"))

          clicker(driver,el)
          driver.implicitly_wait(5)
          url_click = driver.current_url

          elemento, html_elemento, lista_elementos = buscador(driver,"link", b)

          if not lista_elementos and url_click == url_inicial:
            pass

          if not lista_elementos and url_click != url_inicial:
            while url_click != url_inicial:
              print(round(time.time() - inicio, 2),"url")

              url_click = driver.current_url
              driver.back()
              driver.implicitly_wait(5)
            pass

          if lista_elementos:
            break

      if not lista_elementos:
        print(round(time.time() - inicio, 2),"bl1")
        frases_bloqueio = ["Performing security verification", "have been blocked","403 Forbidden",
                            "A página solicitada não foi encontrada","The request could",
                            "Desculpe, não conseguimos",
                            "This page is used","ERRO 500","Bad Gateway",
                            "Blocked request"]


        texto_pg = driver.find_element(By.TAG_NAME,"*").text

        # Verifica se alguma frase f de frases_bloqueio é uma substring de qualquer texto t em textos_corpo
        print(round(time.time() - inicio, 2),"bl2")
        bloqueio = any(f in texto_pg for f in frases_bloqueio)
        print(round(time.time() - inicio, 2),"bl")


        if bloqueio == True:
          error_cod = "URL_BLOCKED"
          error_msg = "URL bloqueada"

        else:
          html_selenium = driver.page_source
          error_cod = "NENHUM_ELEMENTO_LOCALIZADO"
          error_msg = f"Nenhum elemento final localizado na página contendo: {p} ou de interação contendo: {b}"


    except NoSuchElementException as e:
        error_cod = "NoSuchElementException"
        error_msg = str(e)
        textos_corpo, html_corpo = busca_todo_texto(driver, "body")
        texto_click = textos_corpo
        html_click = html_corpo


except Exception as e:
  if not error_cod:
      error_cod = type(e).__name__
      error_msg = str(e)
  print(f"Erro na busca de elementos para : {e}")

0.24 in
0.44 wt
20.54 b0
20.54 bt
50.63 find
60.67 find1
70.7 find2
70.7 find
80.72 find1
90.76 find2
90.76 find
100.78 find1
110.83 find2
110.83 bl1
110.89 bl2
110.89 bl

In [57]:
driver.find_element(By.TAG_NAME,"*").text

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=0, read=1, redirect=None, status=None)) after connection broken by 'NewConnectionError("HTTPConnection(host='localhost', port=53993): Failed to establish a new connection: [Errno 111] Connection refused")': /session/ac66b60fadab1aa32f365c39e1efb50e/element

MaxRetryError: HTTPConnectionPool(host='localhost', port=53993): Max retries exceeded with url: /session/ac66b60fadab1aa32f365c39e1efb50e/element (Caused by NewConnectionError("HTTPConnection(host='localhost', port=53993): Failed to establish a new connection: [Errno 111] Connection refused"))

In [ ]:
driver.close()

'URL_BLOCKED'

'Acesso à informação\nAcessibilidade\nMapa do Site\nAtende.Net\nNotícias\nAutoatendimento\nTransparência\nDiário Oficial\nTransparência Escolar\nConsulta de Vagas de CMEIs\nConsulta de Protocolo\nEmissão de Protocolo\nConsulta Pública PMSB\nAUTOATENDIMENTO\nOlá,\nO Autoatendimento é um portal focado em oferecer acesso aos serviços de forma simples, rápida e personalizada, pois oferece recursos que atendem as necessidades dos usuários de acordo com seu perfil.\nAcessar\nCadastre-se\nAcessar sem login\nEstão Disponíveis\n356\nServiços\n285\nDispensam Login\n71\nNecessitam Login\n238\nServiços Informativos\nAcesso ao Sistema de Nota Fiscal de Serviço Eletrônica\nEmissão do Recibo de Pagamento\nEmissão de Guias IPTU\nEmissão da Certidão Negativa de Débitos - CND\nConsulta de Processo Digital (Protocolo)\nLicitações\nNota Fiscal Eletrônica\nEscrita Fiscal\nPortal da Transparência\nAcesso à Informação\nCarta de Serviços\nESTATÍSTICAS IBGE\nÁrea da unidade territorial [2024]\n745.748 Km²\nPopulação estimada [2025]\n58.734 pessoas\nSalário médio mensal [2023]\n2,40 salários mínimos\nIDHM [2010]\n0.774\nPIB per capita [2021]\nR$ 54.115,26\nÁrea [2022]\n746,00 Km²\nDensidade demográfica [2022]\n74,87\n©Fonte: IBGE\nVer Mais\nPregão 65/2025 - Prova de COnceito (IPM) - dia 5\nRegistro de preços para contratação de fornecimento de sistema de gest...\nTransmitido em: 12/12/2025 08:30\nPregão 65/2025 - Prova de COnceito (IPM) - dia 4\nRegistro de preços para contratação de fornecimento de sistema de gest...\nTransmitido em: 11/12/2025 08:30\nPregão 65/2025 - Prova de COnceito (IPM) - dia 3\nRegistro de preços para contratação de fornecimento de sistema de gest...\nTransmitido em: 10/12/2025 08:30\nPregão 65/2025 - Prova de COnceito (IPM) - dia 2\nRegistro de preços para contratação de fornecimento de sistema de gest...\nTransmitido em: 09/12/2025 08:30\nPregão 65/2025 - Prova de COnceito (IPM) - dia 1\nRegistro de preços para contratação de fornecimento de sistema de gest...\nTransmitido em: 08/12/2025 08:30\nVer Mais\nMarço\n2026\nHoje\nDom\nSeg\nTer\nQua\nQui\nSex\nSáb\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n1\n2\n3\n4\n30\nVer Mais\nAtenção, motoristas!\nAtenção, motoristas!...\nKatiane Pech representa Marechal Rondon no Miss Paraná 2025 da franquia BMW Eventos\nKatiane Pech representa Marechal Rondon no Miss Paraná 2025 da franquia BMW Eventos...\nAtenção, rondonenses!\nAtenção, rondonenses!...\nPrefeitura rondonense oferece cursos NR-11 para operadores de empilhadeira e de paleteira elétrica\nPrefeitura rondonense oferece cursos NR-11 para operadores de empilhadeira e de paleteira elétrica...\nHoje é o Dia do Desafio!\nNa prefeitura, as atividades aconteceram logo no início da manhã....\n25 de maio, Dia da Indústria!\n25 de maio, Dia da Indústria!...\nVem aí a Expo Rondon 2025, de 23 a 27 de julho!\nVem aí a Expo Rondon 2025, de 23 a 27 de julho!...\nFestival Brescianini - 24 de maio\nFestival Brescianini - 24 de maio...\nFestival Brescianini - 23 de maio\nFestival Brescianini - 23 de maio...\nPrograma ProÁgua terá sequência em 2026 em Marechal Rondon\n...\nCarreta da Expedição do Conhecimento chega a Porto Mendes e integra programação do Acampamento Pais ...\n...\n06/02/2026 16h26\nConfira os ganhadores do Torneio Internacional de Pesca à Corvina em Porto Mende...\n...\n29/03/2026 08h51\nIniciado o Torneio de Pesca à Corvina\n...\n29/03/2026 08h46\n1ª Corrida e Caminhada alusiva ao Dia Internacional da Mulher reúne centenas de ...\n...\n28/03/2026 08h41\nIdosos de Marechal Rondon participam de evento esportivo em Pontal do Paraná\n27/03/2026 16h00\n1ª Corrida e Caminhada alusiva ao Dia Internacional da Mulher acontece neste sáb...\n...\n27/03/2026 15h58\nIniciadas as obras para pavimentação asfáltica na Linha Sanga do Mico\n...\n27/03/2026 08h36\nMarechal Cândido Rondon inicia Campanha de Vacinação contra a Influenza e reforç...\n...\n27/03/2026 08h33\nMarechal Cândido Rondon recebe caminhão para a coleta seletiva\n...\n26/03/2026 15h51\nAudiência pública sobre Lei de Diretrizes Orçamentárias acontece no dia 8 de abr...\n...\n26/03/2026 15h36\nCentro de Referência Paralímpico é lançado em Marechal Cândido Rondon\n...\n26/03/2026 15h33\nServidores da Secretaria de Educação participam de capacitação sobre a plataform...\n...\n26/03/2026 09h22\nObras do campo Society no bairro Alvorada avançam em Marechal Cândido Rondon\n...\n25/03/2026 15h30\nSecretaria de Educação recebe certificado em formação continuada\n...\n25/03/2026 10h06\nSaúde de Marechal Cândido Rondon participa do "Saúde em Movimento 2026" em Curit...\n...\n25/03/2026 09h19\nFesta do Costelão de Bela Vista será realizada no dia 12 de abril\n...\n25/03/2026 08h36\nFesta do Frango da Linha Palmital acontece no dia 11 de abril\n...\n25/03/2026 08h35\nEstudantes da Escola Ana Paula conhecem a prefeitura\n...\n25/03/2026 08h32\nMais Notícias\nInscrição Concurso Público\nDocumentos e Leis para Obras\nTransporte Coletivo Urbano\nCadastro Agentes Culturais\nVisite o Museu Online\nInformações Úteis\nSistema Informação da Cultura\nAcesse o site do Museu\nServiços Ambientais\nVcMCR\nCardápio Alimentação Escolar\nValores de Referência\nPlantão Fiscal\nTransparência Vacinação Covid\nITR - Preço da Terra Nua\nGESTÃO DE RESÍDUOS E LIMPEZA\nCronograma de Esportes\nIPTU\nITBI\nFormulários da Sec. de Fazenda\nSIM/POA\nAlvará - Guias Online\nPlano Municipal de Mobilidade\nCoronavírus - Ajude no Combate\nLGPD\nDenuncie Fura-Fila\nBoletim Diário Covid\nPPA\nServiços Dig. Mód. Empresarial\nMUNICÍPIO DE MARECHAL CÂNDIDO RONDON\nREDES SOCIAIS\nPORTAL DO CIDADÃO\nACESSO RÁPIDO\nAcesso à Informação\nAutoatendimento\nTransparência\nLOCALIZAÇÃO\nRUA ESPIRITO SANTO, Nº 777, BAIRRO CENTRO\nMarechal Cândido Rondon/PR\nCEP: 85.960-138\nAbrir no Mapa\nCONTATOS\n(45) 3284-8828\npm@mcr.pr.gov.br\nHORÁRIO DE ATENDIMENTO\nSegunda-feira a Sexta-feira 8:00 às 11:45 - 13:15 às 17:00\n2026 - IPM Sistemas Ltda. Todos os Direitos Reservados.\nTermos de Uso\n|\nPolítica de Privacidade\nNão exibir este aviso novamente.\nCONSENTIMENTO DE COOKIES\nUtilizamos cookies e tecnologias semelhantes para fornecer-lhe uma melhor experiência de navegação, assim como providenciar alguns recursos essenciais.\nLeia sobre Políticas de uso de cookies.\nLeia sobre Políticas de privacidade.\nLeia sobre Termos de Uso.\nAceitar\nRejeitar não necessários\nGerenciar Preferências'

In [ ]:
el1

[<selenium.webdriver.remote.webelement.WebElement (session="71bc04e2e37a31a8e25c98ec92fcbbd3", element="f.21B64539471A6ADD2D6433C2BB4A08BC.d.EA9C6341DBDE1CB60E3D00B47B5ED719.e.208")>,
 <selenium.webdriver.remote.webelement.WebElement (session="71bc04e2e37a31a8e25c98ec92fcbbd3", element="f.21B64539471A6ADD2D6433C2BB4A08BC.d.EA9C6341DBDE1CB60E3D00B47B5ED719.e.207")>]

In [ ]:
eh = [e.get_attribute("outerHTML") for e in el1]
eh

['<a target="_blank" rel="noopener" href="https://tce.pr.gov.br/transparencia/radar-da-transparencia.htm" title="Radar Transparência Pública" class="link-acesso-rapido"><span class="icon-acesso-rapido"><i class="fas fa-external-link-square-alt"></i></span> <span class="titulo-servico">Radar Transparência Pública</span></a>',
 '<a target="_blank" rel="noopener" href="https://tce.pr.gov.br/transparencia/radar-da-transparencia.htm" title="Radar Transparência Pública" class="link-acesso-rapido"><span class="icon-acesso-rapido"><i class="fas fa-external-link-square-alt"></i></span> <span class="titulo-servico">Radar Transparência Pública</span></a>']

In [ ]:
driver.execute_script('arguments[0].click();',el1[1])

In [ ]:
driver.save_screenshot('i.jpg')

True

In [ ]:
ep = localiza_pai(el1[3])

ep.get_attribute("outerHTML")

'<div class="elementor-widget-container">\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href="https://cr2transparencia.com.br/radar" target="_blank">\n\t\t\t\t\t\t\t<img decoding="async" class=" lazyloaded" src="https://cr2transparencia.com.br/imgs/logoRadar.png" title="" alt="radar-transparencia-pública" loading="lazy" data-src="https://cr2transparencia.com.br/imgs/logoRadar.png">\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>'

In [ ]:
el1[3].get_attribute("outerHTML")

'<a href="https://cr2transparencia.com.br/radar" target="_blank">\n\t\t\t\t\t\t\t<img decoding="async" class=" lazyload" src="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PScwIDAgMSAxJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPjwvc3ZnPg==" title="" alt="radar-transparencia-pública" loading="lazy" data-src="https://cr2transparencia.com.br/imgs/logoRadar.png">\t\t\t\t\t\t\t\t</a>'

In [ ]:
driver.save_screenshot("image.jpg")

True

In [ ]:
url_inicial = driver.current_url
for e in el1:
  try:
    clicker(driver, e)
    driver.implicitly_wait(5)
    print(driver.current_url)
  except Exception:
    print("erro")

  if driver.current_url == "https://radardatransparencia.atricon.org.br/":
    print('pagina localizada')
    break

  if driver.current_url != url_inicial:
    print('pagina alterada')
    while driver.current_url != url_inicial:
      driver.back()
      driver.implicitly_wait(5)
      pass

  if driver.current_url == url_inicial:
    pass

https://saojosedaboavista.pr.gov.br/
https://saojosedaboavista.pr.gov.br/
https://saojosedaboavista.pr.gov.br/
https://saojosedaboavista.pr.gov.br/
https://saojosedaboavista.pr.gov.br/

In [ ]:
e = driver.find_element(By.XPATH, f'//*[contains(text(),"Despesas")]')
driver.execute_script('arguments[0].click();',e)
driver.implicitly_wait(10)
driver.save_screenshot("image.jpg")

True

In [ ]:
e = driver.find_element(By.XPATH, f'//*[contains(text(),"Pessoal")]')
driver.execute_script('arguments[0].click();',e)
driver.implicitly_wait(10)
driver.save_screenshot("image.jpg")

True

In [ ]:
driver.implicitly_wait(5)
e = driver.find_element(By.XPATH, f'//*[contains(text(),"Ver detalhamento")]')
driver.execute_script('arguments[0].click();',e)
driver.implicitly_wait(5)
driver.save_screenshot("image.jpg")

True

In [ ]:
driver.save_screenshot("image.jpg")

True

In [ ]:
driver.forward()

In [ ]:
driver.close()

In [ ]:
driver = abrir_driver()
url = "http://corumbataidosul.pr.gov.br/secretaria/index"
driver.get(url)
p = ["Secretaria","Coordenadoria","Gabinete","Administração","Agricultura"]
pp = padroniza_parametro(p)
els, html, lista = busca_link(driver, pp)
driver.page_source
lista = list(set(lista))
lista
[el.text for el in lista if el.text != '']

KeyboardInterrupt:

In [ ]:
driver.close()

###EM BLOCO

In [ ]:
q664_1 = q_selenium(664,0,65)

Tempo de execução para https://barracao.pr.gov.br/: 22.75s
Tempo de execução para https://www.bocaiuvadosul.pr.gov.br/: 6.48s
Tempo de execução para https://marmeleiro.atende.net/transparencia/: 9.18s
Tempo de execução para https://cianorte.oxy.elotech.com.br/portaltransparencia/1/: 7.53s
WebDriver error for https://www.marialva.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: 27.749
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x5b76d2e5ca6a <unknown>
#1 0x5b76d286bab5 <unknown>
#2 0x5b76d28533bb <unknown>
#3 0x5b76d28530a4 <unknown>
#4 0x5b76d2850deb <unknown>
#5 0x5b76d285176f <unknown>
#6 0x5b76d28607a0 <unknown>
#7 0x5b76d287a4b7 <unknown>
#8 0x5b76d2880feb <unknown>
#9 0x5b76d2851ebf <unknown>
#10 0x5b76d287a24b <unknown>
#11 0x5b76d2906ac6 <unknown>
#12 0x5b76d28b1cbf <unknown>
#13 0x5b76d28b2a81 <unknown>
#14 0x5b76d2e22a64 <unknown>
#15 0x5b76d2e25951 <unknown>
#16 0x5b76d2e0f21e <unknown>
#17 0x5b76d2e2651e <unknown>
#18 0x5b76d2df5be0 <unknown>
#19 0x5b76d2e499b8 <unknown>
#20 0x5b76d2e49b88 <unknown>
#21 0x5b76d2e5b4de <unknown>
#22 0x7953e5c10ac3 <unknown>

Tempo de execução para https://www.marialva.pr.gov.br/: 31.5s
Tempo de execução para https://antonioolinto.eloweb.net/portaltransparencia/1/: 5.4s
Tempo de execução para https://mandirituba.pr.gov.br/portal-da-transparencia/informacoes-gerais/radar-da-transparenciapublica: 112.9s
Tempo de execução para https://saotomepr.equiplano.com.br:7430/transparencia/: 7.09s
Tempo de execução para https://www.veracruz.pr.gov.br/: 163.21s
10
Tempo de execução para https://tapira.eloweb.net/portaltransparencia/1/: 5.01s
Tempo de execução para https://terraboa.eloweb.net/portaltransparencia/1/: 5.77s
Tempo de execução para https://ibipora.eloweb.net/portaltransparencia/1/publicacoes/1056: 5.7s
Tempo de execução para https://marechalcandidorondon.atende.net/cidadao: 222.72s
Tempo de execução para https://fazendariogrande.pr.gov.br/transparencia: 113.24s
Tempo de execução para https://santaizabeldooeste.atende.net/cidadao: 9.86s
Tempo de execução para https://ouroverdedooeste.atende.net/: 6.72s
Tempo de execução para https://guaraniacu.atende.net/: 184.58s
Tempo de execução para https://riobranco.eloweb.net/portaltransparencia/1/: 6.66s
20
Tempo de execução para https://transparencia.cambe.pr.gov.br:8443/portal/index.xhtml: 6.41s
Tempo de execução para https://patobragado.atende.net/subportal/portal-da-transparencia: 113.27s
Tempo de execução para https://www.pmcds.pr.gov.br/portalTransparencia/: 158.68s
Tempo de execução para https://www.esperancanova.pr.gov.br/: 7.59s
WebDriver error for https://presidentecastelobranco.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: 28.312
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x5c49a66cda6a <unknown>
#1 0x5c49a60dcab5 <unknown>
#2 0x5c49a60c43bb <unknown>
#3 0x5c49a60c40a4 <unknown>
#4 0x5c49a60c1deb <unknown>
#5 0x5c49a60c276f <unknown>
#6 0x5c49a60d17a0 <unknown>
#7 0x5c49a60eb4b7 <unknown>
#8 0x5c49a60f1feb <unknown>
#9 0x5c49a60c2ebf <unknown>
#10 0x5c49a60eb24b <unknown>
#11 0x5c49a6177ac6 <unknown>
#12 0x5c49a6122cbf <unknown>
#13 0x5c49a6123a81 <unknown>
#14 0x5c49a6693a64 <unknown>
#15 0x5c49a6696951 <unknown>
#16 0x5c49a668021e <unknown>
#17 0x5c49a669751e <unknown>
#18 0x5c49a6666be0 <unknown>
#19 0x5c49a66ba9b8 <unknown>
#20 0x5c49a66bab88 <unknown>
#21 0x5c49a66cc4de <unknown>
#22 0x7fe63025dac3 <unknown>

Tempo de execução para https://presidentecastelobranco.pr.gov.br/: 30.99s
Tempo de execução para https://transparencia.betha.cloud/#/cFVgtYEEPVrO7Xy4RZ_lXg==: 7.06s
WebDriver error for http://california.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: 28.116
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x5a42137c5a6a <unknown>
#1 0x5a42131d4ab5 <unknown>
#2 0x5a42131bc3bb <unknown>
#3 0x5a42131bc0a4 <unknown>
#4 0x5a42131b9deb <unknown>
#5 0x5a42131ba76f <unknown>
#6 0x5a42131c97a0 <unknown>
#7 0x5a42131e34b7 <unknown>
#8 0x5a42131e9feb <unknown>
#9 0x5a42131baebf <unknown>
#10 0x5a42131e324b <unknown>
#11 0x5a421326fac6 <unknown>
#12 0x5a421321acbf <unknown>
#13 0x5a421321ba81 <unknown>
#14 0x5a421378ba64 <unknown>
#15 0x5a421378e951 <unknown>
#16 0x5a421377821e <unknown>
#17 0x5a421378f51e <unknown>
#18 0x5a421375ebe0 <unknown>
#19 0x5a42137b29b8 <unknown>
#20 0x5a42137b2b88 <unknown>
#21 0x5a42137c44de <unknown>
#22 0x7aed6fa16ac3 <unknown>

Tempo de execução para http://california.pr.gov.br/: 31.03s
WebDriver error for https://www.saocarlosdoivai.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: 28.861
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x55f2cfa64a6a <unknown>
#1 0x55f2cf473ab5 <unknown>
#2 0x55f2cf45b3bb <unknown>
#3 0x55f2cf45b0a4 <unknown>
#4 0x55f2cf458deb <unknown>
#5 0x55f2cf45976f <unknown>
#6 0x55f2cf4687a0 <unknown>
#7 0x55f2cf4824b7 <unknown>
#8 0x55f2cf488feb <unknown>
#9 0x55f2cf459ebf <unknown>
#10 0x55f2cf48224b <unknown>
#11 0x55f2cf50eac6 <unknown>
#12 0x55f2cf4b9cbf <unknown>
#13 0x55f2cf4baa81 <unknown>
#14 0x55f2cfa2aa64 <unknown>
#15 0x55f2cfa2d951 <unknown>
#16 0x55f2cfa1721e <unknown>
#17 0x55f2cfa2e51e <unknown>
#18 0x55f2cf9fdbe0 <unknown>
#19 0x55f2cfa519b8 <unknown>
#20 0x55f2cfa51b88 <unknown>
#21 0x55f2cfa634de <unknown>
#22 0x7f30816f0ac3 <unknown>

Tempo de execução para https://www.saocarlosdoivai.pr.gov.br/: 30.99s
Tempo de execução para https://loanda.eloweb.net/portaltransparencia/1/: 4.88s
Tempo de execução para https://franciscoalves.eloweb.net/portaltransparencia/1/: 6.59s
30
Tempo de execução para https://carambei.atende.net/cidadao: 7.22s
Tempo de execução para https://anahy.atende.net/: 13.15s
Tempo de execução para  https://cascavel.atende.net/transparencia/: 5.63s
Tempo de execução para https://araruna.eloweb.net/portaltransparencia/1/: 204.09s
Tempo de execução para https://transparencia.betha.cloud/#/QZgNvTT4qFk80u10mrdMPg==/consulta/75669: 6.03s
Tempo de execução para https://www.saopedrodoiguacu.pr.gov.br/: 4.05s
WebDriver error for http://www.saopedrodoivai.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: -0.003
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x58cff7d91a6a <unknown>
#1 0x58cff77a0ab5 <unknown>
#2 0x58cff77883bb <unknown>
#3 0x58cff77880a4 <unknown>
#4 0x58cff7785deb <unknown>
#5 0x58cff778676f <unknown>
#6 0x58cff77957a0 <unknown>
#7 0x58cff77af4b7 <unknown>
#8 0x58cff77b5feb <unknown>
#9 0x58cff7786ebf <unknown>
#10 0x58cff77af24b <unknown>
#11 0x58cff783b67f <unknown>
#12 0x58cff77e6cbf <unknown>
#13 0x58cff77e7a81 <unknown>
#14 0x58cff7d57a64 <unknown>
#15 0x58cff7d5a951 <unknown>
#16 0x58cff7d4421e <unknown>
#17 0x58cff7d5b51e <unknown>
#18 0x58cff7d2abe0 <unknown>
#19 0x58cff7d7e9b8 <unknown>
#20 0x58cff7d7eb88 <unknown>
#21 0x58cff7d904de <unknown>
#22 0x7d7d4440eac3 <unknown>

Tempo de execução para http://www.saopedrodoivai.pr.gov.br/: 31.02s
WebDriver error for https://www.sertaneja.pr.gov.br/: Message: timeout: Timed out receiving message from renderer: -0.003
  (Session info: chrome=146.0.7680.164)
Stacktrace:
#0 0x58b3d1e2ea6a <unknown>
#1 0x58b3d183dab5 <unknown>
#2 0x58b3d18253bb <unknown>
#3 0x58b3d18250a4 <unknown>
#4 0x58b3d1822deb <unknown>
#5 0x58b3d182376f <unknown>
#6 0x58b3d18327a0 <unknown>
#7 0x58b3d184c4b7 <unknown>
#8 0x58b3d1852feb <unknown>
#9 0x58b3d1823ebf <unknown>
#10 0x58b3d184c24b <unknown>
#11 0x58b3d18d867f <unknown>
#12 0x58b3d1883cbf <unknown>
#13 0x58b3d1884a81 <unknown>
#14 0x58b3d1df4a64 <unknown>
#15 0x58b3d1df7951 <unknown>
#16 0x58b3d1de121e <unknown>
#17 0x58b3d1df851e <unknown>
#18 0x58b3d1dc7be0 <unknown>
#19 0x58b3d1e1b9b8 <unknown>
#20 0x58b3d1e1bb88 <unknown>
#21 0x58b3d1e2d4de <unknown>
#22 0x7b8997641ac3 <unknown>

Tempo de execução para https://www.sertaneja.pr.gov.br/: 30.96s
Tempo de execução para https://guaira.atende.net/?pg=transparencia#!/: 5.52s
40
Tempo de execução para https://www.grandesrios.pr.gov.br/: 6.13s
Tempo de execução para http://45.225.146.100:8090/ portaltransparencia/1/: 112.76s
Tempo de execução para https://www.centenariodosul.pr.gov.br/index.php: 11.36s
Tempo de execução para https://teixeirasoarespr.equiplano.com.br:7004/transparencia/: 7.56s
Tempo de execução para http://www.campinadosimao.pr.gov.br/index.php: 4.21s
Tempo de execução para https://cambira.eloweb.net/portaltransparencia/1/: 5.35s
Tempo de execução para https://transparencia.betha.cloud/#/XsTYmnrmpsOvZ8_9fe1GYw==: 7.49s

WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=1, read=0, redirect=None, status=None)) after connection broken by 'ConnectionResetError(104, 'Connection reset by peer')': /session/9f4159f625f941d51d05377f2f7ad595

Tempo de execução para http://177.92.1.11:7474/transparencia/: 20.65s

KeyboardInterrupt:

In [ ]:
q664_2 = q_selenium(664,65,130)

In [ ]:
q664_3 = q_selenium(664,130,195)

In [ ]:
q664_4 = q_selenium(664,195,260)

In [ ]:
q664_5 = q_selenium(664,260,325)

In [ ]:
q664_6 = q_selenium(664,325,)

In [ ]:
q_selenium_664 = pd.concat([q664_1,
                            q664_2,
                            q664_3,
                            q664_4,
                            q664_5,
                            q664_6
                          ],ignore_index=True)
q_selenium_664
q_selenium_664.to_csv( 'q_selenium_653.csv', index=False)

In [ ]:
q_selenium_664.head()

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
0,509,664,Disponibilidade,https://barracao.pr.gov.br/,True,"<html lang=""pt-BR"" ng-app=""indexController""><h...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],27.48
1,660,664,Disponibilidade,https://www.bocaiuvadosul.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[https://radardatransparencia.atricon.org.br/r...,"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.14
2,2972,664,Disponibilidade,https://marmeleiro.atende.net/transparencia/,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.20
3,1270,664,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],5.28
4,2949,664,Disponibilidade,https://www.marialva.pr.gov.br/,True,None,None,None,TimeoutException,Message: timeout: Timed out receiving message ...,[],[],31.00

In [ ]:
p = ["radardatransparencia"]
v = q_selenium_664.copy()

v["verificado"] = v.elemento_final.apply(lambda x: pd.Series(verifica_lista(x, p)).drop_duplicates().tolist())
v

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
0,509,664,Disponibilidade,https://barracao.pr.gov.br/,True,"<html lang=""pt-BR"" ng-app=""indexController""><h...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],27.48,[[https://radardatransparencia.atricon.org.br/...
1,660,664,Disponibilidade,https://www.bocaiuvadosul.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[https://radardatransparencia.atricon.org.br/r...,"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.14,[[https://radardatransparencia.atricon.org.br/...
2,2972,664,Disponibilidade,https://marmeleiro.atende.net/transparencia/,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.20,[[https://radardatransparencia.atricon.org.br/...
3,1270,664,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],5.28,[[https://radardatransparencia.atricon.org.br/...
4,2949,664,Disponibilidade,https://www.marialva.pr.gov.br/,True,None,None,None,TimeoutException,Message: timeout: Timed out receiving message ...,[],[],31.00,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,4405,664,Disponibilidade,https://santaines.eloweb.net/portaltransparenc...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.31,[[https://radardatransparencia.atricon.org.br/...
393,1554,664,Disponibilidade,https://diamantedonorte.eloweb.net/portaltrans...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/r...,"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],6.91,[[https://radardatransparencia.atricon.org.br/...
394,5196,664,Disponibilidade,https://telemacoborba.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],19.15,[]
395,3341,664,Disponibilidade,https://novalondrina.eloweb.net/portaltranspar...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/r...,"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.02,[[https://radardatransparencia.atricon.org.br/...
396,3380,664,Disponibilidade,https://novatebas.oxy.elotech.com.br/portaltra...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],5.23,[[https://radardatransparencia.atricon.org.br/...

In [ ]:
elemento_localizado = v[v["verificado"].apply(lambda x: x != [])]
elemento_localizado.head()

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
0,509,664,Disponibilidade,https://barracao.pr.gov.br/,True,"<html lang=""pt-BR"" ng-app=""indexController""><h...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],27.48,[[https://radardatransparencia.atricon.org.br/...
1,660,664,Disponibilidade,https://www.bocaiuvadosul.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[https://radardatransparencia.atricon.org.br/r...,"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.14,[[https://radardatransparencia.atricon.org.br/...
2,2972,664,Disponibilidade,https://marmeleiro.atende.net/transparencia/,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.20,[[https://radardatransparencia.atricon.org.br/...
3,1270,664,Disponibilidade,https://cianorte.oxy.elotech.com.br/portaltran...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],5.28,[[https://radardatransparencia.atricon.org.br/...
5,266,664,Disponibilidade,https://antonioolinto.eloweb.net/portaltranspa...,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],5.22,[[https://radardatransparencia.atricon.org.br/...

In [ ]:
elemento_ausente = v[v["verificado"].apply(lambda x: x == [])]
elemento_ausente.head()

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
4,2949,664,Disponibilidade,https://www.marialva.pr.gov.br/,True,None,None,None,TimeoutException,Message: timeout: Timed out receiving message ...,[],[],31.00,[]
6,3589,664,Disponibilidade,https://radardatransparencia.atricon.org.br/ra...,True,None,None,None,URL_VERIFY,Foi verificado que a URL fornecida se refere d...,None,None,NaN,[]
7,2888,664,Disponibilidade,https://mandirituba.pr.gov.br/portal-da-transp...,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.19,[]
9,5470,664,Disponibilidade,https://www.veracruz.pr.gov.br/,False,"<html lang=""pt-BR""><head>\n<meta charset=""UTF-...",[],[],None,None,[],"[<img loading=""lazy"" decoding=""async"" width=""6...",22.93,[]
13,2941,664,Disponibilidade,https://marechalcandidorondon.atende.net/cidadao,False,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, ]","[<a target=""_blank"" rel=""noopener"" href=""https...",50.52,[]

In [ ]:
elemento_ausente[elemento_ausente['html_elemento_final'].apply(lambda x: x != []) & elemento_ausente['html_elemento_final'].notna() ]

Empty DataFrame
Columns: [entidade_id, id_criterio, item_avaliacao, link_avaliacao, resultado_final, pagina_scraped, elemento_final, html_elemento_final, error_cod, error_msg, elemento_interacao_1, html_elemento_interacao_1, duracao_segundos, verificado]
Index: []

In [ ]:
q_selenium_664[q_selenium_664['link_avaliacao'].str.contains('saotomepr', na=False)]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
8,4910,664,Disponibilidade,https://saotomepr.equiplano.com.br:7430/transp...,False,"<html xmlns=""http://www.w3.org/1999/xhtml"" lan...",[https://radardatransparencia.atricon.org.br/],"[<a href=""https://radardatransparencia.atricon...",None,None,[],[],7.93

In [ ]:
display(elemento_localizado.duracao_segundos.describe())
display(elemento_localizado.duracao_segundos.sum())
display(elemento_localizado.shape)
display(elemento_ausente.duracao_segundos.describe())
display(elemento_ausente.duracao_segundos.sum())
display(elemento_ausente.shape)
display(elemento_ausente.error_cod.value_counts())

count    198.000000
mean       7.849747
std        3.793946
min        2.990000
25%        5.622500
50%        6.635000
75%        9.010000
max       31.090000
Name: duracao_segundos, dtype: float64

np.float64(1554.25)

(198, 14)

count    144.000000
mean      28.992153
std       15.308328
min        1.180000
25%       18.507500
50%       31.000000
75%       31.815000
max       97.800000
Name: duracao_segundos, dtype: float64

np.float64(4174.87)

(199, 14)

error_cod
URL_VERIFY                     45
TimeoutException               44
URL_BLOCKED                    28
URL_INVALID                    10
NENHUMA_ELEMENTO_LOCALIZADO     9
WebDriverException              4
InvalidArgumentException        2
Name: count, dtype: int64

In [ ]:
elemento_ausente[elemento_ausente.pagina_scraped.notna()]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
7,2888,664,Disponibilidade,https://mandirituba.pr.gov.br/portal-da-transp...,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.19,[]
9,5470,664,Disponibilidade,https://www.veracruz.pr.gov.br/,False,"<html lang=""pt-BR""><head>\n<meta charset=""UTF-...",[],[],None,None,[],"[<img loading=""lazy"" decoding=""async"" width=""6...",22.93,[]
13,2941,664,Disponibilidade,https://marechalcandidorondon.atende.net/cidadao,False,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, ]","[<a target=""_blank"" rel=""noopener"" href=""https...",50.52,[]
15,1754,664,Disponibilidade,https://fazendariogrande.pr.gov.br/transparencia,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.30,[]
18,2013,664,Disponibilidade,https://guaraniacu.atende.net/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , , Radar da Transparência Pública, Radar T...","[<div tabindex=""0"" title=""radar 2"" class=""bann...",84.34,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,34,664,Disponibilidade,https://transparencia.betha.cloud/#/k7LmvDe0yL...,True,<html><head></head><body>redirecionando login....,[],[],None,None,[],"[<style type=""text/css"">.img-selo[data-v-2a047...",25.84,[]
381,2975,664,Disponibilidade,https://marquinho.pr.gov.br/MapaAcessoTranspar...,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[ Radar da Transparência Pública],"[<a href=""https://radardatransparencia.com.br/...",19.63,[]
386,3810,664,Disponibilidade,https://pinhao.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.64,[]
389,3008,664,Disponibilidade,https://matinhos.atende.net/transparencia/item...,False,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,[],[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,32.03,[]
394,5196,664,Disponibilidade,https://telemacoborba.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],19.15,[]

In [ ]:
elemento_ausente[(elemento_ausente['html_elemento_interacao_1'].apply(lambda x: x != []))
                  & (elemento_ausente['html_elemento_interacao_1'].notna())
                  & (elemento_ausente['resultado_final'] == True)
                  ].shape

(46, 14)

In [ ]:
nao_localizados_betha = elemento_ausente[(elemento_ausente['html_elemento_interacao_1'].apply(lambda x: x != []))
                  & (elemento_ausente['html_elemento_interacao_1'].notna())
                  & (elemento_ausente['resultado_final'] == True)
                  & ~(elemento_ausente['link_avaliacao'].str.contains("betha", na=False))
                  ]


display(nao_localizados_betha)
display(nao_localizados_betha.shape)

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
18,2013,664,Disponibilidade,https://guaraniacu.atende.net/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , , Radar da Transparência Pública, Radar T...","[<div tabindex=""0"" title=""radar 2"" class=""bann...",84.34,[]
57,2659,664,Disponibilidade,https://www.jussara.pr.gov.br/,True,"<html><head>\n <meta charset=""UTF-8"">\n...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",47.13,[]
62,4447,664,Disponibilidade,http://s2.asp.srv.br/etransparencia.pm.santamo...,True,"<html lang=""pt""><head>\n<meta name=""generator""...",[],[],None,None,"[, RADAR NACIONAL DE TRANSPARÊNCIA]","[<input type=""hidden"" name=""GXState"" value=""{&...",18.39,[]
64,2129,664,Disponibilidade,https://www.icaraima.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n\t<title>Prefeitura...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.16,[]
67,4086,664,Disponibilidade,https://www.quitandinha.pr.gov.br/,True,"<html lang=""pt"" style=""scroll-padding-top: 0px...",[],[],None,None,"[, , , , ]","[<script type=""application/json"" id=""wix-warmu...",36.39,[]
101,3177,664,Disponibilidade,https://www.morretes.pr.gov.br/,True,<html><head>\n <!-- Google tag (gtag.js...,[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.99,[]
104,2488,664,Disponibilidade,https://jaguapita.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.02,[]
107,2648,664,Disponibilidade,https://juranda.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , ]","[<a target=""_blank"" rel=""noopener"" href=""https...",45.92,[]
116,4743,664,Disponibilidade,https://saojosedaboavista.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,"[, , Radar da Transparência Pública]","[<a href=""https://cr2transparencia.com.br/rada...",31.89,[]
165,5524,664,Disponibilidade,http://www.virmond.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[],"[<a href=""https://www.radardatransparencia.com...",18.50,[]
179,749,664,Disponibilidade,https://www.brasilandiadosul.pr.gov.br/index.php#,True,"<html lang=""pt-br""><head>\n <title>Prefeitu...",[],[],None,None,[],"[<img src=""images/radar1.jpg"" alt=""Portal da T...",20.03,[]
190,4065,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.51,[]
222,334,664,Disponibilidade,https://arapongas.atende.net/transparencia,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,34.16,[]
236,1366,664,Disponibilidade,https://www.conselheiromairinck.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,"[, , ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",33.12,[]
241,1899,664,Disponibilidade,https://www.generalcarneiro.pr.gov.br/portal-d...,True,"<html lang=""pt-BR"" style=""height: 100%;""><head...",[],[],None,None,"[, , ]","[<a href=""https://radardatransparencia.com.br/...",29.21,[]
287,3365,664,Disponibilidade,https://novapratadoiguacu.atende.net/transpare...,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,36.35,[]
303,633,664,Disponibilidade,http://45.167.72.22:8091/portaltransparencia/,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[],[],None,None,"[RADAR DA\nTRANSPARÊNCIA, RADAR DA\nTRANSPARÊN...","[<a href=""https://radar.tce.mt.gov.br/extensio...",21.59,[]
314,923,664,Disponibilidade,https://cambara.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",32.85,[]
317,4107,664,Disponibilidade,https://realeza.pr.gov.br/transparencia,True,"<html lang=""pt-BR"" style=""--bs-pmr-green: #016...",[],[],None,None,"[, ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",23.51,[]
319,4188,664,Disponibilidade,https://www.riobom.pr.gov.br/,True,"<html lang=""pt-BR"" class=""sr"" style=""height: 1...",[],[],None,None,[],"[<a href=""https://radardatransparencia.com.br/...",21.78,[]
326,3533,664,Disponibilidade,https://palmeira.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,"[RADAR, RADAR, Radar da transparência]","[<a href=""https://radar.tce.mt.gov.br/extensio...",35.52,[]
329,2516,664,Disponibilidade,https://janiopolis.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[Radar da Transparência, Radar da Transparênci...","[<a href=""https://radar.tce.mt.gov.br/extensio...",48.30,[]
339,3754,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.12,[]
354,5228,664,Disponibilidade,https://tibagi.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[Radar da Transparência],"[<a class=""elementor-button elementor-button-l...",36.02,[]
361,4101,664,Disponibilidade,https://www.ranchoalegre.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,[],"[<img src=""/assets/radarTransparencia.png"" sty...",31.24,[]
368,3779,664,Disponibilidade,https://www.pien.pr.gov.br/,True,"<html lang=""pt-br""><head>\n\n <!-- Google T...",[],[],None,None,"[Radar da Transparência Pública, , Radar da Tr...","[<a class=""d-flex p-4 transition h-100"" title=...",24.90,[]
369,4108,664,Disponibilidade,https://reboucas.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",29.94,[]
373,2367,664,Disponibilidade,https://itaperucu.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[],"[<a href=""/portal-da-transparencia/radar/"">\n\...",24.14,[]
381,2975,664,Disponibilidade,https://marquinho.pr.gov.br/MapaAcessoTranspar...,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[ Radar da Transparência Pública],"[<a href=""https://radardatransparencia.com.br/...",19.63,[]

(29, 14)

In [ ]:
ausentes_sem_erro = elemento_ausente[(elemento_ausente['error_cod'].isna()) & ~(elemento_ausente['link_avaliacao'].str.contains("betha", na=False))]
ausentes_sem_erro

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
9,5470,664,Disponibilidade,https://www.veracruz.pr.gov.br/,False,"<html lang=""pt-BR""><head>\n<meta charset=""UTF-...",[],[],None,None,[],"[<img loading=""lazy"" decoding=""async"" width=""6...",22.93,[]
13,2941,664,Disponibilidade,https://marechalcandidorondon.atende.net/cidadao,False,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, ]","[<a target=""_blank"" rel=""noopener"" href=""https...",50.52,[]
18,2013,664,Disponibilidade,https://guaraniacu.atende.net/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , , Radar da Transparência Pública, Radar T...","[<div tabindex=""0"" title=""radar 2"" class=""bann...",84.34,[]
34,351,664,Disponibilidade,https://araruna.eloweb.net/portaltransparencia/1/,False,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[],[],None,None,[Radar da Transparência\nRadar Nacional da Tra...,"[<a id=""linkMenu"" href=""https://radar.tce.mt.g...",48.12,[]
57,2659,664,Disponibilidade,https://www.jussara.pr.gov.br/,True,"<html><head>\n <meta charset=""UTF-8"">\n...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",47.13,[]
62,4447,664,Disponibilidade,http://s2.asp.srv.br/etransparencia.pm.santamo...,True,"<html lang=""pt""><head>\n<meta name=""generator""...",[],[],None,None,"[, RADAR NACIONAL DE TRANSPARÊNCIA]","[<input type=""hidden"" name=""GXState"" value=""{&...",18.39,[]
64,2129,664,Disponibilidade,https://www.icaraima.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n\t<title>Prefeitura...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.16,[]
67,4086,664,Disponibilidade,https://www.quitandinha.pr.gov.br/,True,"<html lang=""pt"" style=""scroll-padding-top: 0px...",[],[],None,None,"[, , , , ]","[<script type=""application/json"" id=""wix-warmu...",36.39,[]
99,1663,664,Disponibilidade,https://eneasmarques.atende.net/transparencia/,False,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,33.73,[]
101,3177,664,Disponibilidade,https://www.morretes.pr.gov.br/,True,<html><head>\n <!-- Google tag (gtag.js...,[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.99,[]
104,2488,664,Disponibilidade,https://jaguapita.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.02,[]
107,2648,664,Disponibilidade,https://juranda.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , ]","[<a target=""_blank"" rel=""noopener"" href=""https...",45.92,[]
116,4743,664,Disponibilidade,https://saojosedaboavista.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,"[, , Radar da Transparência Pública]","[<a href=""https://cr2transparencia.com.br/rada...",31.89,[]
165,5524,664,Disponibilidade,http://www.virmond.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[],"[<a href=""https://www.radardatransparencia.com...",18.50,[]
179,749,664,Disponibilidade,https://www.brasilandiadosul.pr.gov.br/index.php#,True,"<html lang=""pt-br""><head>\n <title>Prefeitu...",[],[],None,None,[],"[<img src=""images/radar1.jpg"" alt=""Portal da T...",20.03,[]
190,4065,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.51,[]
214,4520,664,Disponibilidade,https://www.stitaipu.pr.gov.br/portal-da-trans...,False,"<html lang=""{page-&gt;lang}""><head><meta http-...",[],[],None,None,[RADAR DA TRANSPARÊNCIA PÚBLICA],"[<a href=""https://radar.tce.mt.gov.br/extensio...",17.27,[]
222,334,664,Disponibilidade,https://arapongas.atende.net/transparencia,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,34.16,[]
236,1366,664,Disponibilidade,https://www.conselheiromairinck.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,"[, , ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",33.12,[]
241,1899,664,Disponibilidade,https://www.generalcarneiro.pr.gov.br/portal-d...,True,"<html lang=""pt-BR"" style=""height: 100%;""><head...",[],[],None,None,"[, , ]","[<a href=""https://radardatransparencia.com.br/...",29.21,[]
273,1934,664,Disponibilidade,https://www.goioxim.pr.gov.br/,False,"<html><head>\n <meta charset=""UTF-8...",[],[],None,None,[],"[<a href=""https://radardatransparencia.com.br/...",20.62,[]
287,3365,664,Disponibilidade,https://novapratadoiguacu.atende.net/transpare...,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,36.35,[]
299,3093,664,Disponibilidade,https://www.miraselva.pr.gov.br/mapa_site.php,False,"<html lang=""pt-br"" class="" js no-touch cssanim...",[],[],None,None,[],"[<a href=""/radar_transparencia"">Radar da Trans...",32.50,[]
303,633,664,Disponibilidade,http://45.167.72.22:8091/portaltransparencia/,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[],[],None,None,"[RADAR DA\nTRANSPARÊNCIA, RADAR DA\nTRANSPARÊN...","[<a href=""https://radar.tce.mt.gov.br/extensio...",21.59,[]
314,923,664,Disponibilidade,https://cambara.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",32.85,[]
317,4107,664,Disponibilidade,https://realeza.pr.gov.br/transparencia,True,"<html lang=""pt-BR"" style=""--bs-pmr-green: #016...",[],[],None,None,"[, ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",23.51,[]
319,4188,664,Disponibilidade,https://www.riobom.pr.gov.br/,True,"<html lang=""pt-BR"" class=""sr"" style=""height: 1...",[],[],None,None,[],"[<a href=""https://radardatransparencia.com.br/...",21.78,[]
326,3533,664,Disponibilidade,https://palmeira.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,"[RADAR, RADAR, Radar da transparência]","[<a href=""https://radar.tce.mt.gov.br/extensio...",35.52,[]
329,2516,664,Disponibilidade,https://janiopolis.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[Radar da Transparência, Radar da Transparênci...","[<a href=""https://radar.tce.mt.gov.br/extensio...",48.30,[]
339,3754,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.12,[]
351,2737,664,Disponibilidade,https://lapa.atende.net/cidadao,False,"<html lang=""pt-br"" class=""base_portal js flexb...",[],[],None,None,"[, , ]","[<script>window['__oListaSistemas'] = {""WPO"":{...",48.03,[]
354,5228,664,Disponibilidade,https://tibagi.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[Radar da Transparência],"[<a class=""elementor-button elementor-button-l...",36.02,[]
361,4101,664,Disponibilidade,https://www.ranchoalegre.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,[],"[<img src=""/assets/radarTransparencia.png"" sty...",31.24,[]
368,3779,664,Disponibilidade,https://www.pien.pr.gov.br/,True,"<html lang=""pt-br""><head>\n\n <!-- Google T...",[],[],None,None,"[Radar da Transparência Pública, , Radar da Tr...","[<a class=""d-flex p-4 transition h-100"" title=...",24.90,[]
369,4108,664,Disponibilidade,https://reboucas.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",29.94,[]
373,2367,664,Disponibilidade,https://itaperucu.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[],"[<a href=""/portal-da-transparencia/radar/"">\n\...",24.14,[]
381,2975,664,Disponibilidade,https://marquinho.pr.gov.br/MapaAcessoTranspar...,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[ Radar da Transparência Pública],"[<a href=""https://radardatransparencia.com.br/...",19.63,[]
389,3008,664,Disponibilidade,https://matinhos.atende.net/transparencia/item...,False,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,[],[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,32.03,[]

In [ ]:
ausentes_sem_erro.shape

(38, 14)

In [ ]:
ausentes_sem_erro[ausentes_sem_erro['html_elemento_interacao_1'].str.contains("atricon", na= False)]

Empty DataFrame
Columns: [entidade_id, id_criterio, item_avaliacao, link_avaliacao, resultado_final, pagina_scraped, elemento_final, html_elemento_final, error_cod, error_msg, elemento_interacao_1, html_elemento_interacao_1, duracao_segundos, verificado]
Index: []

In [ ]:
nao_localizados_interacao['verificado'] = elemento_ausente['link_avaliacao'].str.contains("radardatransparencia.atricon", na=False)
nao_localizados_interacao

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
18,2013,664,Disponibilidade,https://guaraniacu.atende.net/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , , Radar da Transparência Pública, Radar T...","[<div tabindex=""0"" title=""radar 2"" class=""bann...",84.34,False
57,2659,664,Disponibilidade,https://www.jussara.pr.gov.br/,True,"<html><head>\n <meta charset=""UTF-8"">\n...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",47.13,False
62,4447,664,Disponibilidade,http://s2.asp.srv.br/etransparencia.pm.santamo...,True,"<html lang=""pt""><head>\n<meta name=""generator""...",[],[],None,None,"[, RADAR NACIONAL DE TRANSPARÊNCIA]","[<input type=""hidden"" name=""GXState"" value=""{&...",18.39,False
64,2129,664,Disponibilidade,https://www.icaraima.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n\t<title>Prefeitura...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.16,False
67,4086,664,Disponibilidade,https://www.quitandinha.pr.gov.br/,True,"<html lang=""pt"" style=""scroll-padding-top: 0px...",[],[],None,None,"[, , , , ]","[<script type=""application/json"" id=""wix-warmu...",36.39,False
101,3177,664,Disponibilidade,https://www.morretes.pr.gov.br/,True,<html><head>\n <!-- Google tag (gtag.js...,[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.99,False
104,2488,664,Disponibilidade,https://jaguapita.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,[],"[<a href=""https://radar.tce.mt.gov.br/extensio...",45.02,False
107,2648,664,Disponibilidade,https://juranda.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[, , ]","[<a target=""_blank"" rel=""noopener"" href=""https...",45.92,False
116,4743,664,Disponibilidade,https://saojosedaboavista.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,"[, , Radar da Transparência Pública]","[<a href=""https://cr2transparencia.com.br/rada...",31.89,False
165,5524,664,Disponibilidade,http://www.virmond.pr.gov.br/index.php,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[],"[<a href=""https://www.radardatransparencia.com...",18.50,False
179,749,664,Disponibilidade,https://www.brasilandiadosul.pr.gov.br/index.php#,True,"<html lang=""pt-br""><head>\n <title>Prefeitu...",[],[],None,None,[],"[<img src=""images/radar1.jpg"" alt=""Portal da T...",20.03,False
190,4065,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.51,False
222,334,664,Disponibilidade,https://arapongas.atende.net/transparencia,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,34.16,False
236,1366,664,Disponibilidade,https://www.conselheiromairinck.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,"[, , ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",33.12,False
241,1899,664,Disponibilidade,https://www.generalcarneiro.pr.gov.br/portal-d...,True,"<html lang=""pt-BR"" style=""height: 100%;""><head...",[],[],None,None,"[, , ]","[<a href=""https://radardatransparencia.com.br/...",29.21,False
287,3365,664,Disponibilidade,https://novapratadoiguacu.atende.net/transpare...,True,"<html lang=""pt-br"" class=""js flexbox canvas ca...",[],[],None,None,"[, , ]",[<script>\n\n/*!\n * Chart.js v4.4.0\n * https...,36.35,False
303,633,664,Disponibilidade,http://45.167.72.22:8091/portaltransparencia/,True,"<html lang=""pt-br""><head><meta http-equiv=""ori...",[],[],None,None,"[RADAR DA\nTRANSPARÊNCIA, RADAR DA\nTRANSPARÊN...","[<a href=""https://radar.tce.mt.gov.br/extensio...",21.59,False
314,923,664,Disponibilidade,https://cambara.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",32.85,False
317,4107,664,Disponibilidade,https://realeza.pr.gov.br/transparencia,True,"<html lang=""pt-BR"" style=""--bs-pmr-green: #016...",[],[],None,None,"[, ]","[<a href=""https://radar.tce.mt.gov.br/extensio...",23.51,False
319,4188,664,Disponibilidade,https://www.riobom.pr.gov.br/,True,"<html lang=""pt-BR"" class=""sr"" style=""height: 1...",[],[],None,None,[],"[<a href=""https://radardatransparencia.com.br/...",21.78,False
326,3533,664,Disponibilidade,https://palmeira.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t<meta charset=""UT...",[],[],None,None,"[RADAR, RADAR, Radar da transparência]","[<a href=""https://radar.tce.mt.gov.br/extensio...",35.52,False
329,2516,664,Disponibilidade,https://janiopolis.atende.net/cidadao/,True,"<html class=""font-size-default"" lang=""pt-br""><...",[],[],None,None,"[Radar da Transparência, Radar da Transparênci...","[<a href=""https://radar.tce.mt.gov.br/extensio...",48.30,False
339,3754,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],None,None,[Radar da Transparência Pública],"[<div class=""portal-widget-link-title"">Radar d...",18.12,False
354,5228,664,Disponibilidade,https://tibagi.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[Radar da Transparência],"[<a class=""elementor-button elementor-button-l...",36.02,False
361,4101,664,Disponibilidade,https://www.ranchoalegre.pr.gov.br/,True,"<html lang=""pt-BR"" class=""fontawesome-i2svg-ac...",[],[],None,None,[],"[<img src=""/assets/radarTransparencia.png"" sty...",31.24,False
368,3779,664,Disponibilidade,https://www.pien.pr.gov.br/,True,"<html lang=""pt-br""><head>\n\n <!-- Google T...",[],[],None,None,"[Radar da Transparência Pública, , Radar da Tr...","[<a class=""d-flex p-4 transition h-100"" title=...",24.90,False
369,4108,664,Disponibilidade,https://reboucas.pr.gov.br/,True,"<html lang=""pt-BR"" style=""transform: none;""><!...",[],[],None,None,"[, Radar da Transparência Pública, ]","[<a href=""https://cr2transparencia.com.br/rada...",29.94,False
373,2367,664,Disponibilidade,https://itaperucu.pr.gov.br/,True,"<html lang=""pt-BR"" class=""s-light site-s-light...",[],[],None,None,[],"[<a href=""/portal-da-transparencia/radar/"">\n\...",24.14,False
381,2975,664,Disponibilidade,https://marquinho.pr.gov.br/MapaAcessoTranspar...,True,"<html lang=""pt-BR""><head>\n <meta name=""vie...",[],[],None,None,[ Radar da Transparência Pública],"[<a href=""https://radardatransparencia.com.br/...",19.63,False

In [ ]:
q_selenium_664.html_elemento_interacao_1[368]

['<a class="d-flex p-4 transition h-100" title="Link de acesso ao site Radar da Transparência Pública" href="https://radar.tce.mt.gov.br/extensions/radar-da-transparencia-publica/radar-da-transparencia-publica.html" target="_blank">\n                    <article class="text-center">\n                        <img class="w-100 p-4" src="https://www.pien.pr.gov.br/themes/prefeitura-web/assets/images/logo-radar.png" title="Brasão da Radar da Transparência Pública" alt="[Brasão da Radar da Transparência Pública]">\n                        <h3>Radar da Transparência Pública</h3>\n                    </article>\n                </a>',
 '<img class="w-100 p-4" src="https://www.pien.pr.gov.br/themes/prefeitura-web/assets/images/logo-radar.png" title="Brasão da Radar da Transparência Pública" alt="[Brasão da Radar da Transparência Pública]">',
 '<h3>Radar da Transparência Pública</h3>']

In [ ]:
elemento_ausente.pagina_scraped[319]

'<html lang="pt-BR" class="sr" style="height: 100%;"><head><base href="https://www.riobom.pr.gov.br/">\n  <meta charset="UTF-8">\n  <meta name="theme-color" content="#2f71cd">\n\n  <title>Prefeitura Municipal  de Rio Bom</title>\n                                    <meta name="description" content="Prefeitura Municipal  de Rio Bom.">\n                                    <meta name="keywords" content="prefeitura, municipal, rio bom, cidade">\n                                    <link rel="canonical" href="http://www.riobom.pr.gov.br/">\n                <meta property="og:url" content="http://www.riobom.pr.gov.br/">\n                <meta property="og:image" content="https://www.riobom.pr.gov.br/admin/globalarq/logo/5915d5643f6bb9e3f017412a33a2b5a6.png">\n                <meta property="og:title" content="Prefeitura Municipal de Rio Bom">\n                <meta property="og:description" content="Prefeitura Municipal de Rio Bom">\n                <meta property="og:site_name" content="Prefeitura Municipal de Rio Bom">\n                <meta property="og:type" content="website">\n              <meta name="viewport" content="width=device-width, initial-scale=1.0">  <link href="/admin/globalarq/logo/favicon.webp" rel="shortcut icon" type="image/vnd.microsoft.icon">\n  <link rel="stylesheet" type="text/css" href="/site/js/plugins/camera-master/css/camera.css">                                                                                       \n      \n      <link rel="stylesheet" as="style" type="text/css" href="/site2/css/speech.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/speech.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/normalize.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/normalize.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/icomoon_v2/style.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/icomoon_v2/style.css"></noscript>\n    \n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/bootstrap-4.3.1/css/bootstrap.min.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/bootstrap-4.3.1/css/bootstrap.min.css"></noscript>\n    \n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/font/ArialRoundedMTBold/styles.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/font/ArialRoundedMTBold/styles.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/font/MyriadPro-Bold/styles.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/font/MyriadPro-Bold/styles.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/font/Oswald-RegularItalic/styles.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/font/Oswald-RegularItalic/styles.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/font/ProximaNova-Regular/styles.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/font/ProximaNova-Regular/styles.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/catamaran-cufonfonts-webfont/style.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/catamaran-cufonfonts-webfont/style.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/gotham-rounded/stylesheet.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/gotham-rounded/stylesheet.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/kulim-park/stylesheet.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/kulim-park/stylesheet.css"></noscript>\n\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/poppins/stylesheet.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/poppins/stylesheet.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/font/open-sans/stylesheet.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/font/open-sans/stylesheet.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/ekko-lightbox.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/ekko-lightbox.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/js/plugins/acessibilidade/jbility.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/js/plugins/acessibilidade/jbility.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/animate.min.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/animate.min.css"></noscript>\n    <link rel="stylesheet" type="text/css" href="/site2/js/plugins/owlcarousel/owl.carousel.min.css">\n    <link rel="stylesheet" as="style" type="text/css" href="/site/css/font/fontawesome/font-awesome.min.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site/css/font/fontawesome/font-awesome.min.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/js/plugins/calendario-evento/datepickk.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/js/plugins/calendario-evento/datepickk.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/js/plugins/calendario-diario/jquery.e-calendar.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/js/plugins/calendario-diario/jquery.e-calendar.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/js/plugins/menu/sm-core-css.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/js/plugins/menu/sm-core-css.css"></noscript>\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/js/plugins/menu/sm-clean.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/js/plugins/menu/sm-clean.css"></noscript>\n\n    <link rel="stylesheet" type="text/css" href="/site/js/plugins/tradutor/tradutor.css">\n    <link rel="stylesheet" type="text/css" href="/site2/css/css_v2.css">\n\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/cssCustom.css?v=1774877128" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/cssCustom.css?v=1774877128"></noscript>\n\n    <link rel="stylesheet" href="/site2/css/css-mobile_v2.css">\n\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/hover-min.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/hover-min.css"></noscript>\n\n    <link rel="stylesheet" as="style" type="text/css" href="/site2/css/boletim.css" onload="this.onload=null;this.rel=\'stylesheet\'">\n    <noscript><link rel="stylesheet" href="/site2/css/boletim.css"></noscript>\n  \n  \n  <style>\n    :root {\n      /*cores padrão do projeto*/\n      --branco: #FFFFFF;\n      --branco_v2: #FFFFFF;\n      --preto: #555555;\n      --cinza-1_v2: #F7F6F2;\n      --cinza-2_v2: #E8E7E3;\n      --cinza-3_v2: #D0D0D0;\n      --cinza-4_v2: #84868C;\n      --cinza-5_v2: #606466;\n      --cinza-6_v2: #5E5F61;\n      --font-primaria_v2: #606466;\n      --font-secundaria_v2: #606466;\n      --fontConteudo: "ProximaNova-Regular";\n      --fontItalic: "Oswald-RegularItalic";\n      --fontTituloRodape: "MyriadPro-Bold";\n      --fontSubTitulo: "ArialRoundedMTBold";\n      --tamanho-fonte-cidade: 40px;\n      --cor-primaria: #2f71cd;\n      --cor-secundaria: #5697f3;\n      --cor-icon: #2f71cd;\n    }\n\n    .img-logo {\n      width: 100px;\n      height: 100px;\n      background: url(/admin/globalarq/logo/5915d5643f6bb9e3f017412a33a2b5a6.png);\n      background-size: 100% 100%;\n    }\n\n    .img-logo-rodape {\n      width: 100px;\n      height: 100px;\n      background: url(/admin/globalarq/logo/4455345acaea2de710a301da0ef1bee3.png);\n      background-size: 100% 100%;\n      margin-bottom: 10px;\n    }\n\n    .btn-menu-mobile {\n      background: url(\'../../../../admin/globalarq/logo/5915d5643f6bb9e3f017412a33a2b5a6.png\') no-repeat;\n      background-size: 50px auto;\n    }\n\n    .caixa-dialogo {\n      background: linear-gradient(rgba(255, 255, 255, .9), rgba(255, 255, 255, .9)), url(\'../../admin/globalarq/logo/5915d5643f6bb9e3f017412a33a2b5a6.png\') space;\n    }\n  </style>\n\n          <script async="" src="https://analytics.kingpage.com.br/matomo.js"></script><script>\n          var _paq = window._paq = window._paq || [];\n          /* tracker methods like "setCustomDimension" should be called before "trackPageView" */\n          _paq.push([\'trackPageView\']);\n          _paq.push([\'enableLinkTracking\']);\n          (function() {\n              var u="https://analytics.kingpage.com.br/";\n              _paq.push([\'setTrackerUrl\', u+\'matomo.php\']);\n              _paq.push([\'setSiteId\', \'94\']);\n              var d=document, g=d.createElement(\'script\'), s=d.getElementsByTagName(\'script\')[0];\n              g.async=true; g.src=u+\'matomo.js\'; s.parentNode.insertBefore(g,s);\n          })();\n      </script>\n    <link type="text/css" rel="stylesheet" charset="UTF-8" href="https://www.gstatic.com/_/translate_http/_/ss/k=translate_http.tr.2f3WBw8L4SI.L.W.O/am=AAAO/d=0/rs=AN8SPfqEMEisTZAmeZOnTrf_mfOPDE49Nw/m=el_main_css"><script type="text/javascript" charset="UTF-8" src="https://translate.googleapis.com/_/translate_http/_/js/k=translate_http.tr.en_US.J2mRtXrMjsU.O/am=AABA/d=1/exm=el_conf/ed=1/rs=AN8SPfpOGvJ-zwx790JtiLHagu-JfI_hLQ/m=el_main"></script><style>@-webkit-keyframes marqueeAnimation-1405171  { 100%  {transform:translateX(-565.688px)}}</style><style>@-webkit-keyframes marqueeAnimation-5306160  { 100%  {transform:translateX(-539.583px)}}</style><script src="/site2/js/plugins/acessibilidade/vlibras-plugin.js"></script><style>@charset "UTF-8";\n[vp] .vpw-vlibras-span {\n  font-family: "Open Sans", sans-serif; }\n\n[vp] .vpw-settings {\n  position: relative;\n  width: 100%;\n  height: calc(100% - 40px); }\n  [vp] .vpw-settings .vpw-content {\n    position: relative;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    z-index: 6;\n    background-color: #003f86;\n    color: white; }\n    [vp] .vpw-settings .vpw-content .vpw-flag {\n      position: absolute;\n      height: 24px;\n      margin-top: -12px;\n      margin-left: 4px;\n      border: none;\n      border-radius: 5px; }\n    [vp] .vpw-settings .vpw-content > .vpw-bar {\n      position: absolute;\n      width: 100%;\n      height: 54px; }\n      [vp] .vpw-settings .vpw-content > .vpw-bar .vpw-title {\n        position: absolute;\n        top: 16px;\n        left: 50px;\n        color: #6481b8;\n        font-size: 12px;\n        font-weight: bold; }\n    [vp] .vpw-settings .vpw-content > ul {\n      list-style-type: none;\n      margin: 0;\n      padding: 0 11%;\n      font-family: "Open Sans", sans-serif; }\n      [vp] .vpw-settings .vpw-content > ul li {\n        position: relative;\n        padding: 19px 0;\n        color: white;\n        border-bottom: 0; }\n        [vp] .vpw-settings .vpw-content > ul li .vpw-name {\n          position: absolute;\n          left: 0px;\n          margin-top: -10px;\n          font-size: 14px; }\n        [vp] .vpw-settings .vpw-content > ul li .vpw-percent {\n          float: right;\n          margin-top: -7px;\n          font-size: 11px;\n          color: rgba(255, 255, 255, 0.6);\n          width: 30px;\n          margin-right: -6px;\n          margin-left: -4px;\n          text-align: center; }\n        [vp] .vpw-settings .vpw-content > ul li .arrow-right-opac,\n        [vp] .vpw-settings .vpw-content > ul li .arrow-left-opac {\n          margin-top: -13px;\n          width: 25px;\n          float: right; }\n      [vp] .vpw-settings .vpw-content > ul li:hover {\n        color: #67c8d5; }\n      [vp] .vpw-settings .vpw-content > ul .vpw-position {\n        display: none; }\n      [vp] .vpw-settings .vpw-content > ul .vpw-opacity {\n        display: none; }\n      [vp] .vpw-settings .vpw-content > ul .vpw-localism {\n        padding: 24px 0; }\n        [vp] .vpw-settings .vpw-content > ul .vpw-localism .vpw-flag {\n          right: 27px;\n          height: 24px; }\n        [vp] .vpw-settings .vpw-content > ul .vpw-localism .vpw-abbrev {\n          position: absolute;\n          right: 0px;\n          margin-top: -9px;\n          font-size: 14px;\n          font-weight: bold; }\n        [vp] .vpw-settings .vpw-content > ul .vpw-localism .vpw-arrow {\n          position: absolute;\n          right: 16px;\n          height: 13px;\n          margin-top: -6px; }\n    [vp] .vpw-settings .vpw-content > .vpw-localism {\n      position: absolute;\n      top: 0;\n      left: 0;\n      width: 100%;\n      height: 100%;\n      z-index: 7;\n      background-color: white;\n      border: 1px solid rgba(0, 0, 0, 0.2);\n      border-radius: 2px; }\n      [vp] .vpw-settings .vpw-content > .vpw-localism:not(.active) {\n        visibility: hidden;\n        opacity: 0;\n        -webkit-transition: visibility 0s, opacity 0.3s;\n        transition: visibility 0s, opacity 0.3s; }\n      [vp] .vpw-settings .vpw-content > .vpw-localism.active {\n        visibility: visible;\n        opacity: 1;\n        -webkit-transition: visibility 0s, opacity 0.3s;\n        transition: visibility 0s, opacity 0.3s; }\n      [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-name {\n        position: absolute;\n        margin-top: -7px;\n        margin-left: 9px;\n        font-size: 14px;\n        font-weight: bold; }\n      [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-national {\n        position: relative;\n        width: calc(33.33%);\n        margin-top: 6px;\n        padding-top: 16px;\n        display: flex;\n        flex-direction: row;\n        justify-content: center;\n        align-items: center; }\n        [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-national .vpw-name {\n          color: black;\n          position: relative; }\n        [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-national .vpw-flag {\n          position: relative; }\n      [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions {\n        position: relative;\n        width: 100%;\n        height: 100%;\n        box-sizing: content-box;\n        padding: 0px 8px 0px 8px;\n        left: 0;\n        top: 50%;\n        transform: translateY(-50%); }\n        [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions {\n          display: inline-block;\n          position: relative;\n          width: 33.33%;\n          margin-bottom: 1px;\n          padding: 6px 0;\n          margin-top: 1%;\n          cursor: pointer;\n          opacity: 0.5;\n          -webkit-transition: opacity 0.3s;\n          transition: opacity 0.3s; }\n          [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions.selected, [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions:hover {\n            opacity: 1;\n            -webkit-transition: opacity 0.3s;\n            transition: opacity 0.3s; }\n          [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions .vpw-cont {\n            display: flex;\n            flex-direction: row;\n            justify-content: center;\n            align-items: center; }\n          [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions > .vpw-cont .vpw-flag {\n            position: relative;\n            margin: 0; }\n          [vp] .vpw-settings .vpw-content > .vpw-localism .vpw-regions > .vpw-container-regions > .vpw-cont .vpw-name {\n            position: relative;\n            margin: 0 10px 0;\n            color: grey; }\n    [vp] .vpw-settings .vpw-content .vpw-vlibras-logo {\n      position: absolute;\n      left: 50%;\n      transform: translateX(-50%);\n      bottom: 0;\n      z-index: 6; }\n      [vp] .vpw-settings .vpw-content .vpw-vlibras-logo .vpw-vlibras-span {\n        left: 50%;\n        transform: translateX(-50%);\n        position: absolute;\n        bottom: 15%;\n        align-items: center;\n        font-size: 14px; }\n      [vp] .vpw-settings .vpw-content .vpw-vlibras-logo .vpw-logo {\n        width: 100%; }\n  [vp] .vpw-settings > .vpw-wall {\n    position: absolute;\n    top: 0;\n    left: 0;\n    bottom: 0;\n    right: 0;\n    z-index: 5; }\n  [vp] .vpw-settings.active {\n    display: block; }\n    [vp] .vpw-settings.active .vpw-content {\n      left: 0;\n      -webkit-transition: left 0.3s;\n      transition: left 0.3s; }\n    [vp] .vpw-settings.active .vpw-wall {\n      visibility: visible; }\n  [vp] .vpw-settings:not(.active) {\n    display: none; }\n    [vp] .vpw-settings:not(.active) .vpw-content {\n      left: 0;\n      visibility: hidden;\n      -webkit-transition: left 0.3s;\n      transition: left 0.3s; }\n    [vp] .vpw-settings:not(.active) .vpw-wall {\n      visibility: hidden; }\n  [vp] .vpw-settings .vpw-clickable {\n    cursor: pointer; }\n    [vp] .vpw-settings .vpw-clickable:not(:hover) {\n      background-color: inherit;\n      -webkit-transition: 0.12s background-color;\n      transition: 0.12s background-color; }\n    [vp] .vpw-settings .vpw-clickable:hover {\n      -webkit-transition: 0.2s background-color;\n      transition: 0.2s background-color; }\n\n[vp] .vpw-controls-dictionary:not(.vpw-loading-dictionary):before {\n  content: "Dicionário";\n  font-size: 14px;\n  position: absolute;\n  margin-top: -11px; }\n\n[vp] .vpw-controls-dictionary.vpw-loading-dictionary {\n  min-width: 22px;\n  min-height: 22px;\n  margin-top: -17px;\n  position: absolute;\n  border-left: 3px solid rgba(255, 255, 255, 0.2);\n  border-top: 3px solid rgba(255, 255, 255, 0.6);\n  border-bottom: 3px solid white;\n  border-right: 3px solid rgba(255, 255, 255, 0.6);\n  border-style: inset;\n  border-radius: 50%;\n  -webkit-animation: spin 1.5s linear infinite;\n  animation: spin 0.8s linear infinite; }\n\n/*@media (min-width: 600px) {\n  .vpw-settings {\n    &.active {\n      visibility: visible;\n      left: 0;\n\n      -webkit-transition: visibility 0s, left 0.3s;\n      transition: visibility 0s, left 0.3s;\n    }\n\n    &:not(.active) {\n      visibility: hidden;\n      left: -220px;\n\n      -webkit-transition: visibility 0.3s, left 0.3s;\n      transition: visibility 0.3s, left 0.3s;\n    }\n\n    .vpw-content {\n      left: -220px;\n      width: 220px;\n\n\n      .vpw-bar {\n        height: 66px;\n\n\n        .vpw-btn-back {\n          width: 30px;\n          height: 30px;\n          margin-top: 18px;\n          margin-left: 18px;\n        }\n\n        .vpw-title {\n          top: 25px;\n          left: 60px;\n          font-size: 1em;\n        }\n      }\n    }\n  }\n}*/\n</style><style>[vp] {\n  /* Hide default HTML checkbox */\n  /* The slider */\n  /* Rounded sliders */ }\n  [vp] .vpw-switch {\n    position: relative;\n    display: inline-block;\n    width: 60

In [ ]:
elemento_ausente[elemento_ausente["error_cod"] == "NENHUMA_ELEMENTO_LOCALIZADO"]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos,verificado
22,1398,664,Disponibilidade,https://www.pmcds.pr.gov.br/portalTransparencia/,False,"<html><head>\n <meta charset=""UTF-8...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,False,[],[],51.05,[]
55,2257,664,Disponibilidade,http://www.iracemadooeste.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,False,[],[],16.57,[]
81,1918,664,Disponibilidade,http://godoymoreira.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.23,[]
117,3291,664,Disponibilidade,http://www.novaamericadacolina.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.50,[]
124,2274,664,Disponibilidade,http://www.iretama.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.28,[]
146,4280,664,Disponibilidade,http://www.rosariodoivai.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.06,[]
215,3877,664,Disponibilidade,https://planalto.pr.gov.br/portal-transparencia,True,"<html><head>\n\t\t<link href=""//fonts.googleap...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.87,[]
229,5220,664,Disponibilidade,http://www.terrarica.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],15.80,[]
233,189,664,Disponibilidade,https://amapora.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.61,[]
253,3978,664,Disponibilidade,https://portovitoria.pr.gov.br/,True,"<html lang=""pt-BR""><head>\n\t\n\t<meta charset...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],81.73,[]
259,2454,664,Disponibilidade,https://www.ivate.pr.gov.br/,True,"<html><head>\n <meta charset=""UTF-8"">\n...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],84.50,[]
265,573,664,Disponibilidade,https://transparencia.e-publica.net/epublica-p...,True,"<html ng-app=""epublica"" ng-controller=""AppCtrl...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],61.21,[]
279,3287,664,Disponibilidade,http://www.novaalianca.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.28,[]
295,4738,664,Disponibilidade,https://www.facebook.com/prefeiturasaojorgedoi...,True,"<html id=""facebook"" class=""_9dls __fb-light-mo...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],74.87,[]
313,1838,664,Disponibilidade,https://www5.pmfi.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.66,[]
321,2176,664,Disponibilidade,https://imbau.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.21,[]
323,3016,664,Disponibilidade,https://matorico.pr.gov.br/portal/,False,"<html lang=""pt-BR"" class=""scroll-smooth""><head...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],43.75,[]
331,3662,664,Disponibilidade,https://paulafreitas.pr.gov.br/site/,False,<html><head><style>.jquery-ripples { position:...,[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],54.35,[]
350,482,664,Disponibilidade,https://www.bandeirantes.pr.gov.br/ ht...,False,"<html lang=""en""><head><meta charset=""utf-8""><t...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],15.62,[]
370,4843,664,Disponibilidade,https://www.saomiguel.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.88,[]
372,5359,664,Disponibilidade,https://www.ubirata.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.28,[]
386,3810,664,Disponibilidade,https://pinhao.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.82,[]
390,1822,664,Disponibilidade,https://formosadooeste.pr.gov.br/site/,True,"<html><head>\n <meta charset=""UTF-8...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],57.08,[]

In [ ]:
"URL_BLOCKED"
"URL bloqueada"

In [ ]:
frases_bloqueio = ["Performing security verification", "Sorry, you have been blocked","403 Forbidden",
                    "A página solicitada não foi encontrada no servidor.","The request could not be satisfied.",
                    "Desculpe, não conseguimos encontrar o que você está procurando.",
                    "This page is used to test the proper operation ","ERRO 500","Bad Gateway",
                    "Blocked request this country"
                  ]

In [ ]:
[q_selenium_664.html_elemento_interacao_1.empty()]

TypeError: 'bool' object is not callable

In [ ]:
frases = [any(f in str(p) for f in frases_bloqueio) for p in q_selenium_664.pagina_scraped.fillna('')]

In [ ]:
q_selenium_664[frases]

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
7,2888,664,Disponibilidade,https://mandirituba.pr.gov.br/portal-da-transp...,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],15.48
15,1754,664,Disponibilidade,https://fazendariogrande.pr.gov.br/transparencia,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],14.35
21,3644,664,Disponibilidade,https://patobragado.atende.net/subportal/porta...,True,"<html lang=""pt-br""><head>\n <meta http-equiv=...",[],[],URL_BLOCKED,URL bloqueada,[],[],14.55
41,164,664,Disponibilidade,http://45.225.146.100:8090/ portaltransparenci...,False,"<html><head>\n<meta charset=""utf-8"">\n<meta na...",[],[],URL_BLOCKED,URL bloqueada,[],[],13.80
55,2257,664,Disponibilidade,http://www.iracemadooeste.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,False,[],[],16.57
75,1618,664,Disponibilidade,https://douradina.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],StaleElementReferenceException,Message: stale element reference: stale elemen...,[],[],15.71
81,1918,664,Disponibilidade,http://godoymoreira.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.23
117,3291,664,Disponibilidade,http://www.novaamericadacolina.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.50
124,2274,664,Disponibilidade,http://www.iretama.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.28
146,4280,664,Disponibilidade,http://www.rosariodoivai.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.06
173,4099,664,Disponibilidade,https://www.ramilandia.pr.gov.br/site/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.23
192,1933,664,Disponibilidade,https://www.goioere.pr.gov.br/site/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],17.52
194,4312,664,Disponibilidade,https://www.salgadofilho.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],14.55
215,3877,664,Disponibilidade,https://planalto.pr.gov.br/portal-transparencia,True,"<html><head>\n\t\t<link href=""//fonts.googleap...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.87
217,3950,664,Disponibilidade,https://www.portoamazonas.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],19.79
220,1025,664,Disponibilidade,https://www.candoi.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],16.23
229,5220,664,Disponibilidade,http://www.terrarica.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],15.80
233,189,664,Disponibilidade,https://amapora.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.61
275,3951,664,Disponibilidade,https://portobarreiro.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],StaleElementReferenceException,Message: stale element reference: stale elemen...,[],[],15.18
279,3287,664,Disponibilidade,http://www.novaalianca.pr.gov.br/,True,"<html><head>\n<meta http-equiv=""content-type"" ...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],17.28
313,1838,664,Disponibilidade,https://www5.pmfi.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.66
321,2176,664,Disponibilidade,https://imbau.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.21
325,966,664,Disponibilidade,https://campodotenente.pr.gov.br/transparencia,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],15.93
337,1839,664,Disponibilidade,https://fozdojordao.pr.gov.br,True,"<html class=""no-js"" lang=""en-US""><!--<![endif]...",[],[],URL_BLOCKED,URL bloqueada,[],[],14.40
370,4843,664,Disponibilidade,https://www.saomiguel.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.88
372,5359,664,Disponibilidade,https://www.ubirata.pr.gov.br/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],13.28
386,3810,664,Disponibilidade,https://pinhao.eloweb.net/portaltransparencia/1/,True,"<html><head><meta name=""color-scheme"" content=...",[],[],NENHUMA_ELEMENTO_LOCALIZADO,Nenhum elemento final localizado na página con...,[],[],16.82
394,5196,664,Disponibilidade,https://telemacoborba.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],URL_BLOCKED,URL bloqueada,[],[],15.33

In [ ]:
q_selenium_664.where()

In [ ]:
q_selenium_664.link_avaliacao[378]

'https://transparencia.betha.cloud/#/k7LmvDe0yL18JzGy4qfLPw=='

In [ ]:
q_selenium_664.pagina_scraped[378]

'<html><head></head><body>redirecionando login...\n<script src="https://cdn.betha.cloud/auth/ui/v3/callback.js"></script>\n<script>\n  callback.resolve({\n    clientId: \'91a97459-f1d8-4b29-b5fa-2e51d1692623\',\n    baseURL: \'https://transparencia.betha.cloud\'\n  });\n</script>\n</body></html>'

In [ ]:
q_selenium_664.html_elemento_interacao_1[378]

['<style type="text/css">.img-selo[data-v-2a0475cc]{height:84px;background:transparent 0 0 no-repeat padding-box;opacity:1}.img-radar[data-v-2a0475cc]{width:25px;height:25px}.botao-radar[data-v-2a0475cc]{height:45px;width:130px}@media (max-width:768px){.responsive[data-v-2a0475cc]{width:-webkit-fit-content;width:-moz-fit-content;width:fit-content}}.footer__title.footer__title--h3[data-v-2a0475cc]{font-weight:700}.section.footer__sitemap[data-v-2a0475cc]{padding:0 35px}@media (max-width:767px){.section.footer__sitemap[data-v-2a0475cc]{padding:0 20px}}.router-link[data-v-2a0475cc]{text-decoration:none!important;color:#fff;cursor:pointer}.footer[data-v-2a0475cc]{min-height:270px}.section[data-v-2a0475cc]{max-width:none!important}.contrast .footer[data-v-2a0475cc],.contrast .section[data-v-2a0475cc]{border:none!important}.contrast .section[data-v-2a0475cc]{border-top:1px solid #fff!important}.politica[data-v-2a0475cc]{padding:5px}.politica a[data-v-2a0475cc]{color:#fff}</style>']

Verficando a questão 664, relacionada a existência de um elemento que leve ao site do Radar da Transparência (https://radardatransparencia.atricon.org.br/)  foi localizada em 252 dos 397 link testados, sendo 10 vazios, 45 erros de link informados (https://www.tce.pr.gov.br/, https://radar.tce.mt.gov.br/, https://radardatransparencia.atricon.org.br/)

In [ ]:
a = q_selenium(664,217,218)
a

Não foi possível encontrar o elemento desejado para https://www.portoamazonas.pr.gov.br/: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(text(),"RADAR")]"}
  (Session info: chrome=146.0.7680.153); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
#0 0x5b922909b41a <unknown>
#1 0x5b9228aa8270 <unknown>
#2 0x5b9228afbe76 <unknown>
#3 0x5b9228afc0b1 <unknown>
#4 0x5b9228b47074 <unknown>
#5 0x5b9228b44209 <unknown>
#6 0x5b9228aef4cf <unknown>
#7 0x5b9228af0291 <unknown>
#8 0x5b9229060364 <unknown>
#9 0x5b9229063251 <unknown>
#10 0x5b922904d11a <unknown>
#11 0x5b9229063e1e <unknown>
#12 0x5b9229033b10 <unknown>
#13 0x5b9229087f88 <unknown>
#14 0x5b9229088158 <unknown>
#15 0x5b9229099e5e <unknown>
#16 0x1446ea1bcac3 <unknown>

Tempo de execução para https://www.portoamazonas.pr.gov.br/: 21.34s

,entidade_id,id_criterio,item_avaliacao,link_avaliacao,resultado_final,pagina_scraped,elemento_final,html_elemento_final,error_cod,error_msg,elemento_interacao_1,html_elemento_interacao_1,duracao_segundos
0,3950,664,Disponibilidade,https://www.portoamazonas.pr.gov.br/,True,"<html lang=""en-US"" dir=""ltr""><head><title>Just...",[],[],NoSuchElementException,Message: no such element: Unable to locate ele...,None,None,21.34

In [ ]:
q_selenium_664.elemento.value_counts(dropna= False)

In [ ]:
q_selenium_653_1 = q_selenium(653,0,65)
q_selenium_653_1.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653_2 = q_selenium(653,65,130)
q_selenium_653_2.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653_3 = q_selenium(653,130,195)
q_selenium_653_3.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653_4 = q_selenium(653,195,261)
q_selenium_653_4.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653_5 = q_selenium(653,261,325)
q_selenium_653_5.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653_6 = q_selenium(653,325,)
q_selenium_653_6.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653 = pd.concat([q_selenium_653_1,
                            q_selenium_653_2,
                            q_selenium_653_3,
                            q_selenium_653_4,
                            q_selenium_653_5,
                            q_selenium_653_6],ignore_index=True)
q_selenium_653
q_selenium_653.to_csv( 'q_selenium_653.csv', index=False)

In [ ]:
q_selenium_653

In [ ]:
mask = q_selenium_653.link_avaliacao.str.contains('ingad')
mask.fillna(False, inplace = True)
mask.value_counts()

In [ ]:
links_detalhes[['entidade_id','id_criterio','item_avaliacao','link_avaliacao','resultado_final']].query('id_criterio == 653 and item_avaliacao =="Disponibilidade"').drop_duplicates(subset='entidade_id', keep = 'first').iloc[380:None]

In [ ]:
q_selenium_653.query("@mask").pagina_scraped[156]

In [ ]:
q_selenium_653.query("@mask")[['pagina_scraped','title']]

In [ ]:
q_selenium_653.pagina_scraped.notna().sum()

In [ ]:
q_selenium_653.error_cod.value_counts()

In [ ]:
q_selenium_653.title.str.lower().str.contains('transp').fillna(False)

In [ ]:
pd.DataFrame(q_selenium_653.title.value_counts(dropna= False))

In [ ]:
transp_n = q_selenium_653[q_selenium_653['title'].str.lower().str.contains('transp', na = False).fillna(False) == False]
pref_n = transp_n[transp_n['title'].str.lower().str.contains('pref', na = False).fillna(False) == False ]
pref_n[(pref_n['title'].str.lower().str.contains('muni', na = False).fillna(False) == False) & (pref_n['title'].isna()== False)]

In [ ]:
q_selenium_653.link_avaliacao[305]

In [ ]:
q_selenium_653.pagina_scraped[305 ]

In [ ]:
q_selenium_664_1 = q_selenium(664,0,65)

###TESTE INDIVIDUAIS

In [ ]:
def scrape_sync():
    URL = "https://rionegro.pr.gov.br/transparencia"
    page = StealthyFetcher.fetch(
        URL,
        headless=True,
        network_idle=True
    )
    return page

page = scrape_sync()
print(page.status)

In [ ]:
URL = "https://rionegro.pr.gov.br/transparencia"
page = StealthyFetcher.fetch(URL, headless=True, network_idle=True)  # Fetch website under the radar!


html = page.html
print("Status:", page.status)

In [ ]:
URL = "https://rionegro.pr.gov.br/transparencia"

page = StealthyFetcher.fetch(URL, headless=True, network_idle=True)  # Fetch website under the radar!


html = page.html
print("Status:", page.status)

In [ ]:
url = "https://rionegro.pr.gov.br/transparencia"

def scrap_http_1(url):
    page = Fetcher.get(url)
    return page.html, page.title or "", None, None

def scrap_http_session(url):
    try:
        with FetcherSession(impersonate='chrome') as session:
            page = session.get(url, stealthy_headers=True)
        return page.html, page.title or "", None, None
    except Exception as e:
        return None, None, type(e).__name__, str(e)

html, title, err, msg = scrap_http_session(url)

In [ ]:
##Tipo Select##

url = "https://www.ingadigital.com.br/transparencia/?id_cliente=11986"

driver = abrir_driver()

html0 = None
html1 = None
html2 = None

try:
  driver.set_page_load_timeout(30)
  driver.get(url)

  html0 = driver.page_source
  wait = WebDriverWait(driver, 30)
  try:
    wait.until(
      EC.any_of(
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                )
    )
    html1 = driver.page_source
    check_input = driver.find_element(By.ID, 'filterFilterano') #{PARAMENTOS DE BUSCAS PARA FILTRAGEM}
    select = Select(check_input)
    select.select_by_value("2024")
    check_click = driver.find_element(By.CLASS_NAME, 'submit')
    check_click.click()
    wait.until(
        EC.any_of(
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                  EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                  )
        )

  except TimeoutException:
    print("Timeout esperando carregamento principal, seguindo mesmo assim.")
    html2 = driver.page_source

  except Exception as e:
    titulo_text = None
    print(f"Não foi possível encontrar o título para {url}: {e}")

except WebDriverException as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"WebDriver error for {url}: {error_msg}")


except Exception as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"General error for {url}: {error_msg}")
    html2 = driver.page_source
    driver.quit()
finally:
    driver.quit()

In [ ]:
##Tipo elementos de texto##

url = "https://www.instagram.com/saomanoeldopr/"

driver = abrir_driver()

html0 = None
html1 = None
html2 = None

try:
  driver.set_page_load_timeout(30)
  driver.get(url)

  html0 = driver.page_source
  wait = WebDriverWait(driver, 10)

  try:
    wait.until(
      EC.any_of(
                EC.presence_of_all_elements_located((By.NAME,"username")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".bth-card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                )
    )


    html1 = driver.page_source

    #FUNCAO DE LOCALIZACAO
    elements = driver.find_elements(By.TAG_NAME, 'title') #PARAMETRO DE BUSCA

    #FUNCAO DE BUSCA
    #lista de perguntas
    lista_text = []
    for e in elements:
      lista_text.append(e.text)



  except TimeoutException:
    print("Timeout esperando carregamento principal, seguindo mesmo assim.")
    html2 = driver.page_source

  except Exception as e:
    titulo_text = None
    print(f"Não foi possível encontrar o título para {url}: {e}")

except WebDriverException as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"WebDriver error for {url}: {error_msg}")


except Exception as e:
    error_cod = type(e).__name__
    error_msg = str(e)
    print(f"General error for {url}: {error_msg}")
    html2 = driver.page_source
    driver.quit()
finally:
    driver.quit()

In [ ]:
url =  ["https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/servlet/wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg="]

for i in url:

  html_selenium = None
  elemento = None
  html_elemento = None
  error_cod = False
  error_msg = False
  texto_click = None
  html_click = None
  elemento_f = None
  html_elemento_f = None
  tipo_busca = "link"

  if not url:
    print("Erro: URL vazia ou não localizada para raspagem.")


  try:
    driver = abrir_driver()
    driver.get(i)
    wait = WebDriverWait(driver, 40)
    driver.set_page_load_timeout(60)
    driver.implicitly_wait(5)


    try: ##Parâmetros HTML para busca inicial
        wait.until(
            EC.any_of(
                      EC.presence_of_all_elements_located((By.TAG_NAME,"a")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".row")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".close-sub-itens")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".table")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main-content-wrapper")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".card-container")),
                      EC.presence_of_all_elements_located((By.CSS_SELECTOR,".main"))
                      )
            )

        html_selenium = driver.page_source

    except TimeoutException:
        print(f"Timeout esperando carregamento principal para {url}, seguindo mesmo assim.")

    try:
        parametros = ["RADAR","atricon"] #PARAMETRO VINDO DE DF QUESTAOxPARAMETROS

        c , d = buscador(driver, "link", parametros  )

        parametro_navegacao = ["RADAR"]

        for p in parametro_navegacao:
          element_click = driver.find_element(By.XPATH , f'//*[contains(text(),"{p}")]')

          texto = element_click.text
          html = element_click.get_attribute("outerHTML")

          element_click.click()
          driver.implicitly_wait(5)



        e , f = buscador(driver, "link", parametros  )

    except Exception as e:
        error_cod = type(e).__name__
        error_msg = str(e)
        print(f"Erro na busca por elementos: {error_msg}")

  finally:
      driver.quit()

print("Encontrados os seguintes links:", c)
print("HTML dos elementos encontrados:", d )
print("Encontrados os seguintes links:", e)
print("HTML dos elementos encontrados:", f )

Encontrados os seguintes links: []
HTML dos elementos encontrados: []
Encontrados os seguintes links: ['https://radardatransparencia.atricon.org.br/radar-da-transparencia-publica.html']
HTML dos elementos encontrados: ['<a id="ygtvlabelel20" class="BasicNodeTextDecoration" style="background:url(/etransparencia.pm.santamonica.pr/static/Resources/RelAnexos.gif) no-repeat;padding-left: 20px;" href="https://radardatransparencia.atricon.org.br/radar-da-transparencia-publica.html" target="_blank" onclick="return YAHOO.widget.TreeView.getNode(\'TREEVIEW1Container\',20).onLabelClick(YAHOO.widget.TreeView.getNode(\'TREEVIEW1Container\',20))"><span id="ygtvlabelel20Span" class="NodeTextDecoration" style=" undefined">Link Acesso..</span></a>']

In [ ]:
html

'<span id="ygtvlabelel19Span" class="NodeTextDecoration" style=" undefined">RADAR NACIONAL DE TRANSPARÊNCIA</span>'

In [ ]:
html_selenium

'<html lang="pt"><head>\n<meta name="generator" content="GeneXus Java 15_0_6-116888">\n<meta name="description" content="ww Modelo">\n<!--[if IE]><meta http-equiv="page-enter" content="blendTrans(Duration=0.1)"/><![endif]-->\n<meta name="fragment" content="!">\n<meta http-equiv="content-type" content="text/html; charset=UTF-8">\n<title>e-transparência</title>\n<link rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/AspSelectBox/tema/jquery-ui-1.10.1.custom.css">\n<link rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/AspSelectBox/tema/jquery.ui.combogrid.css">\n<style id="gx-dom-fixes">.gx-center-align {text-align:center;}.gx-center-align > p,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-center-align > table,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-center-align > div,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-center-align > fieldset,.gx-center-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-center-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:auto;margin-right:auto;}.gx-right-align {text-align:right;}.gx-right-align > p,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-right-align > table,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-right-align > div,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-right-align > fieldset,.gx-right-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-right-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:auto;margin-right:0;}.gx-left-align {text-align:left;}.gx-left-align > p,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > p, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > p,.gx-left-align > table,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > table, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > table,.gx-left-align > div,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > div, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > div,.gx-left-align > fieldset,.gx-left-align > div.gx-content-placeholder > div.gx-ct-body > fieldset, .gx-left-align > div.gxwebcomponent > div.gxwebcomponent-body > fieldset{margin-left:0;margin-right:auto;}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}.gx-tab-padding-fix-0{padding:0px}.gx-tab-padding-fix-1{padding:1px}.gx-tab-padding-fix-5{padding:5px}.gx-tab-spacing-fix-0{border-collapse:separate; border-spacing:0px}.gx-tab-spacing-fix-2{border-collapse:separate; border-spacing:2px}.gx-tab-spacing-fix-3{border-collapse:separate; border-spacing:3px}</style><link id="gxtheme_css_reference" rel="stylesheet" type="text/css" href="/etransparencia.pm.santamonica.pr/static/Resources/Portuguese/tmPortal.css?2025121115525298">\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/jquery.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxtimezone.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxgral.js?116888"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/gxcfg.js?202512111551741"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/yahoo.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/event.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/treeview.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/dom.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/yahoo-dom-event.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/dragdrop.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/assets/js/DDSend.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/Treeview/TreeviewRender.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/js/jquery-ui-1.10.1.custom.min.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/js/jquery.ui.combogrid-1.6.3.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspSelectBox/AspSelectBoxRender.js"></script>\n<script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/JSHandler/JSHandlerRender.js"></script>\n<link rel="shortcut icon" href="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/imgIconePadrao.ico" type="images/x-icon"><style>[vw] [vw-access-button]{display:none;flex-direction:row-reverse;width:40px;height:40px;cursor:pointer;overflow:hidden;position:absolute;border-radius:8px;transition:all 0.5s ease;right:0;left:auto}[vw] [vw-access-button] img{max-height:40px;transition:all 0.5s ease;border-radius:8px;opacity:1 !important;visibility:visible !important}[vw] [vw-access-button] .vp-access-button{width:40px;height:40px;z-index:1}[vw] [vw-access-button] .vp-pop-up{position:absolute;height:40px;min-width:150px;z-index:0;left:0;right:auto}[vw] [vw-access-button]:hover{width:200px}[vw] [vw-access-button].isLeft{flex-direction:row;left:0;right:auto}[vw] [vw-access-button].isLeft .vp-pop-up{left:auto;right:0}[vw] [vw-access-button].isTopOrBottom:hover{bottom:-20px;top:0;margin-right:-80px}[vw] [vw-access-button].active{display:flex}\n</style><style>[vw].left [vw-plugin-wrapper]{float:left}[vw] [vw-plugin-wrapper]{position:relative;display:none;width:300px;height:100%;float:right;background:white;-webkit-box-shadow:0px 0px 15px rgba(0,0,0,0.2);-moz-box-shadow:0px 0px 15px rgba(0,0,0,0.2);box-shadow:0px 0px 15px rgba(0,0,0,0.2);border-radius:12px;-moz-border-radius:12px;-webkit-border-radius:12px}[vw] [vw-plugin-wrapper].active{display:-webkit-flex;display:flex;flex-direction:column;-webkit-flex-direction:column;height:450px;max-width:100%;min-height:100%}\n</style><style>div[vw]{position:fixed;max-width:95vw;min-height:40px;min-width:40px;z-index:2147483645 !important;display:none;margin:10px !important}div[vw].enabled{display:block}div[vw].active{margin-top:-285px}div[vw].left{left:0;right:initial}\n</style><link type="text/css" rel="stylesheet" media="screen" href="https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/static/Treeview/assets/css/default/tree.css"></head>\n<body class="Form Form-fx" style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);" data-hasenter="false" data-skiponenter="false">\n<form id="MAINFORM" name="MAINFORM" method="post" tabindex="-1" class="Form" data-gx-class="Form" novalidate="" action="wprelatorioconsulta?+LWxykPEPEYjnv1U6qEU0QKWevNanJ7LiINCsD2f9Sg=">\n\n\n\n<div class="gx-call-target top off empty"><div class="gxwebcomponent" id="gxHTMLWrpMPW9996"></div></div><div id="gx-column-targets"><div class="gx-call-target left off empty"><div class="gxwebcomponent" id="gxHTMLWrpMPW9999"></div></div><div class="gx-center-target"><input type="submit" style="display:none"><table id="TABFUNDO_MPAGE" class="gx-tab-spacing-fix-0 Table" data-cellpadding="0" data-cellspacing="0" style="margin-left:auto; margin-right: auto; height: 100%; width: 100%;"><tbody><tr><td class="gx-tab-padding-fix-0 "><table id="TABIMAGEM_MPAGE" class="gx-tab-spacing-fix-0 TabelaImgFundo" data-cellpadding="0" data-cellspacing="0" style="height: 100%; width: 100%;"><tbody><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center;vertical-align:top" class="gx-tab-padding-fix-0  "><table id="TABPRINCIPAL_MPAGE" class="gx-tab-spacing-fix-0 Table" data-cellpadding="0" data-cellspacing="0" style="height: 100%; width: 1000px;"><tbody><tr><td style="height:100px" class="gx-tab-padding-fix-0   "><div class="gxwebcomponent" id="gxHTMLWrpMPW0011"><script type="text/javascript" src="/etransparencia.pm.santamonica.pr/static/AspFontSize/AspFontSizeRender.js"></script>\n<div class="gxwebcomponent-body Form-fx"><div><span class="gx_ev ErrorViewerBullet" id="MPW0011gxErrorViewer"></span></div><table id="MPW0011TABCABLOGOTIPO" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td data-align="right" style="text-align:-khtml-right;text-align:-moz-right;text-align:-webkit-right;height:5px" class="gx-tab-padding-fix-0     ">&nbsp;</td></tr><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center" class="gx-tab-padding-fix-0     "><table id="MPW0011TABLE3" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td class="gx-tab-padding-fix-0       "><table id="MPW0011TABLE4" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 15px;"><tbody><tr><td class="gx-tab-padding-fix-0         "></td></tr></tbody></table></td><td class="gx-tab-padding-fix-0       "><a href="portal" class="gx-image-link"><img src="https://s2.asp.srv.br/etransparencia.pm.santamonica.pr/PublicTempStorage/multimedia/SantaMonica_ITP2025_Prata_ia_759bad3beb99441ebe689af6d60b5045.JPG" id="MPW0011IMGPARAM" alt="" class="Image"></a></td><td style="width:100%" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><a href="portal" class="gx-image-link"><img src="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/logo_etransparencia_head.png" id="MPW0011IMGLOGO" alt="" class="Image"></a></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TABLE2" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 15px;"><tbody><tr><td class="gx-tab-padding-fix-0         "></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td style="height:15px" class="gx-tab-padding-fix-0     "></td></tr></tbody></table><table id="MPW0011TABCABECALHOPERSOLANIZADO" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="display:none; width: 100%;"><tbody><tr><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center" class="gx-tab-padding-fix-0     "><table id="MPW0011TABLE7" class="gx-tab-spacing-fix-0  Table" data-cellpadding="0" data-cellspacing="0" style="width: 100%;"><tbody><tr><td style="width:1px" class="gx-tab-padding-fix-0       "></td><td data-align="center" style="text-align:-khtml-center;text-align:-moz-center;text-align:-webkit-center;height:175px;width:100%" class="gx-tab-padding-fix-0       "><img src="/etransparencia.pm.santamonica.pr/static/Resources/tmPortal/ActionDisabled.gif" id="MPW0011IMGCABPERSONALIZADO" alt="" class="Image"></td><td style="width:100%" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "></td></tr></tbody></table></td></tr></tbody></table><div class="gx_usercontrol" id="MPW0011ASPFONTSIZE1Container"></div><table id="MPW0011TABLECONTAINERCONTRASTE" class="gx-tab-spacing-fix-2  TabelaFlutuante" data-cellpadding="1" data-cellspacing="2"><tbody><tr><td data-align="right" style="text-align:-khtml-right;text-align:-moz-right;text-align:-webkit-right" class="gx-tab-padding-fix-1     "><table id="MPW0011TABLE6" class="gx-tab-spacing-fix-0  TabelaFundoBotao" data-cellpadding="0" data-cellspacing="0" style="margin-left:auto;"><tbody><tr><td style="width:3px" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBDADOSABERTOS" class="gx-tab-spacing-fix-2  VLibras" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><img src="/etransparencia.pm.santamonica.pr/static/Resources/open_padlock_01.png" data-gx-evt="5" id="MPW0011IMAGE2" alt="Dados Abertos" title="Dados Abertos" class="Image" style="width: 21px;height: 19px" onfocus="gx.evt.onfocus(this, 46,\'MPW0011\',false,\'\',0)" data-gx-evt-control="IMAGE2" data-gx-context="[&quot;MPW0011&quot;,false]" tabindex="0"></td></tr></tbody></table></td><td style="width:3px" class="gx-tab-padding-fix-0       "></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBESPACO" class="gx-tab-spacing-fix-2  Table" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><span class="TextBlock" style="display:none;" id="MPW0011TXESPACO">espaco</span></td></tr></tbody></table></td><td class="gx-tab-padding-fix-0       "><table id="MPW0011TBACESSIBILIDADE" class="gx-tab-spacing-fix-2  Table" data-cellpadding="1" data-cellspacing="2" style="margin-left:auto; margin-right: auto; height: 27px; width: 31px;"><tbody><tr><td class="gx-tab-padding-fix-1         "><span class="TextBlock" id="MPW0011TXACESSIBILIDADE">ACESSIBILIDA